<?php

namespace Database\Seeders;

use App\Models\SalesCopilotPlaybook;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SalesCopilotSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->playbooks() as $playbook) {
            SalesCopilotPlaybook::query()->firstOrCreate(['slug' => $playbook['slug']], [
                ...$playbook, 'token' => (string) Str::uuid(), 'category' => 'objections',
                'scenario' => 'Surplus Recovery', 'stage' => 'objection_resolution',
                'priority' => 100, 'active' => true, 'vvr_approved' => true,
                'owner_authored' => true, 'source_reference' => 'Owner-provided VVR Sales Copilot specification',
            ]);
        }
    }

    /** @return list<array<string,mixed>> */
    private function playbooks(): array
    {
        return [
            ['slug'=>'scam-legitimacy','title'=>'Scam / Legitimacy Concern','trigger_phrases'=>['scam','is this legit','legitimate','fraud','trust your company'],'recommended_response'=>'When you say scam... how do you mean? Are you wondering about the money itself... or my company?','tones'=>['confused','curious'],'objective'=>'Clarify what the prospect distrusts before offering proof or defending VVR.','follow_up_questions'=>['What about the funds made you feel like they might not be legitimate?','What specifically would you need to see to feel comfortable that we are a legitimate company?'],'listen_for'=>['They doubt the surplus exists','They doubt Valor Venture','They received several solicitations','They do not understand why they were contacted'],'branches'=>['I do not believe the money is real.','I have never heard of your company.','I have received several letters.','How did you get my information?'],'mistakes_to_avoid'=>['Becoming defensive','Claiming unverified credentials','Explaining the company before clarifying the concern'],'notes'=>'The funds and the company are separate trust questions.'],
            ['slug'=>'diy-concern','title'=>'DIY / I Can Do It Myself','trigger_phrases'=>['do it myself','handle it myself','file it myself','dont need help','do not need help'],'recommended_response'=>'Yeah... I guess you could. What have you already looked into so far?','tones'=>['neutral','curious'],'objective'=>'Let the prospect evaluate their experience without insulting their ability.','follow_up_questions'=>['How comfortable do you feel navigating the court documents and county requirements?'],'listen_for'=>['They have already filed','They have researched but not acted','They are uncertain about requirements','They genuinely prefer DIY'],'branches'=>['I have not looked into it yet.','I already contacted the county.','I know exactly what to file.'],'mistakes_to_avoid'=>['Arguing','Belittling the prospect','Inventing procedural complexity'],'notes'=>'Respect a well-informed DIY decision.'],
            ['slug'=>'send-information','title'=>'Send Me Information','trigger_phrases'=>['send me information','send info','email me something','mail me information'],'recommended_response'=>'Yeah, that is not a problem. Just so I can gather the right information... what exactly are you looking for?','tones'=>['familiar','curious'],'objective'=>'Determine whether this is a real information request or a concealed concern.','follow_up_questions'=>['If the information fits what you are looking for, what would you want the next step to be?'],'listen_for'=>['Legitimacy information','Process explanation','Fee concern','Polite attempt to end the call'],'branches'=>['Information about your company.','How the process works.','What you charge.'],'mistakes_to_avoid'=>['Immediately ending discovery','Sending generic information','Assuming interest or disinterest'],'notes'=>'Send tailored information only after understanding the request.'],
            ['slug'=>'decision-maker','title'=>'Need to Talk to Someone','trigger_phrases'=>['talk to my wife','talk to my husband','talk to my spouse','talk to my attorney','talk to my brother','talk to my sister','talk to my partner','talk to someone'],'recommended_response'=>'Yeah, that is not a problem. Are they someone who would actually be involved in the decision with you, or do you mainly want their opinion?','tones'=>['neutral','curious'],'objective'=>'Understand the other person’s decision role and uncover likely concerns.','follow_up_questions'=>['What do you think they might have questions or concerns about?'],'listen_for'=>['Actual joint decision maker','Advisor only','Hidden fee concern','Legal or family concern'],'branches'=>['They have to agree.','I just want their opinion.','They will probably question the fee.'],'mistakes_to_avoid'=>['Undermining an advisor','Pressuring around a spouse','Assuming the objection is resolved'],'notes'=>'Respect spouses, relatives, attorneys, and advisors.'],
            ['slug'=>'too-good-to-be-true','title'=>'Too Good to Be True','trigger_phrases'=>['too good to be true','sounds too easy','cant be real','cannot be real'],'recommended_response'=>'When you say it sounds too good to be true... which part feels that way?','tones'=>['curious'],'objective'=>'Identify whether the concern is the funds, amount, process, fee, or VVR.','follow_up_questions'=>['What about that part feels uncertain to you?'],'listen_for'=>['Existence of funds','Surplus amount','No-upfront-cost concern','VVR legitimacy','Fee concern'],'branches'=>['The amount.','Why would you help me?','I do not believe the funds exist.'],'mistakes_to_avoid'=>['Using humor before rapport','Shaming skepticism','Giving an aggressive rebuttal'],'notes'=>'The playful option is not the default and requires established rapport.'],
            ['slug'=>'not-interested','title'=>'Not Interested','trigger_phrases'=>['not interested','no interest','dont want it','do not want it'],'recommended_response'=>'Got it. When you say you are not interested... is that because you have already handled the funds, you do not feel like they are actually yours, or you just do not want outside help with it?','tones'=>['neutral','detached'],'objective'=>'Clarify the meaning once, then respect a firm decision.','follow_up_questions'=>['Would you prefer that we close this out and not contact you again?'],'listen_for'=>['Already handled','DIY preference','Not their funds','Firm refusal','Do-not-contact request'],'branches'=>['I already handled it.','I will do it myself.','Stop calling me.'],'mistakes_to_avoid'=>['Fighting a firm refusal','Continuing after DNC','Creating urgency'],'notes'=>'A clear do-not-contact request ends the sales flow.'],
            ['slug'=>'competitor-comparison','title'=>'What Is Different About VVR?','trigger_phrases'=>['different about you','other companies','why your company','what makes you different','compare you'],'recommended_response'=>'Well... maybe nothing. It really depends on what you are comparing. What are you mainly trying to figure out... the fee, how the process works, communication, or whether we are legitimate?','tones'=>['detached','curious'],'objective'=>'Discover the prospect’s comparison criteria before differentiating with verified facts.','follow_up_questions'=>['What matters most to you when comparing the options?'],'listen_for'=>['Fee','Communication','Process','Legitimacy','Competitor promise'],'branches'=>['Your fee.','Whether you are legitimate.','How quickly you communicate.'],'mistakes_to_avoid'=>['Attacking competitors','Claiming VVR is best','Inventing differentiators'],'notes'=>'Use verified facts only.'],
            ['slug'=>'get-back-to-you','title'=>'I Will Get Back to You','trigger_phrases'=>['ill get back to you','i will get back to you','let me think','need to think about it'],'recommended_response'=>'Yeah... that is not a problem. If you have your calendar available, we can put a specific time on it so neither one of us has to chase the other down. Would that be appropriate?','tones'=>['familiar','neutral'],'objective'=>'Create a real follow-up commitment, then uncover what they need to consider.','follow_up_questions'=>['Before we do that, what was it you wanted to go over in your mind... just so I know what questions you might have?'],'listen_for'=>['Fee concern','Trust concern','Spouse or attorney','DIY concern','Another company'],'branches'=>['I need to think about the 12%.','I need to talk to my wife.','I am not sure your company is legitimate.'],'mistakes_to_avoid'=>['Accepting an undefined callback','Inventing calendar scarcity','Ignoring the hidden concern'],'notes'=>'After scheduling, diagnose the actual objection.'],
            ['slug'=>'call-me-later','title'=>'Call Me Later','trigger_phrases'=>['call me later','call me back','not a good time','busy right now'],'recommended_response'=>'That is not a problem. What is your timeframe... later today or tomorrow... so we can put a specific time on the calendar?','tones'=>['familiar','neutral'],'objective'=>'Respect timing and establish a specific follow-up without pressure.','follow_up_questions'=>['Before we schedule it, was there anything specific you wanted to go over when we talk?'],'listen_for'=>['Genuine timing issue','Polite brush-off','Hidden concern','Preferred callback window'],'branches'=>['Tomorrow morning.','I just need to think about the fee.','I am not sure yet.'],'mistakes_to_avoid'=>['Chasing indefinitely','Fake scarcity','Continuing a long pitch when they are busy'],'notes'=>'If a hidden concern appears, switch to that concern immediately.'],
        ];
    }
}
