@php
    $v = fn (string $key, mixed $default = null) => old($key, data_get($aiValues, $key, $default));
    $propertyMatch = $surplusIntakeReview['property_duplicates'][0] ?? null;
    $contactMatch = $surplusIntakeReview['contact_duplicates'][0] ?? null;
    $caseMatch = $surplusIntakeReview['surplus_duplicates'][0] ?? null;
@endphp

<section class="rounded-2xl border border-violet-200 bg-violet-50/60 p-6 dark:border-violet-900 dark:bg-violet-950/20">
    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 class="text-lg font-semibold">Surplus document-intake review</h2><p class="mt-1 text-sm text-slate-500">Candidate facts from {{ $surplusIntakeReview['file_name'] }}. Extracted values are not verified until you review and approve them.</p></div><span class="self-start rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800 dark:bg-amber-900 dark:text-amber-200">Risk level 2 · Approval required</span></div>

    @if($surplusIntakeReview['document_duplicates'])
        <div class="mt-5 rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-200"><strong>Duplicate document warning</strong><ul class="mt-2 list-disc pl-5">@foreach($surplusIntakeReview['document_duplicates'] as $duplicate)<li>{{ $duplicate['label'] }} — {{ $duplicate['reason'] }}</li>@endforeach</ul></div>
    @endif

    <div class="mt-5 overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead><tr class="border-b border-violet-200 text-xs uppercase tracking-wide text-slate-500 dark:border-violet-900"><th class="py-2 pr-4">Extracted fact</th><th class="py-2 pr-4">Candidate value</th><th class="py-2 pr-4">Source</th><th class="py-2">Status</th></tr></thead><tbody class="divide-y divide-violet-100 dark:divide-violet-900/60">@foreach($surplusIntakeReview['fields'] as $field) @if(filled($field['value'] ?? null))<tr><td class="py-3 pr-4 font-medium">{{ str($field['field'])->headline() }}</td><td class="py-3 pr-4">{{ $field['value'] }}</td><td class="py-3 pr-4 text-xs text-slate-500">{{ filled($field['page'] ?? null) ? 'Page '.$field['page'].' · ' : '' }}{{ $field['source_excerpt'] ?? 'Uploaded source' }}</td><td class="py-3"><span class="font-medium">{{ number_format(((float)($field['confidence'] ?? 0)) * 100) }}%</span><span class="block text-[10px] uppercase tracking-wide text-amber-600">Extracted</span></td></tr>@endif @endforeach</tbody></table></div>

    @if($surplusIntakeReview['missing_fields'])<div class="mt-5"><h3 class="text-sm font-semibold">Missing or unverified information</h3><div class="mt-2 flex flex-wrap gap-2">@foreach($surplusIntakeReview['missing_fields'] as $field)<span class="rounded-full bg-slate-200 px-3 py-1 text-xs dark:bg-slate-800">{{ str($field)->headline() }}</span>@endforeach</div></div>@endif
    @if($surplusIntakeReview['warnings'])<div class="mt-5 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/40 dark:text-amber-200"><strong>Safeguards and warnings</strong><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($surplusIntakeReview['warnings'] as $warning)<li>{{ $warning }}</li>@endforeach</ul></div>@endif
</section>

<form method="POST" action="{{ route('vvr-ai.surplus-intakes.approve', $conversation) }}" class="space-y-6" x-data="{ surplus: Number(@js($v('surplus_amount', 0))) || 0, money(value) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value) || 0) } }">@csrf
    <input type="hidden" name="intake_token" value="{{ $surplusIntakeReview['token'] }}">

    <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <h2 class="text-lg font-semibold">1. Property record</h2><p class="mt-1 text-sm text-slate-500">Annual taxes below are stored in tax history and never added to this property’s all-in cost.</p>
        @if($surplusIntakeReview['property_duplicates'])<div class="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm dark:border-rose-900 dark:bg-rose-950/30"><strong>Possible property duplicates</strong>@foreach($surplusIntakeReview['property_duplicates'] as $duplicate)<a href="{{ route('properties.show',$duplicate['id']) }}" target="_blank" class="mt-2 block font-semibold text-rose-700 hover:underline dark:text-rose-300">{{ $duplicate['label'] }} — {{ $duplicate['reason'] }}</a>@endforeach</div>@endif
        <div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="rounded-xl border p-3"><input type="radio" name="property_resolution" value="create" @checked(old('property_resolution', $propertyMatch ? 'use_existing' : 'create') === 'create')> <span class="ml-2 font-medium">Create new property anyway</span></label>@if($propertyMatch)<label class="rounded-xl border p-3"><input type="radio" name="property_resolution" value="use_existing" @checked(old('property_resolution','use_existing') === 'use_existing')> <span class="ml-2 font-medium">Use existing property</span></label>@endif</div>
        @if($propertyMatch)<select name="property_id" class="form-input mt-3">@foreach($surplusIntakeReview['property_duplicates'] as $duplicate)<option value="{{ $duplicate['id'] }}" @selected((string)old('property_id',$propertyMatch['id']) === (string)$duplicate['id'])>{{ $duplicate['label'] }} — {{ $duplicate['reason'] }}</option>@endforeach</select>@endif
        <div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            @foreach(['parcel_id'=>'Parcel ID','county'=>'County','address'=>'Site address','city'=>'City','postal_code'=>'ZIP','acreage'=>'Acreage'] as $key=>$label)<div><label for="{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" value="{{ $v($key) }}" @if($key==='acreage') type="number" min="0" step="0.0001" @endif class="form-input"><x-form-error name="{{ $key }}" /></div>@endforeach
            <div><label for="state" class="text-sm font-medium">State</label><input id="state" name="state" maxlength="2" value="{{ $v('state','FL') }}" class="form-input"><x-form-error name="state" /></div>
            <div><label for="property_type" class="text-sm font-medium">Property type</label><select id="property_type" name="property_type" class="form-input">@foreach($propertyTypes as $type)<option value="{{ $type->value }}" @selected($v('property_type','land')===$type->value)>{{ $type->label() }}</option>@endforeach</select></div>
            <div class="sm:col-span-2 lg:col-span-3"><label for="legal_description" class="text-sm font-medium">Legal description</label><textarea id="legal_description" name="legal_description" rows="3" class="form-input">{{ $v('legal_description') }}</textarea></div>
        </div>
    </section>

    <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <h2 class="text-lg font-semibold">2. Surplus contact</h2><p class="mt-1 text-sm text-slate-500">Creates a Surplus-type contact and preserves the owner’s mailing address separately from the property site.</p>
        @if($surplusIntakeReview['contact_duplicates'])<div class="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm dark:border-rose-900 dark:bg-rose-950/30"><strong>Possible contact duplicates</strong>@foreach($surplusIntakeReview['contact_duplicates'] as $duplicate)<a href="{{ route('contacts.show',$duplicate['id']) }}" target="_blank" class="mt-2 block font-semibold text-rose-700 hover:underline dark:text-rose-300">{{ $duplicate['label'] }} — {{ $duplicate['reason'] }}</a>@endforeach</div>@endif
        <div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="rounded-xl border p-3"><input type="radio" name="contact_resolution" value="create" @checked(old('contact_resolution',$contactMatch?'use_existing':'create')==='create')> <span class="ml-2 font-medium">Create new contact anyway</span></label>@if($contactMatch)<label class="rounded-xl border p-3"><input type="radio" name="contact_resolution" value="use_existing" @checked(old('contact_resolution','use_existing')==='use_existing')> <span class="ml-2 font-medium">Use existing contact</span></label>@endif</div>
        @if($contactMatch)<select name="contact_id" class="form-input mt-3">@foreach($surplusIntakeReview['contact_duplicates'] as $duplicate)<option value="{{ $duplicate['id'] }}" @selected((string)old('contact_id',$contactMatch['id'])===(string)$duplicate['id'])>{{ $duplicate['label'] }} — {{ $duplicate['reason'] }}</option>@endforeach</select>@endif
        <div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            @foreach(['first_name'=>['First name','owner_first_name'],'last_name'=>['Last name','owner_last_name'],'mailing_address_line_1'=>['Mailing address','mailing_address_line_1'],'mailing_address_line_2'=>['Address line 2','mailing_address_line_2'],'mailing_city'=>['Mailing city','mailing_city'],'mailing_state_province'=>['State / province','mailing_state_province'],'mailing_postal_code'=>['Postal code','mailing_postal_code'],'mailing_country'=>['Country','mailing_country']] as $name=>[$label,$source])<div><label for="{{ $name }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $name }}" name="{{ $name }}" value="{{ old($name,data_get($aiValues,$source)) }}" class="form-input"><x-form-error name="{{ $name }}" /></div>@endforeach
        </div>
    </section>

    <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <h2 class="text-lg font-semibold">3. Property tax history</h2><p class="mt-1 text-sm text-slate-500">This historical record is independent of acquisition costs and financial all-in calculations.</p>
        <div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['tax_year'=>'Tax year','market_value'=>'Market value','assessed_value'=>'Assessed value','taxable_value'=>'Taxable value','prior_year_final_tax'=>'Prior-year final tax','proposed_tax'=>'Proposed tax','no_budget_change_tax'=>'No-budget-change tax','non_ad_valorem_assessments'=>'Non-ad valorem'] as $key=>$label)<div><label for="{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" type="number" min="0" step="{{ $key==='tax_year'?'1':'0.01' }}" value="{{ $v($key) }}" class="form-input"><x-form-error name="{{ $key }}" /></div>@endforeach<div class="sm:col-span-2 lg:col-span-4"><label for="assessment_classification" class="text-sm font-medium">Assessment classification</label><input id="assessment_classification" name="assessment_classification" value="{{ $v('assessment_classification') }}" class="form-input"></div></div>
    </section>

    <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <h2 class="text-lg font-semibold">4. Surplus case and follow-up</h2><p class="mt-1 text-sm text-slate-500">The case begins in Research. A 12% VVR fee is configured, but no fee is calculated until an actual surplus amount is confirmed.</p>
        @if($surplusIntakeReview['surplus_duplicates'])<div class="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm dark:border-rose-900 dark:bg-rose-950/30"><strong>Possible Surplus case duplicates</strong>@foreach($surplusIntakeReview['surplus_duplicates'] as $duplicate)<a href="{{ route('surplus.show',$duplicate['token']) }}" target="_blank" class="mt-2 block font-semibold text-rose-700 hover:underline dark:text-rose-300">{{ $duplicate['label'] }} — {{ $duplicate['reason'] }}</a>@endforeach</div>@endif
        <div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="rounded-xl border p-3"><input type="radio" name="surplus_resolution" value="create" @checked(old('surplus_resolution',$caseMatch?'use_existing':'create')==='create')> <span class="ml-2 font-medium">Create new case anyway</span></label>@if($caseMatch)<label class="rounded-xl border p-3"><input type="radio" name="surplus_resolution" value="use_existing" @checked(old('surplus_resolution','use_existing')==='use_existing')> <span class="ml-2 font-medium">Use existing case</span></label>@endif</div>
        @if($caseMatch)<select name="surplus_case_id" class="form-input mt-3">@foreach($surplusIntakeReview['surplus_duplicates'] as $duplicate)<option value="{{ $duplicate['id'] }}" @selected((string)old('surplus_case_id',$caseMatch['id'])===(string)$duplicate['id'])>{{ $duplicate['label'] }} — {{ $duplicate['reason'] }}</option>@endforeach</select>@endif
        <div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div><label for="foreclosure_case_number" class="text-sm font-medium">Foreclosure case number</label><input id="foreclosure_case_number" name="foreclosure_case_number" value="{{ $v('foreclosure_case_number') }}" class="form-input"></div><div><label for="certificate_number" class="text-sm font-medium">Certificate number</label><input id="certificate_number" name="certificate_number" value="{{ $v('certificate_number') }}" class="form-input"></div>@if(auth()->user()->canViewSurplusFinancials())<div><label for="surplus_amount" class="text-sm font-medium">Confirmed surplus amount</label><input id="surplus_amount" name="surplus_amount" type="number" min="0" step="0.01" value="{{ $v('surplus_amount') }}" x-model.number="surplus" class="form-input"><p class="mt-1 text-xs text-slate-500">Leave blank unless the source explicitly proves it.</p></div><div><label class="text-sm font-medium">VVR projected fee pay (12%)</label><div class="form-input bg-amber-50 font-semibold text-amber-900 dark:bg-amber-950/40 dark:text-amber-200" x-text="money(surplus * 0.12)">{{ '$'.number_format((float)$v('surplus_amount',0) * .12, 2) }}</div></div>@endif<div><label for="sale_date" class="text-sm font-medium">Sale date</label><input id="sale_date" name="sale_date" type="date" value="{{ $v('sale_date') }}" class="form-input"></div><div><label for="claim_deadline" class="text-sm font-medium">Claim deadline</label><input id="claim_deadline" name="claim_deadline" type="date" value="{{ $v('claim_deadline') }}" class="form-input"></div></div>
        <label class="mt-5 flex items-start gap-3 rounded-xl border border-slate-200 p-4 dark:border-slate-800"><input type="checkbox" name="create_research_tasks" value="1" @checked(old('create_research_tasks','1')) class="mt-1 rounded"><span><strong class="text-sm">Create four research tasks</strong><span class="mt-1 block text-xs text-slate-500">Verify surplus amount, obtain auction/foreclosure records, verify claimant eligibility, and confirm claim deadline. Existing open tasks with the same titles will not be duplicated.</span></span></label>
    </section>

    <section class="rounded-2xl border border-amber-300 bg-amber-50 p-6 dark:border-amber-900 dark:bg-amber-950/30"><h2 class="font-semibold">Exact approval</h2><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Approval creates or links the selected property, owner contact, Surplus case, separate tax-history record, private source attachment, and selected research tasks in one database transaction. If a required step fails, all new writes roll back. Created records can be archived later, but the audit history remains.</p><label class="mt-4 flex items-start gap-3"><input type="checkbox" name="approve_extracted_data" value="1" required class="mt-1 rounded"><span class="text-sm font-medium">I reviewed and approve these proposed CRM changes.</span></label><x-form-error name="approve_extracted_data" /><button class="mt-5 rounded-lg bg-emerald-700 px-5 py-2.5 text-sm font-semibold text-white hover:bg-emerald-600">Approve and execute Surplus intake</button></section>
</form>
