<x-layouts.app title="VVR AI" heading="VVR AI" subheading="Describe the objective, review the plan, then approve CRM changes">
    <div class="grid gap-6 xl:grid-cols-[260px_minmax(0,1fr)]">
        @include('vvr-ai._sidebar')

        <div class="space-y-6">
            <section class="grid gap-4 md:grid-cols-2">
                <div class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold dark:bg-slate-800">Manual</span><h2 class="mt-4 text-lg font-semibold">Enter a property yourself</h2><p class="mt-2 text-sm leading-6 text-slate-500">Use the regular CRM form with no information sent to an AI provider.</p><a href="{{ route('properties.create') }}" class="mt-5 inline-flex rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold dark:border-slate-700">Add property manually</a></div>
                <div class="rounded-2xl border border-violet-300 bg-violet-50 p-5 dark:border-violet-900 dark:bg-violet-950/30"><span class="rounded-full bg-violet-200 px-3 py-1 text-xs font-semibold text-violet-800 dark:bg-violet-900 dark:text-violet-200">AI action assistant</span><h2 class="mt-4 text-lg font-semibold">Ask VVR AI</h2><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Describe an objective. VVR AI can search authorized CRM data immediately or prepare validated property, pipeline, checklist, task, buyer-search, reporting, and auction actions for your approval.</p></div>
            </section>

            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div><h2 class="text-lg font-semibold">What would you like VVR AI to do?</h2><p class="mt-1 text-sm text-slate-500">Read-only searches can run immediately. Every CRM write is shown as an exact action plan and requires approval.</p></div>
                @if($aiConfigured)
                    <form method="POST" action="{{ route('vvr-ai.intakes.store') }}" enctype="multipart/form-data" class="mt-6 space-y-5">@csrf
                        <div><label for="prompt" class="text-sm font-medium">Prompt</label><textarea id="prompt" name="prompt" rows="6" required maxlength="5000" placeholder="Examples: Move property 24 to Marketing. Show open surplus cases in Putnam County. Move surplus case 12 to Agreement. Create a title task due Friday. I bought this property—use the attached agreement." class="form-input">{{ old('prompt') }}</textarea><x-form-error name="prompt" /></div>
                        <div><label for="document" class="text-sm font-medium">Optional supporting document</label><input id="document" name="document" type="file" accept=".pdf,.docx,.txt,.csv,.jpg,.jpeg,.png" class="form-input"><p class="mt-1 text-xs text-slate-500">PDF, DOCX, TXT, CSV, JPG, JPEG, or PNG · Maximum {{ number_format(config('ai.file_upload_limit_kb') / 1024) }} MB · Stored privately</p><x-form-error name="document" /></div>
                        <label class="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-200"><input type="checkbox" name="acknowledge_external_processing" value="1" required class="mt-1 rounded border-slate-300"><span>I understand that my prompt and any attached file will be transmitted to the configured Google Gemini API. I will not submit sensitive or confidential information under a free-tier account unless VVR has approved that data-processing arrangement.</span></label><x-form-error name="acknowledge_external_processing" />
                        <div class="flex justify-end"><button class="rounded-lg bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-violet-500">Prepare AI plan</button></div>
                    </form>
                @else
                    <div class="mt-6 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/50 dark:text-amber-200"><strong>Gemini is not configured.</strong> Add <code>GEMINI_API_KEY</code> to the private server <code>.env</code> and clear the configuration cache.</div>
                @endif
            </section>

            <section class="rounded-2xl border border-emerald-300 bg-emerald-50/60 p-6 shadow-sm dark:border-emerald-900 dark:bg-emerald-950/20">
                <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><span class="rounded-full bg-emerald-200 px-3 py-1 text-xs font-semibold text-emerald-900 dark:bg-emerald-900 dark:text-emerald-200">CSV contact + Surplus intake</span><h2 class="mt-4 text-lg font-semibold">Import a tax-deed or Stannp list</h2><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Upload the tax-deed format with Sale Date, Tax Deed #, Cert #, Surplus Available, Property ID #, and claimant mailing fields—or the earlier Stannp format. VVR AI maps the rows, groups repeated names, detects existing cases, calculates the 12% projected fee, and pauses for approval.</p></div><span class="self-start rounded-full bg-white px-3 py-1 text-xs font-semibold text-emerald-800 shadow-sm dark:bg-slate-900 dark:text-emerald-300">Parsed privately</span></div>
                <form method="POST" action="{{ route('vvr-ai.surplus-csv-imports.store') }}" enctype="multipart/form-data" class="mt-6 grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(260px,0.7fr)_auto] lg:items-end">@csrf
                    <div><label for="csv_prompt" class="text-sm font-medium">Prompt or instructions</label><input id="csv_prompt" name="prompt" maxlength="2000" value="{{ old('prompt', 'Create Surplus contacts and cases from this CSV.') }}" class="form-input" placeholder="Create Surplus contacts and cases from this CSV."><x-form-error name="prompt" /></div>
                    <div><label for="csv_file" class="text-sm font-medium">Surplus CSV</label><input id="csv_file" name="csv_file" type="file" accept=".csv,text/csv" required class="form-input"><p class="mt-1 text-xs text-slate-500">Up to {{ config('ai.surplus_csv_max_rows', 500) }} rows. The CSV is parsed on the VVR server and is not sent to Gemini.</p><x-form-error name="csv_file" /></div>
                    <button class="rounded-lg bg-emerald-700 px-5 py-2.5 text-sm font-semibold text-white hover:bg-emerald-600">Review CSV plan</button>
                </form>
            </section>

            <section class="rounded-2xl border border-amber-300 bg-amber-50/60 p-6 shadow-sm dark:border-amber-900 dark:bg-amber-950/20">
                <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><span class="rounded-full bg-amber-200 px-3 py-1 text-xs font-semibold text-amber-900 dark:bg-amber-900 dark:text-amber-200">CSV PreTax Auctions intake</span><h2 class="mt-4 text-lg font-semibold">Import upcoming tax deed auctions</h2><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Upload a scheduled Tax Deed list containing contact mailing fields, Listing Type, auction date, Parcel Number, County, owner record name, assessor value, and source links. VVR AI detects existing contacts and PreTax Auction files, shows missing details and conflicts, and waits for approval.</p></div><span class="self-start rounded-full bg-white px-3 py-1 text-xs font-semibold text-amber-800 shadow-sm dark:bg-slate-900 dark:text-amber-300">Parsed privately</span></div>
                <form method="POST" action="{{ route('vvr-ai.pre-auction-csv-imports.store') }}" enctype="multipart/form-data" class="mt-6 grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(260px,0.7fr)_auto] lg:items-end">@csrf
                    <div><label for="pre_auction_csv_prompt" class="text-sm font-medium">Prompt or instructions</label><input id="pre_auction_csv_prompt" name="prompt" maxlength="2000" value="{{ old('prompt', 'Create PreTax Auctions contacts and acquisition files from this CSV.') }}" class="form-input" placeholder="Create PreTax Auctions contacts and acquisition files from this CSV."><x-form-error name="prompt" /></div>
                    <div><label for="pre_auction_csv_file" class="text-sm font-medium">PreTax Auctions CSV</label><input id="pre_auction_csv_file" name="csv_file" type="file" accept=".csv,text/csv" required class="form-input"><p class="mt-1 text-xs text-slate-500">Up to {{ config('ai.pre_auction_csv_max_rows', 500) }} rows. Parsed on the VVR server and not sent to Gemini.</p><x-form-error name="csv_file" /></div>
                    <button class="rounded-lg bg-amber-500 px-5 py-2.5 text-sm font-semibold text-slate-950 hover:bg-amber-400">Review PreTax Auctions plan</button>
                </form>
            </section>

            <section><h2 class="text-sm font-semibold">Suggested commands</h2><div class="mt-3 flex flex-wrap gap-2">@foreach(['Create a Surplus case from this prior-year tax notice', 'I bought this property', 'Show my owned properties', 'Move property 24 to Marketing', 'Show open surplus cases', 'Move surplus case 12 to Agreement', 'What is our property research SOP?', 'Create a due-diligence task for property 24', 'Find investor contacts', 'Show the pipeline summary', 'Add this tax deed auction to the calendar'] as $suggestion)<button type="button" onclick="document.getElementById('prompt').value = @js($suggestion); document.getElementById('prompt').focus()" class="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600 hover:border-violet-400 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">{{ $suggestion }}</button>@endforeach</div></section>
        </div>
    </div>
</x-layouts.app>
