<x-layouts.app title="VVR AI · {{ $conversation->title }}" heading="VVR AI" subheading="Review, approve, execute, and verify">
    <div class="grid gap-6 xl:grid-cols-[260px_minmax(0,1fr)_280px]">
        @include('vvr-ai._sidebar')

        <main class="min-w-0 space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900">
                <div class="space-y-4">
                    @foreach($conversation->messages as $message)
                        <div @class(['flex', 'justify-end' => $message->role === 'user'])><div @class(['max-w-3xl rounded-2xl px-4 py-3 text-sm leading-6', 'bg-violet-600 text-white' => $message->role === 'user', 'bg-slate-100 dark:bg-slate-800' => $message->role !== 'user'])>{{ $message->content }}</div></div>
                    @endforeach
                </div>
            </section>

            @if($errors->any())
                <section class="rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-200"><strong>VVR AI could not complete this step.</strong><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>
            @endif

            @if($preAuctionCsvImportResult)
                <section class="rounded-2xl border border-emerald-300 bg-emerald-50 p-6 dark:border-emerald-900 dark:bg-emerald-950/30"><span class="rounded-full bg-emerald-200 px-3 py-1 text-xs font-semibold text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200">Completed</span><h2 class="mt-4 text-xl font-semibold">PreTax Auctions CSV import completed</h2><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Contacts created</p><p class="mt-1 text-xl font-semibold">{{ count($preAuctionCsvImportResult['created_contacts'] ?? []) }}</p></div><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Contacts reused</p><p class="mt-1 text-xl font-semibold">{{ count($preAuctionCsvImportResult['reused_contacts'] ?? []) }}</p></div><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Files created</p><p class="mt-1 text-xl font-semibold">{{ count($preAuctionCsvImportResult['created_cases'] ?? []) }}</p></div><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Files updated</p><p class="mt-1 text-xl font-semibold">{{ count($preAuctionCsvImportResult['updated_cases'] ?? []) }}</p></div><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Tasks created</p><p class="mt-1 text-xl font-semibold">{{ $preAuctionCsvImportResult['tasks_created'] ?? 0 }}</p></div></div><div class="mt-5 flex flex-wrap gap-2">@foreach([...($preAuctionCsvImportResult['created_cases'] ?? []), ...($preAuctionCsvImportResult['updated_cases'] ?? [])] as $case)<a href="{{ route('pre-auction.show', $case['token']) }}" class="rounded-lg border border-emerald-700 px-3 py-2 text-sm font-semibold text-emerald-800 dark:text-emerald-300">Open {{ $case['case_number'] }}</a>@endforeach @foreach([...($preAuctionCsvImportResult['created_contacts'] ?? []), ...($preAuctionCsvImportResult['reused_contacts'] ?? [])] as $contact)<a href="{{ route('contacts.show', $contact['id']) }}" class="rounded-lg border border-emerald-700 px-3 py-2 text-sm font-semibold text-emerald-800 dark:text-emerald-300">Open {{ $contact['name'] }}</a>@endforeach</div><p class="mt-5 text-sm text-slate-600 dark:text-slate-300">No Property or Calendar record was invented from contact mailing data. Research tasks identify the remaining property address, auction link/time, title, and tax-deed details.</p></section>
            @elseif($surplusCsvImportResult)
                <section class="rounded-2xl border border-emerald-300 bg-emerald-50 p-6 dark:border-emerald-900 dark:bg-emerald-950/30"><span class="rounded-full bg-emerald-200 px-3 py-1 text-xs font-semibold text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200">Completed</span><h2 class="mt-4 text-xl font-semibold">CSV contact and Surplus import completed</h2><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Contacts created</p><p class="mt-1 text-xl font-semibold">{{ count($surplusCsvImportResult['created_contacts'] ?? []) }}</p></div><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Contacts reused</p><p class="mt-1 text-xl font-semibold">{{ count($surplusCsvImportResult['reused_contacts'] ?? []) }}</p></div><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Cases created</p><p class="mt-1 text-xl font-semibold">{{ count($surplusCsvImportResult['created_cases'] ?? []) }}</p></div><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Cases updated</p><p class="mt-1 text-xl font-semibold">{{ count($surplusCsvImportResult['updated_cases'] ?? []) }}</p></div><div class="rounded-xl bg-white p-4 dark:bg-slate-900"><p class="text-xs text-slate-500">Relatives linked</p><p class="mt-1 text-xl font-semibold">{{ count($surplusCsvImportResult['linked_contacts'] ?? []) }}</p></div></div><div class="mt-5 flex flex-wrap gap-2">@foreach([...($surplusCsvImportResult['created_cases'] ?? []), ...($surplusCsvImportResult['updated_cases'] ?? [])] as $case)<a href="{{ route('surplus.show', $case['token']) }}" class="rounded-lg border border-emerald-700 px-3 py-2 text-sm font-semibold text-emerald-800 dark:text-emerald-300">Open {{ $case['case_number'] }}</a>@endforeach @foreach([...($surplusCsvImportResult['created_contacts'] ?? []), ...($surplusCsvImportResult['reused_contacts'] ?? [])] as $contact)<a href="{{ route('contacts.show', $contact['id']) }}" class="rounded-lg border border-emerald-700 px-3 py-2 text-sm font-semibold text-emerald-800 dark:text-emerald-300">Open {{ $contact['name'] }}</a>@endforeach</div><p class="mt-5 text-sm text-slate-600 dark:text-slate-300">{{ $surplusCsvImportResult['tasks_created'] ?? 0 }} property-research task(s) were created. Property records were not created because the CSV contains claimant mailing addresses, not verified property addresses.</p></section>
            @elseif($createdSurplusCase)
                <section class="rounded-2xl border border-emerald-300 bg-emerald-50 p-6 dark:border-emerald-900 dark:bg-emerald-950/30"><span class="rounded-full bg-emerald-200 px-3 py-1 text-xs font-semibold text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200">Completed</span><h2 class="mt-4 text-xl font-semibold">Surplus intake completed successfully</h2><p class="mt-2 text-sm text-slate-600 dark:text-slate-300">The approved records were linked transactionally, tax history was stored separately from acquisition costs, and the source remains private.</p><div class="mt-5 flex flex-wrap gap-3"><a href="{{ route('surplus.show',$createdSurplusCase) }}" class="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Open {{ $createdSurplusCase->case_number }}</a>@if($createdProperty)<a href="{{ route('properties.show',$createdProperty) }}" class="rounded-lg border border-emerald-700 px-4 py-2 text-sm font-semibold text-emerald-800 dark:text-emerald-300">Open property</a>@endif @if($createdContact)<a href="{{ route('contacts.show',$createdContact) }}" class="rounded-lg border border-emerald-700 px-4 py-2 text-sm font-semibold text-emerald-800 dark:text-emerald-300">Open contact</a>@endif</div></section>
            @elseif($createdProperty)
                <section class="rounded-2xl border border-emerald-300 bg-emerald-50 p-6 dark:border-emerald-900 dark:bg-emerald-950/30"><span class="rounded-full bg-emerald-200 px-3 py-1 text-xs font-semibold text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200">Completed</span><h2 class="mt-4 text-xl font-semibold">Property created successfully</h2><p class="mt-2 text-sm text-slate-600 dark:text-slate-300">The approved property was created transactionally, its checklist was initialized, and the source was attached privately.</p><a href="{{ route('properties.show', $createdProperty) }}" class="mt-5 inline-flex rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Open {{ $createdProperty->address }}</a></section>
            @elseif($actionPlan)
                <section @class(['rounded-2xl border p-6', 'border-emerald-300 bg-emerald-50 dark:border-emerald-900 dark:bg-emerald-950/30' => $actionPlan->status === 'completed', 'border-violet-300 bg-violet-50 dark:border-violet-900 dark:bg-violet-950/30' => $actionPlan->status === 'pending_approval', 'border-amber-300 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/30' => $actionPlan->status === 'needs_input', 'border-rose-300 bg-rose-50 dark:border-rose-900 dark:bg-rose-950/30' => in_array($actionPlan->status, ['failed','expired','rejected'], true)])>
                    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p class="text-xs font-bold uppercase tracking-wide text-violet-700 dark:text-violet-300">{{ str($actionPlan->status)->replace('_',' ')->title() }}</p><h2 class="mt-2 text-xl font-semibold">{{ $actionPlan->summary }}</h2></div><span class="self-start rounded-full bg-white/80 px-3 py-1 text-xs font-semibold shadow-sm dark:bg-slate-900">Risk level {{ $actionPlan->risk_level }}</span></div>
                    @if($actionPlan->missing_information_json)<div class="mt-5 rounded-xl bg-white/70 p-4 dark:bg-slate-900/70"><h3 class="text-sm font-semibold">Missing information</h3><ul class="mt-2 list-disc space-y-1 pl-5 text-sm">@foreach($actionPlan->missing_information_json as $missing)<li>{{ $missing }}</li>@endforeach</ul></div>@endif
                    @if($actionPlan->warnings_json)<div class="mt-5 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/40 dark:text-amber-200"><strong>Warnings</strong><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($actionPlan->warnings_json as $warning)<li>{{ $warning }}</li>@endforeach</ul></div>@endif
                </section>

                @if($actionPlan->toolCalls->isNotEmpty())
                    <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div><h2 class="text-lg font-semibold">{{ $actionPlan->status === 'completed' ? 'Completed actions' : 'Exact proposed actions' }}</h2><p class="mt-1 text-sm text-slate-500">Tool names, validated arguments, risk, and execution state are recorded for audit.</p></div><div class="mt-5 space-y-4">@foreach($actionPlan->toolCalls as $call)<article class="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div class="flex flex-col justify-between gap-2 sm:flex-row"><div><p class="font-semibold">{{ $call->sequence }}. {{ $call->action_summary }}</p><p class="mt-1 font-mono text-xs text-slate-500">{{ $call->tool_name }}</p></div><span class="self-start rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold dark:bg-slate-800">{{ str($call->status)->title() }} · Level {{ $call->risk_level }}</span></div><pre class="mt-3 overflow-x-auto rounded-lg bg-slate-950 p-3 text-xs leading-5 text-slate-200">{{ json_encode($call->arguments_json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre>@if($call->result_json)<div class="mt-3 rounded-lg bg-emerald-50 p-3 text-sm dark:bg-emerald-950/30"><strong>Verified result</strong><pre class="mt-2 overflow-x-auto whitespace-pre-wrap text-xs">{{ json_encode($call->result_json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre>@if(data_get($call->result_json,'url'))<a href="{{ data_get($call->result_json,'url') }}" class="mt-2 inline-flex font-semibold text-emerald-700 hover:underline dark:text-emerald-400">Open affected record →</a>@endif</div>@endif</article>@endforeach</div></section>
                @endif

                @if($actionPlan->status === 'pending_approval')
                    <section class="rounded-2xl border border-amber-300 bg-amber-50 p-6 dark:border-amber-900 dark:bg-amber-950/30"><h2 class="font-semibold">Approval required</h2><p class="mt-2 text-sm text-slate-600 dark:text-slate-300">VVR AI will re-check your permissions and validate every argument after approval. All proposed writes run in one transaction and roll back if a required action fails. Approval expires {{ $actionPlan->expires_at?->diffForHumans() }}.</p><div class="mt-5 flex flex-col gap-3 sm:flex-row"><form method="POST" action="{{ route('vvr-ai.plans.approve',[$conversation,$actionPlan]) }}">@csrf<button class="w-full rounded-lg bg-emerald-700 px-5 py-2.5 text-sm font-semibold text-white hover:bg-emerald-600">Approve all actions</button></form><form method="POST" action="{{ route('vvr-ai.plans.reject',[$conversation,$actionPlan]) }}" class="flex flex-1 gap-2">@csrf<input name="rejection_reason" maxlength="1000" placeholder="Optional rejection reason" class="form-input mt-0 flex-1"><button class="rounded-lg border border-rose-300 px-5 py-2.5 text-sm font-semibold text-rose-700 dark:border-rose-800 dark:text-rose-300">Reject</button></form></div></section>
                @endif
            @elseif($preAuctionCsvImportReview && $preAuctionCsvImportReview['import']->status === 'ready')
                @include('vvr-ai._pre_auction_csv_import_review')
            @elseif($surplusCsvImportReview && $surplusCsvImportReview['import']->status === 'ready')
                @include('vvr-ai._surplus_csv_import_review')
            @elseif($surplusIntakeReview)
                @include('vvr-ai._surplus_intake_review')
            @elseif($intakeReview)
                <section class="rounded-2xl border border-violet-200 bg-violet-50/60 p-6 dark:border-violet-900 dark:bg-violet-950/20">
                    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 class="text-lg font-semibold">Proposed property plan</h2><p class="mt-1 text-sm text-slate-500">Candidate facts from {{ $intakeReview['file_name'] }}. Nothing below is verified merely because Gemini extracted it.</p></div><span class="self-start rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800 dark:bg-amber-900 dark:text-amber-200">Risk level 2 · Approval required</span></div>
                    @if($intakeReview['duplicates'])<div class="mt-5 rounded-xl border border-rose-300 bg-rose-50 p-4 dark:border-rose-900 dark:bg-rose-950/40"><h3 class="text-sm font-semibold text-rose-800 dark:text-rose-300">Possible duplicates</h3><div class="mt-2 space-y-2">@foreach($intakeReview['duplicates'] as $duplicate)<a href="{{ route('properties.show', $duplicate['id']) }}" target="_blank" class="block text-sm font-medium text-rose-700 hover:underline dark:text-rose-300">{{ $duplicate['address'] }} — {{ $duplicate['reason'] }}</a>@endforeach</div><p class="mt-2 text-xs text-rose-700 dark:text-rose-300">Exact parcel and normalized-address duplicates remain blocked during final validation.</p></div>@endif
                    <div class="mt-5 overflow-x-auto"><table class="w-full min-w-[720px] text-left text-sm"><thead><tr class="border-b border-violet-200 text-xs uppercase tracking-wide text-slate-500 dark:border-violet-900"><th class="py-2 pr-4">Extracted fact</th><th class="py-2 pr-4">Proposed value</th><th class="py-2 pr-4">Source</th><th class="py-2">Confidence</th></tr></thead><tbody class="divide-y divide-violet-100 dark:divide-violet-900/60">@foreach($intakeReview['fields'] as $field) @if(filled($field['value'] ?? null))<tr><td class="py-3 pr-4 font-medium">{{ str($field['field'])->headline() }}</td><td class="py-3 pr-4">{{ $field['value'] }}</td><td class="py-3 pr-4 text-xs text-slate-500">{{ filled($field['page'] ?? null) ? 'Page '.$field['page'].' · ' : '' }}{{ $field['source_excerpt'] ?? 'User prompt or source file' }}</td><td class="py-3">{{ number_format(((float)($field['confidence'] ?? 0)) * 100) }}%<span class="block text-[10px] uppercase tracking-wide text-amber-600">Extracted</span></td></tr>@endif @endforeach</tbody></table></div>
                    @if($intakeReview['missing_fields'])<div class="mt-5"><h3 class="text-sm font-semibold">Missing information</h3><p class="mt-1 text-xs text-slate-500">Leave these blank, enter them manually if known, or research them after creation.</p><div class="mt-2 flex flex-wrap gap-2">@foreach($intakeReview['missing_fields'] as $field)<span class="rounded-full bg-slate-200 px-3 py-1 text-xs dark:bg-slate-800">{{ str($field)->headline() }}</span>@endforeach</div></div>@endif
                    @if($intakeReview['warnings'])<div class="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950/40 dark:text-amber-200"><strong>Warnings</strong><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($intakeReview['warnings'] as $warning)<li>{{ $warning }}</li>@endforeach</ul></div>@endif
                </section>

                <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="mb-6"><h2 class="text-lg font-semibold">Exact proposed database changes</h2><p class="mt-1 text-sm text-slate-500">Create one property, initialize its standard checklist, and attach the source privately. Correct any value before approval.</p></div><form method="POST" action="{{ route('properties.store') }}">@include('properties._form')</form></section>
            @elseif($conversation->status === 'processing')
                <section class="rounded-2xl border border-slate-200 bg-white p-8 text-center dark:border-slate-800 dark:bg-slate-900"><p class="font-semibold">VVR AI is processing this request.</p><p class="mt-2 text-sm text-slate-500">Refresh shortly if this page was reopened during extraction.</p></section>
            @endif
        </main>

        <aside class="space-y-4">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="text-sm font-semibold">Task context</h2><dl class="mt-4 space-y-3 text-xs"><div><dt class="text-slate-500">Intent</dt><dd class="mt-1 font-medium">{{ str($conversation->intent)->replace('_', ' ')->title() }}</dd></div><div><dt class="text-slate-500">Workflow status</dt><dd class="mt-1 font-medium">{{ str($conversation->status)->replace('_', ' ')->title() }}</dd></div><div><dt class="text-slate-500">Permission</dt><dd class="mt-1 font-medium text-emerald-700 dark:text-emerald-400">Authorized as {{ auth()->user()->role->label() }}</dd></div><div><dt class="text-slate-500">Provider</dt><dd class="mt-1 font-medium">Gemini · backend only</dd></div></dl></section>
            @if($intake)<section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="text-sm font-semibold">Source</h2><p class="mt-3 break-words text-sm font-medium">{{ $intake->original_name }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($intake->size_bytes / 1024, 1) }} KB</p><p class="mt-3 text-xs text-slate-500">Stored privately. It becomes attached to the approved CRM record only after execution succeeds.</p></section>@endif
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="text-sm font-semibold">Execution controls</h2><ul class="mt-3 space-y-2 text-xs text-slate-500"><li>✓ Registered tools only</li><li>✓ Server-side permission checks</li><li>✓ Strict structured plans</li><li>✓ Explicit approval for writes</li><li>✓ Transactional rollback</li><li>✓ Idempotency and AI audit logs</li></ul></section>
        </aside>
    </div>
</x-layouts.app>
