<x-layouts.app title="Edit Email Signature" heading="Edit Email Signature" subheading="This text is appended to outbound messages">
    @include('email._navigation', ['active' => 'signatures'])
    <form method="POST" action="{{ route('email.signatures.update', $signature) }}" x-data="{ linkLabel: '', linkUrl: '', linkError: '', insertLink() { const raw=this.linkUrl.trim(); let parsed; try { parsed=new URL(raw); } catch (error) { this.linkError='Enter a complete URL beginning with https://'; return; } if (!['http:', 'https:'].includes(parsed.protocol)) { this.linkError='Only http:// and https:// links are allowed.'; return; } const field=document.getElementById('body_text'); const label=(this.linkLabel.trim() || raw).replace(/[\[\]]/g, ''); const markup='['+label+']('+parsed.toString()+')'; const start=field.selectionStart; field.value=field.value.slice(0,start)+markup+field.value.slice(field.selectionEnd); field.focus(); field.selectionStart=field.selectionEnd=start+markup.length; this.linkLabel=''; this.linkUrl=''; this.linkError=''; } }" class="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
        @csrf
        <div><label for="name" class="text-sm font-medium">Signature name</label><input id="name" name="name" required maxlength="120" value="{{ old('name', $signature->name) }}" class="form-input"><x-form-error name="name" /></div>
        <div class="mt-5"><label for="body_text" class="text-sm font-medium">Signature text</label><textarea id="body_text" name="body_text" required rows="12" maxlength="10000" class="form-input">{{ old('body_text', $signature->body_text) }}</textarea><x-form-error name="body_text" /></div>
        <section class="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800/50">
            <h2 class="text-sm font-semibold">Insert a hyperlink</h2>
            <p class="mt-1 text-xs text-slate-500">Add clickable text at the current cursor position in your signature. Only HTTP and HTTPS destinations are allowed.</p>
            <div class="mt-3 grid gap-3 sm:grid-cols-[1fr_1.5fr_auto]"><div><label for="signature_link_label" class="text-xs font-medium">Link text</label><input id="signature_link_label" type="text" x-model="linkLabel" class="form-input" placeholder="Visit our website"></div><div><label for="signature_link_url" class="text-xs font-medium">Destination URL</label><input id="signature_link_url" type="url" x-model="linkUrl" class="form-input" placeholder="https://valorventure.us/"></div><button type="button" @click="insertLink()" class="self-end rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700 dark:bg-amber-400 dark:text-slate-950 dark:hover:bg-amber-300">Insert link</button></div>
            <p x-show="linkError" x-text="linkError" class="mt-2 text-xs font-semibold text-red-600"></p>
            <p class="mt-2 text-xs text-slate-500">You can also type <code>[link text](https://example.com)</code> directly.</p>
        </section>
        <div class="mt-5 flex flex-wrap gap-6"><label class="flex items-center gap-2 text-sm"><input type="hidden" name="is_default" value="0"><input type="checkbox" name="is_default" value="1" @checked(old('is_default', $signature->is_default))> Default</label><label class="flex items-center gap-2 text-sm"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $signature->is_active))> Active</label></div>
        <div class="mt-6 flex justify-end gap-3"><a href="{{ route('email.signatures.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm">Cancel</a><button type="submit" class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950">Save signature</button></div>
    </form>
</x-layouts.app>
