@csrf
@if(isset($contact)) @method('PUT') @endif
<div class="grid gap-5 sm:grid-cols-2">
    <div><label for="first_name" class="text-sm font-medium">First name *</label><input id="first_name" name="first_name" value="{{ old('first_name', $contact->first_name ?? '') }}" required class="form-input"><x-form-error name="first_name" /></div>
    <div><label for="last_name" class="text-sm font-medium">Last name *</label><input id="last_name" name="last_name" value="{{ old('last_name', $contact->last_name ?? '') }}" required class="form-input"><x-form-error name="last_name" /></div>
    <div><label for="company" class="text-sm font-medium">Company</label><input id="company" name="company" value="{{ old('company', $contact->company ?? '') }}" class="form-input"><x-form-error name="company" /></div>
    <div><label for="email" class="text-sm font-medium">Email</label><input id="email" name="email" type="email" value="{{ old('email', $contact->email ?? '') }}" class="form-input"><x-form-error name="email" /></div>
    <div><label for="phone" class="text-sm font-medium">Phone</label><input id="phone" name="phone" value="{{ old('phone', $contact->phone ?? '') }}" class="form-input"><x-form-error name="phone" /></div>
    <div class="sm:col-span-2 border-t border-slate-200 pt-5 dark:border-slate-800"><h2 class="font-semibold">Mailing address</h2><p class="mt-1 text-xs text-slate-500">Used for owner, seller, and Surplus correspondence. This is separate from a property site address.</p></div>
    @foreach(['mailing_address_line_1'=>'Address line 1','mailing_address_line_2'=>'Address line 2','mailing_city'=>'City','mailing_state_province'=>'State / province','mailing_postal_code'=>'Postal code','mailing_country'=>'Country'] as $key=>$label)<div><label for="{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" value="{{ old($key, $contact->{$key} ?? '') }}" class="form-input"><x-form-error name="{{ $key }}" /></div>@endforeach
    <div><label for="type" class="text-sm font-medium">Contact type *</label><select id="type" name="type" required class="form-input"><option value="">Choose a type</option>@foreach($types as $type)<option value="{{ $type->value }}" @selected(old('type', isset($contact) ? $contact->type->value : '') === $type->value)>{{ $type->label() }}</option>@endforeach</select><x-form-error name="type" /></div>
    <div><label for="status" class="text-sm font-medium">Status *</label><select id="status" name="status" required class="form-input">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', isset($contact) ? $contact->status->value : 'new') === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="status" /></div>
    <div><label for="assigned_user_id" class="text-sm font-medium">Assigned user</label><select id="assigned_user_id" name="assigned_user_id" class="form-input"><option value="">Unassigned</option>@foreach($assignees as $user)<option value="{{ $user->id }}" @selected((string) old('assigned_user_id', $contact->assigned_user_id ?? '') === (string) $user->id)>{{ $user->name }}</option>@endforeach</select><x-form-error name="assigned_user_id" /></div>
    <div><label for="next_follow_up_at" class="text-sm font-medium">Next follow-up</label><input id="next_follow_up_at" name="next_follow_up_at" type="datetime-local" value="{{ old('next_follow_up_at', isset($contact) && $contact->next_follow_up_at ? $contact->next_follow_up_at->format('Y-m-d\TH:i') : '') }}" class="form-input"><x-form-error name="next_follow_up_at" /></div>
    <div class="sm:col-span-2"><label for="next_follow_up_purpose" class="text-sm font-medium">Follow-up purpose</label><input id="next_follow_up_purpose" name="next_follow_up_purpose" maxlength="255" value="{{ old('next_follow_up_purpose', $contact->next_follow_up_purpose ?? '') }}" placeholder="Example: Discuss offer, request documents, or confirm mailing receipt" class="form-input"><p class="mt-1 text-xs text-slate-500">Optional. This will appear with the next follow-up date in Contacts.</p><x-form-error name="next_follow_up_purpose" /></div>
    <div class="sm:col-span-2">
        @php($selectedProperties = collect(old('property_ids', $selectedPropertyIds ?? []))->map(fn ($id) => (string) $id))
        <input type="hidden" name="property_assignments_present" value="1">
        <label for="property_ids" class="text-sm font-medium">Associated properties</label>
        <select id="property_ids" name="property_ids[]" multiple size="{{ min(max($properties->count(), 4), 10) }}" class="form-input">
            @foreach($properties as $property)<option value="{{ $property->id }}" @selected($selectedProperties->contains((string) $property->id))>{{ $property->address }}, {{ $property->city }}, {{ $property->state }}{{ $property->parcel_id ? ' — '.$property->parcel_id : '' }}</option>@endforeach
        </select>
        <p class="mt-2 text-xs text-slate-500">Hold Ctrl on Windows or Command on Mac to select multiple properties. Ownership remains managed separately on the Property record.</p>
        <x-form-error name="property_ids" /><x-form-error name="property_ids.*" />
    </div>
    <div class="sm:col-span-2"><label for="notes" class="text-sm font-medium">Notes</label><textarea id="notes" name="notes" rows="6" class="form-input">{{ old('notes', $contact->notes ?? '') }}</textarea><x-form-error name="notes" /></div>
</div>
<div class="mt-7 flex justify-end gap-3"><a href="{{ isset($contact) ? route('contacts.show', $contact) : route('contacts.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950">{{ isset($contact) ? 'Save changes' : 'Create contact' }}</button></div>
