<x-layouts.app title="{{ $contact->full_name }}" heading="{{ $contact->full_name }}" subheading="{{ $contact->type->label() }} contact record">
    <div class="mx-auto max-w-5xl"><div class="mb-5 flex justify-end gap-3">@can('create', \App\Models\OutboundEmail::class)<a href="{{ route('email.create',['related_type'=>'contact','related_id'=>$contact->id]) }}" class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950">Send email</a>@endcan @can('update',$contact)<a href="{{ route('contacts.edit',$contact) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Edit</a>@endcan @can('delete',$contact)<form method="POST" action="{{ route('contacts.destroy',$contact) }}" onsubmit="return confirm('Archive this contact?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm font-medium text-rose-600 dark:border-rose-900">Archive</button></form>@endcan</div>
    <section class="grid gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2 dark:border-slate-800 dark:bg-slate-900">@foreach([['Company',$contact->company],['Email',$contact->email],['Phone',$contact->phone],['Status',$contact->status->label()],['Assigned to',$contact->assignedUser?->name],['Next follow-up',$contact->next_follow_up_at?->format('M j, Y g:i A')],['Follow-up purpose',$contact->next_follow_up_purpose]] as [$label,$value])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm">{{ $value ?: '—' }}</dd></div>@endforeach @if(collect([$contact->mailing_address_line_1,$contact->mailing_address_line_2,$contact->mailing_city,$contact->mailing_state_province,$contact->mailing_postal_code,$contact->mailing_country])->filter()->isNotEmpty())<div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Mailing address</dt><dd class="mt-2 text-sm leading-6">{{ collect([$contact->mailing_address_line_1,$contact->mailing_address_line_2,trim(collect([$contact->mailing_city,$contact->mailing_state_province,$contact->mailing_postal_code])->filter()->join(' ')),$contact->mailing_country])->filter()->join(', ') }}</dd></div>@endif @if($contact->notes)<div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Notes</dt><dd class="mt-2 whitespace-pre-line text-sm leading-6">{{ $contact->notes }}</dd></div>@endif</section>

    @can('viewSourceDocuments', $contact)
        @if($contact->intakeFiles->isNotEmpty())<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Source documents</h2><p class="mt-1 text-sm text-slate-500">Private files used during contact intake.</p><div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@foreach($contact->intakeFiles as $file)<div class="flex flex-col justify-between gap-3 py-3 sm:flex-row sm:items-center"><div><p class="text-sm font-medium">{{ $file->original_name }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($file->size_bytes / 1024, 1) }} KB · Attached {{ $file->attached_at?->format('M j, Y g:i A') }}</p></div><a href="{{ route('contacts.intake-files.download', [$contact, $file]) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Download</a></div>@endforeach</div></section>@endif
    @endcan

    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold">Phone activity</h2><p class="mt-1 text-sm text-slate-500">Calls, voicemails, and messages received from Beside.</p></div><a href="{{ route('phone-interactions.index', ['search' => $contact->phone]) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">View all calls</a></div>
        <div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">
            @forelse($contact->phoneInteractions as $interaction)
                <a href="{{ route('phone-interactions.show', $interaction) }}" class="flex flex-col justify-between gap-2 py-3 hover:text-amber-700 sm:flex-row sm:items-center dark:hover:text-amber-400">
                    <span><span class="font-medium">{{ $interaction->event_type->label() }} · {{ $interaction->direction->label() }}</span><span class="mt-1 block text-xs text-slate-500">{{ str($interaction->summary ?: 'No summary supplied')->limit(110) }}</span></span>
                    <span class="shrink-0 text-xs text-slate-500">{{ $interaction->occurred_at->format('M j, Y g:i A') }}</span>
                </a>
            @empty
                <p class="py-6 text-sm text-slate-500">No Beside activity is linked to this contact yet.</p>
            @endforelse
        </div>
    </section>

    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="font-semibold">Associated properties</h2><p class="mt-1 text-sm text-slate-500">Properties connected to this contact independently of the dedicated owner field.</p></div>@can('update',$contact)<a href="{{ route('contacts.edit',$contact) }}#property_ids" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Manage assignments</a>@endcan</div>
        <div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($contact->properties as $property)<a href="{{ route('properties.show',$property) }}" class="flex flex-col justify-between gap-2 py-3 hover:text-amber-700 sm:flex-row sm:items-center dark:hover:text-amber-400"><span><span class="font-medium">{{ $property->address }}</span><span class="mt-1 block text-xs text-slate-500">{{ $property->city }}, {{ $property->state }} {{ $property->postal_code }}</span></span><span class="text-xs text-slate-400">{{ $property->parcel_id ?: 'No parcel ID' }}</span></a>@empty<p class="py-6 text-sm text-slate-500">No properties are assigned to this contact.</p>@endforelse</div>
        @if($contact->ownedProperties->isNotEmpty())<div class="mt-5 border-t border-slate-200 pt-5 dark:border-slate-800"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Listed as owner</p><div class="mt-2 flex flex-wrap gap-2">@foreach($contact->ownedProperties as $property)<a href="{{ route('properties.show',$property) }}" class="rounded-lg bg-slate-100 px-3 py-2 text-sm font-medium hover:bg-amber-100 dark:bg-slate-800 dark:hover:bg-amber-950">{{ $property->address }}</a>@endforeach</div></div>@endif
    </section>

    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold">Deals</h2><p class="mt-1 text-sm text-slate-500">Transactions where this contact is primary or an assigned party.</p></div>@can('create',\App\Models\Deal::class)<a href="{{ route('deals.create',['primary_contact_id'=>$contact->id]) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Add deal</a>@endcan</div>@php($contactDeals = $contact->primaryDeals->merge($contact->deals)->unique('id'))<div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($contactDeals as $deal)<a href="{{ route('deals.show',$deal) }}" class="flex flex-col justify-between gap-2 py-3 hover:text-amber-700 sm:flex-row sm:items-center"><span><span class="font-medium">{{ $deal->title }}</span><span class="mt-1 block text-xs text-slate-500">{{ $deal->deal_number }} · {{ $deal->type->label() }}</span></span><span class="text-xs font-semibold">{{ $deal->status->label() }}</span></a>@empty<p class="py-6 text-sm text-slate-500">No deals are linked to this contact.</p>@endforelse</div></section>

    @if(auth()->user()->canViewSurplusCases())<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between"><div><h2 class="font-semibold">Surplus cases</h2><p class="mt-1 text-sm text-slate-500">Recovery cases where this person is the claimant or another associated contact.</p></div>@can('create',\App\Models\SurplusCase::class)<a href="{{ route('surplus.create',['claimant_contact_id'=>$contact->id]) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Add case</a>@endcan</div>@php($contactSurplusCases = $contact->surplusCases->merge($contact->associatedSurplusCases)->unique('id'))<div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($contactSurplusCases as $case)<a href="{{ route('surplus.show',$case) }}" class="flex justify-between gap-3 py-3 hover:text-amber-700"><span><span class="font-medium">{{ $case->case_number }}</span><span class="mt-1 block text-xs text-slate-500">{{ $case->claimant_contact_id === $contact->id ? 'Primary claimant' : (\App\Enums\SurplusContactRole::tryFrom($case->pivot?->role ?? '')?->label() ?? 'Associated person') }}</span></span><span class="text-xs font-semibold">{{ $case->status->label() }}{{ $case->claim_deadline ? ' · '.$case->claim_deadline->format('M j, Y') : '' }}</span></a>@empty<p class="py-6 text-sm text-slate-500">No surplus cases are linked to this contact.</p>@endforelse</div></section>@endif
    @if(auth()->user()->canViewPreAuctionAcquisitions())<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between"><div><h2 class="font-semibold">PreTax Auction acquisitions</h2><p class="mt-1 text-sm text-slate-500">Owner-interest acquisition files linked to this contact.</p></div>@can('create',\App\Models\PreAuctionAcquisition::class)<a href="{{ route('pre-auction.create',['owner_contact_id'=>$contact->id]) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Add acquisition</a>@endcan</div>@php($preAuctionCases = $contact->preAuctionAcquisitions->merge($contact->associatedPreAuctionAcquisitions)->unique('id'))<div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($preAuctionCases as $case)<a href="{{ route('pre-auction.show',$case) }}" class="flex justify-between gap-3 py-3 hover:text-amber-700"><span><span class="font-medium">{{ $case->case_number }}</span><span class="mt-1 block text-xs text-slate-500">{{ $case->owner_contact_id === $contact->id ? 'Primary owner' : (\App\Enums\PreAuctionContactRole::tryFrom($case->pivot?->role ?? '')?->label() ?? 'Associated person') }}</span></span><span class="text-xs font-semibold">{{ $case->status->label() }}{{ $case->auction_at ? ' · '.$case->auction_at->format('M j, Y') : '' }}</span></a>@empty<p class="py-6 text-sm text-slate-500">No PreTax Auction acquisitions are linked to this contact.</p>@endforelse</div></section>@endif

    <section id="tasks" class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div class="border-b border-slate-200 px-6 py-5 dark:border-slate-800"><h2 class="font-semibold">Associated tasks</h2><p class="mt-1 text-sm text-slate-500">Work and follow-ups connected to this contact.</p></div>
        @can('create', [\App\Models\Task::class, $contact])
            <form method="POST" action="{{ route('contacts.tasks.store', $contact) }}" class="grid gap-3 border-b border-slate-200 bg-slate-50/70 p-5 md:grid-cols-[minmax(220px,1fr)_140px_190px_180px_auto] dark:border-slate-800 dark:bg-slate-950/40">@csrf
                <div><label for="task_title" class="sr-only">Task title</label><input id="task_title" name="title" value="{{ old('title') }}" placeholder="Add a task…" required maxlength="180" class="form-input mt-0"><x-form-error name="title" /></div>
                <div><label for="task_priority" class="sr-only">Priority</label><select id="task_priority" name="priority" class="form-input mt-0">@foreach($taskPriorities as $priority)<option value="{{ $priority->value }}" @selected(old('priority', 'normal') === $priority->value)>{{ $priority->label() }}</option>@endforeach</select></div>
                <div><label for="task_due_at" class="sr-only">Due date</label><input id="task_due_at" name="due_at" type="datetime-local" value="{{ old('due_at') }}" class="form-input mt-0"><x-form-error name="due_at" /></div>
                <div><label for="task_assigned_user_id" class="sr-only">Assigned user</label><select id="task_assigned_user_id" name="assigned_user_id" class="form-input mt-0"><option value="">Unassigned</option>@foreach($assignees as $user)<option value="{{ $user->id }}" @selected((string) old('assigned_user_id', $contact->assigned_user_id) === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div>
                <button class="rounded-lg bg-amber-400 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-amber-300">Add task</button>
            </form>
        @endcan
        <div class="divide-y divide-slate-100 dark:divide-slate-800">
            @forelse($tasks as $task)
                <div class="flex flex-col justify-between gap-4 px-6 py-4 sm:flex-row sm:items-center"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><p @class(['font-medium', 'line-through text-slate-400' => $task->status === \App\Enums\TaskStatus::Completed])>{{ $task->title }}</p><span class="rounded-full bg-slate-100 px-2 py-0.5 text-[11px] dark:bg-slate-800">{{ $task->priority->label() }}</span><span class="text-xs text-slate-400">{{ $task->status->label() }}</span></div><p class="mt-1 text-xs text-slate-500">{{ $task->assignedUser?->name ?? 'Unassigned' }} · {{ $task->due_at?->format('M j, Y g:i A') ?? 'No due date' }}</p></div><div class="flex gap-2">@if($task->status !== \App\Enums\TaskStatus::Completed) @can('update',$task)<form method="POST" action="{{ route('contacts.tasks.complete', [$contact, $task]) }}">@csrf @method('PATCH')<button class="rounded-lg border border-emerald-300 px-3 py-1.5 text-xs font-semibold text-emerald-700 dark:border-emerald-900 dark:text-emerald-400">Complete</button></form>@endcan @endif @can('delete',$task)<form method="POST" action="{{ route('contacts.tasks.destroy', [$contact, $task]) }}" onsubmit="return confirm('Archive this task?')">@csrf @method('DELETE')<button class="rounded-lg border border-slate-300 px-3 py-1.5 text-xs dark:border-slate-700">Archive</button></form>@endcan</div></div>
            @empty <p class="px-6 py-10 text-center text-sm text-slate-500">No tasks are associated with this contact.</p> @endforelse
        </div>
        @if($tasks->hasPages())<div class="border-t border-slate-200 px-6 py-4 dark:border-slate-800">{{ $tasks->links() }}</div>@endif
    </section><x-email-history :record="$contact" /></div>
</x-layouts.app>
