@csrf
@isset($negotiation) @method('PUT') @endisset
@php
    $propertyOptions = $properties->map(fn ($property) => [
        'id' => $property->id,
        'asking' => $property->expected_sales_price,
        'allIn' => $property->all_in_amount,
    ])->values();
    $counterPercentValue = old('counter_percent', $negotiation->counter_percent ?? '');
    $counterPercentValue = filled($counterPercentValue) ? number_format((float) $counterPercentValue, 1, '.', '') : '';
@endphp

<div x-data="{ properties: {{ Illuminate\Support\Js::from($propertyOptions) }}, propertyId: {{ Illuminate\Support\Js::from((string) old('property_id', $negotiation->property_id ?? '')) }}, syncFinancials: {{ Illuminate\Support\Js::from((bool) old('sync_property_financials', $negotiation->sync_property_financials ?? true)) }}, asking: {{ Illuminate\Support\Js::from(old('asking_price', $negotiation->asking_price ?? '')) }}, allIn: {{ Illuminate\Support\Js::from(old('all_in_amount', $negotiation->all_in_amount ?? '')) }}, offer: {{ Illuminate\Support\Js::from(old('buyer_offer', $negotiation->buyer_offer ?? '')) }}, counterPercent: {{ Illuminate\Support\Js::from($counterPercentValue) }}, applyProperty() { const property = this.properties.find(item => String(item.id) === String(this.propertyId)); if (!property) return; if (property.asking !== null) this.asking = property.asking; if (property.allIn !== null) this.allIn = property.allIn; }, offerPercent() { if (!this.offer || !this.asking || Number(this.asking) <= 0) return '—'; return ((Number(this.offer) / Number(this.asking)) * 100).toFixed(1) + '%'; }, counterAmount() { if (!this.counterPercent || !this.asking) return '—'; const amount = Number(this.asking) * Number(this.counterPercent) / 100; return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount); } }" class="grid gap-5 sm:grid-cols-2">
    <div class="sm:col-span-2"><label for="name" class="text-sm font-medium">Plan name</label><input id="name" name="name" required maxlength="180" value="{{ old('name', $negotiation->name ?? '') }}" placeholder="120 Bayberry negotiation" class="form-input"><x-form-error name="name" /></div>
    <div><label for="property_id" class="text-sm font-medium">Property</label><select id="property_id" name="property_id" x-model="propertyId" class="form-input"><option value="">Standalone plan</option>@foreach($properties as $property)<option value="{{ $property->id }}">{{ $property->address }}, {{ $property->city }}, {{ $property->state }}</option>@endforeach</select><x-form-error name="property_id" /><button type="button" x-on:click="applyProperty" class="mt-2 text-xs font-semibold text-amber-700 hover:underline dark:text-amber-400">Use selected property values</button></div>
    <div><label for="buyer_contact_id" class="text-sm font-medium">Buyer contact</label><select id="buyer_contact_id" name="buyer_contact_id" class="form-input"><option value="">Unassigned</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string) old('buyer_contact_id', $negotiation->buyer_contact_id ?? '') === (string) $contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="buyer_contact_id" /></div>
    <div><label for="status" class="text-sm font-medium">Status</label><select id="status" name="status" required class="form-input">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', isset($negotiation) ? $negotiation->status->value : 'draft') === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="status" /></div>
    <div class="sm:col-span-2 rounded-xl border border-slate-200 p-4 dark:border-slate-800"><input type="hidden" name="sync_property_financials" value="0"><label class="flex items-start gap-3"><input type="checkbox" name="sync_property_financials" value="1" x-model="syncFinancials" x-on:change="if (syncFinancials) applyProperty()" class="mt-1 rounded border-slate-300 text-amber-500 focus:ring-amber-500"><span><strong class="block text-sm">Keep financials synced with the linked property</strong><span class="mt-1 block text-xs text-slate-500">When enabled, changes to the property's expected sales price or all-in amount automatically update this plan. Turn it off for a custom scenario.</span></span></label><x-form-error name="sync_property_financials" /></div>
    <div><label for="asking_price" class="text-sm font-medium">Asking price (100%)</label><input id="asking_price" name="asking_price" type="number" required min="0.01" step="0.01" x-model="asking" :readonly="syncFinancials && propertyId" :class="{ 'bg-slate-100 dark:bg-slate-800': syncFinancials && propertyId }" class="form-input"><x-form-error name="asking_price" /></div>
    <div><label for="all_in_amount" class="text-sm font-medium">All-in amount</label><input id="all_in_amount" name="all_in_amount" type="number" required min="0.01" step="0.01" x-model="allIn" :readonly="syncFinancials && propertyId" :class="{ 'bg-slate-100 dark:bg-slate-800': syncFinancials && propertyId }" class="form-input"><x-form-error name="all_in_amount" /></div>
    <div><label for="buyer_offer" class="text-sm font-medium">Their offer</label><input id="buyer_offer" name="buyer_offer" type="number" min="0" step="0.01" x-model="offer" class="form-input"><x-form-error name="buyer_offer" /><p class="mt-2 text-xs text-slate-500">Percent of ask: <strong x-text="offerPercent()"></strong></p></div>
    <div><label for="counter_percent" class="text-sm font-medium">Counter-offer percentage</label><select id="counter_percent" name="counter_percent" x-model="counterPercent" class="form-input"><option value="">Select percentage</option>@for($basisPoints = 10000; $basisPoints >= 5000; $basisPoints -= 250)@php($percentage = number_format($basisPoints / 100, 1, '.', ''))<option value="{{ $percentage }}">{{ $percentage }}%</option>@endfor</select><x-form-error name="counter_percent" /><p class="mt-2 text-xs text-slate-500">Counter offer: <strong x-text="counterAmount()"></strong></p></div>
    <div class="sm:col-span-2 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-950"><p class="font-semibold">Fixed planning split</p><p class="mt-1 text-slate-500">20% VVR / 40% Investor 1 / 40% Investor 2. The price ladder runs from 100% to 50% in 2.5% steps.</p></div>
    <div class="sm:col-span-2"><label for="notes" class="text-sm font-medium">Negotiation notes</label><textarea id="notes" name="notes" rows="5" maxlength="10000" class="form-input">{{ old('notes', $negotiation->notes ?? '') }}</textarea><x-form-error name="notes" /></div>
</div>

<div class="mt-6 flex justify-end gap-3"><a href="{{ isset($negotiation) ? route('armory.negotiations.show',$negotiation) : route('armory.negotiations.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">{{ isset($negotiation) ? 'Save plan' : 'Create plan' }}</button></div>
