<x-layouts.app title="Negotiations" heading="Armory Negotiations" subheading="Price ladders and buyer-offer positioning">
    @include('armory._navigation', ['active' => 'negotiations'])
    <section class="mb-6 rounded-2xl border border-amber-200 bg-gradient-to-br from-amber-50 to-white p-6 dark:border-amber-900/70 dark:from-amber-950/30 dark:to-slate-900"><h2 class="text-lg font-bold">Negotiation planning workspace</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">Model the buyer price ladder before and during a conversation. Negative projected splits identify offers below break-even and never create or record a payment.</p></section>
    <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><form method="GET" class="grid flex-1 gap-3 sm:grid-cols-[minmax(220px,1fr)_170px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search plan, property, or buyer" class="form-input mt-0"><select name="status" class="form-input mt-0"><option value="">All statuses</option>@foreach(\App\Enums\NegotiationPlanStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select><button class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Filter</button></form>@can('create',\App\Models\NegotiationPlan::class)<a href="{{ route('armory.negotiations.create') }}" class="rounded-lg bg-amber-400 px-4 py-2 text-center text-sm font-semibold text-slate-950 hover:bg-amber-300">+ New negotiation</a>@endcan</div>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/60"><tr><th class="px-5 py-3">Plan</th><th class="px-5 py-3">Property / Buyer</th><th class="px-5 py-3">Asking</th><th class="px-5 py-3">All-in</th><th class="px-5 py-3">Their Offer / Counter</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
        @forelse($negotiations as $negotiation)<tr class="hover:bg-slate-50 dark:hover:bg-slate-800/40"><td class="px-5 py-4"><a href="{{ route('armory.negotiations.show',$negotiation) }}" class="font-semibold hover:text-amber-600">{{ $negotiation->name }}</a><p class="mt-1 text-xs text-slate-500">Updated {{ $negotiation->updated_at->format('M j, Y') }}</p></td><td class="px-5 py-4"><p>{{ $negotiation->property?->address ?? 'Standalone' }}</p><p class="mt-1 text-xs text-slate-500">{{ $negotiation->buyerContact?->full_name ?? 'Buyer unassigned' }}</p></td><td class="px-5 py-4 font-medium">${{ number_format((float)$negotiation->asking_price,2) }}</td><td class="px-5 py-4">${{ number_format((float)$negotiation->all_in_amount,2) }}</td><td class="px-5 py-4"><p>Offer: {{ $negotiation->buyer_offer !== null ? '$'.number_format((float)$negotiation->buyer_offer,2) : '—' }}</p><p class="mt-1 text-xs text-slate-500">Counter: {{ $negotiation->counter_percent !== null ? '$'.number_format((float)$negotiation->asking_price*((float)$negotiation->counter_percent/100),2).' ('.number_format((float)$negotiation->counter_percent,1).'%)' : '—' }}</p></td><td class="px-5 py-4">{{ $negotiation->status->label() }}</td></tr>
        @empty<tr><td colspan="6" class="px-6 py-14 text-center text-slate-500">No negotiation plans match the current filters.</td></tr>@endforelse
    </tbody></table></div><div class="border-t border-slate-200 px-5 py-4 dark:border-slate-800">{{ $negotiations->links() }}</div></section>
</x-layouts.app>
