<x-layouts.app title="{{ $negotiation->name }}" heading="{{ $negotiation->name }}" subheading="Core Price Ladder">
    @php
        $topRow = $ladder['rows'][0];
        $money = function ($value): string {
            $amount = (float) $value;
            return $amount < 0 ? '-$'.number_format(abs($amount), 2) : '$'.number_format($amount, 2);
        };
    @endphp
    <div class="mx-auto max-w-7xl space-y-6">
        <div class="flex flex-wrap justify-between gap-3"><div class="flex flex-wrap items-center gap-2"><a href="{{ route('armory.index') }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium dark:border-slate-700">Script Library</a><a href="{{ route('armory.negotiations.index') }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium dark:border-slate-700">Negotiations</a>@if($negotiation->property)<span @class(['rounded-full px-3 py-1 text-xs font-semibold','bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' => $negotiation->sync_property_financials,'bg-slate-100 text-slate-500 dark:bg-slate-800' => ! $negotiation->sync_property_financials])>{{ $negotiation->sync_property_financials ? 'Property financials synced' : 'Custom financial scenario' }}</span>@endif</div><div class="flex gap-2">@can('update',$negotiation)<a href="{{ route('armory.negotiations.edit',$negotiation) }}" class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">Update offer</a>@endcan @can('delete',$negotiation)<form method="POST" action="{{ route('armory.negotiations.destroy',$negotiation) }}" onsubmit="return confirm('Archive this negotiation plan?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm font-medium text-rose-600 dark:border-rose-900">Archive</button></form>@endcan</div></div>

        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
            @foreach([['Asking price',$topRow['asking_price']],['All-in amount',$negotiation->all_in_amount],['Profit at ask',$topRow['profit']],['VVR at ask',$topRow['vvr_split']],['Each investor at ask',$topRow['investor_one_split']]] as [$label,$value])<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-3 text-xl font-bold">{{ $money($value) }}</p></article>@endforeach
        </section>

        @if($ladder['offer'])<section class="rounded-2xl border border-sky-200 bg-sky-50 p-6 dark:border-sky-900 dark:bg-sky-950/20"><div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><p class="text-xs font-bold uppercase tracking-wide text-sky-700 dark:text-sky-400">Buyer Offer Input</p><p class="mt-2 text-3xl font-bold">{{ $money($ladder['offer']['amount']) }}</p><p class="mt-1 text-sm text-slate-500">{{ $negotiation->buyerContact?->full_name ?? 'Unassigned buyer' }}</p></div><div class="grid flex-1 gap-4 sm:grid-cols-5 lg:max-w-4xl">@foreach([['Percent of Ask',$ladder['offer']['percent_of_ask'].'%'],['Profit',$money($ladder['offer']['profit'])],['VVR 20%',$money($ladder['offer']['vvr_split'])],['Investor 1 40%',$money($ladder['offer']['investor_one_split'])],['Investor 2 40%',$money($ladder['offer']['investor_two_split'])]] as [$label,$value])<div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-2 font-bold">{{ $value }}</p></div>@endforeach</div></div></section>@endif

        @if($ladder['counter_offer'])<section class="rounded-2xl border border-amber-300 bg-amber-50 p-6 dark:border-amber-800 dark:bg-amber-950/20"><div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><p class="text-xs font-bold uppercase tracking-wide text-amber-700 dark:text-amber-400">Counter Offer</p><p class="mt-2 text-3xl font-bold">{{ $money($ladder['counter_offer']['amount']) }}</p><p class="mt-1 text-sm text-slate-500">Calculated from your selected percentage</p></div><div class="grid flex-1 gap-4 sm:grid-cols-5 lg:max-w-4xl">@foreach([['Percent of Ask',$ladder['counter_offer']['percent_of_ask'].'%'],['Profit',$money($ladder['counter_offer']['profit'])],['VVR 20%',$money($ladder['counter_offer']['vvr_split'])],['Investor 1 40%',$money($ladder['counter_offer']['investor_one_split'])],['Investor 2 40%',$money($ladder['counter_offer']['investor_two_split'])]] as [$label,$value])<div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-2 font-bold">{{ $value }}</p></div>@endforeach</div></div></section>@endif

        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 px-6 py-5 dark:border-slate-800"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="font-semibold">Core Price Ladder</h2><p class="mt-1 text-sm text-slate-500">100% to 50% of asking price in 2.5% steps. Blue marks the closest buyer-offer row; amber marks your selected counter.</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500 dark:bg-slate-800">20% / 40% / 40%</span></div></div><div class="overflow-x-auto"><table class="w-full min-w-[980px] text-right text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/60"><tr><th class="px-5 py-3">Split VVR 20%</th><th class="px-5 py-3">Investor 1 40%</th><th class="px-5 py-3">Investor 2 40%</th><th class="px-5 py-3">Profit</th><th class="px-5 py-3">Asking Price</th><th class="px-5 py-3 text-left">Percent</th><th class="px-5 py-3">All In</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
            @foreach($ladder['rows'] as $row)<tr @class(['bg-amber-50 ring-1 ring-inset ring-amber-300 dark:bg-amber-950/20 dark:ring-amber-800' => $row['is_counter'] ?? false,'bg-sky-50 ring-1 ring-inset ring-sky-200 dark:bg-sky-950/20 dark:ring-sky-900' => ($row['is_closest'] ?? false) && !($row['is_counter'] ?? false),'bg-rose-50/50 dark:bg-rose-950/10' => (float)$row['profit'] < 0])><td class="px-5 py-3">{{ $money($row['vvr_split']) }}</td><td class="px-5 py-3">{{ $money($row['investor_one_split']) }}</td><td class="px-5 py-3">{{ $money($row['investor_two_split']) }}</td><td @class(['px-5 py-3 font-semibold','text-rose-600 dark:text-rose-400' => (float)$row['profit'] < 0,'text-emerald-700 dark:text-emerald-400' => (float)$row['profit'] >= 0])>{{ $money($row['profit']) }}</td><td class="px-5 py-3 font-medium">{{ $money($row['asking_price']) }}</td><td class="px-5 py-3 text-left font-semibold">{{ $row['percent'] }}%@if($row['is_counter'] ?? false)<span class="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] text-amber-700 dark:bg-amber-900 dark:text-amber-200">Counter</span>@endif @if(($row['is_closest'] ?? false) && !($row['is_counter'] ?? false))<span class="ml-2 rounded-full bg-sky-100 px-2 py-0.5 text-[10px] text-sky-700 dark:bg-sky-900 dark:text-sky-200">Closest</span>@endif</td><td class="px-5 py-3 text-slate-500">{{ $money($negotiation->all_in_amount) }}</td></tr>@endforeach
        </tbody></table></div></section>

        @if($negotiation->property || $negotiation->notes)<section class="grid gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2 dark:border-slate-800 dark:bg-slate-900">@if($negotiation->property)<div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Property</p><a href="{{ route('properties.show',$negotiation->property) }}" class="mt-2 block font-semibold text-amber-700 hover:underline dark:text-amber-400">{{ $negotiation->property->full_address }}</a></div>@endif @if($negotiation->notes)<div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Notes</p><p class="mt-2 whitespace-pre-line text-sm leading-6">{{ $negotiation->notes }}</p></div>@endif</section>@endif

        <p class="text-xs leading-5 text-slate-500">Negotiation splits are projections. Negative values flag pricing below the recorded all-in amount. They do not create payments or change Property Financials.</p>
    </div>
</x-layouts.app>
