<x-layouts.app title="Calendar" heading="Auction calendar" subheading="Tax deed and foreclosure auction deadlines">
    <div class="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-center">
        <form method="GET" class="grid gap-3 sm:grid-cols-[170px_180px_210px_auto]">
            <input type="month" name="month" value="{{ $month->format('Y-m') }}" class="form-input mt-0">
            <select name="county" class="form-input mt-0"><option value="">All counties</option>@foreach(\App\Enums\AuctionCounty::cases() as $county)<option value="{{ $county->value }}" @selected(request('county') === $county->value)>{{ $county->label() }}</option>@endforeach</select>
            <select name="event_type" class="form-input mt-0"><option value="">All event types</option>@foreach(\App\Enums\AuctionEventType::cases() as $type)<option value="{{ $type->value }}" @selected(request('event_type') === $type->value)>{{ $type->label() }}</option>@endforeach</select>
            <button class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Apply</button>
        </form>
        <div class="flex flex-wrap gap-2">
            @can('manageGoogleCalendarIntegration')<a href="{{ route('google-calendar.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-center text-sm font-medium dark:border-slate-700">Google Calendar</a>@endcan
            @can('create', \App\Models\CalendarEvent::class)<a href="{{ route('calendar.create') }}" class="rounded-lg bg-amber-400 px-4 py-2 text-center text-sm font-semibold text-slate-950 hover:bg-amber-300">+ Add Event</a>@endcan
        </div>
    </div>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div class="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><a href="{{ route('calendar.index', array_filter(['month' => $month->subMonth()->format('Y-m'), 'county' => request('county'), 'event_type' => request('event_type')])) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm dark:border-slate-700">← Previous</a><h2 class="text-lg font-bold">{{ $month->format('F Y') }}</h2><a href="{{ route('calendar.index', array_filter(['month' => $month->addMonth()->format('Y-m'), 'county' => request('county'), 'event_type' => request('event_type')])) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm dark:border-slate-700">Next →</a></div>
        <div class="grid grid-cols-7 border-b border-slate-200 bg-slate-50 text-center text-xs font-semibold uppercase tracking-wide text-slate-500 dark:border-slate-800 dark:bg-slate-800/60">@foreach(['Sun','Mon','Tue','Wed','Thu','Fri','Sat'] as $weekday)<div class="px-2 py-3">{{ $weekday }}</div>@endforeach</div>
        <div class="grid grid-cols-7">@foreach($days as $day)@php($dayEvents = $eventsByDate->get($day->format('Y-m-d'), collect()))<div @class(['min-h-32 border-b border-r border-slate-100 p-2 dark:border-slate-800', 'bg-slate-50/70 text-slate-400 dark:bg-slate-950/40' => $day->month !== $month->month])><p @class(['mb-2 text-xs font-semibold', 'inline-flex h-6 w-6 items-center justify-center rounded-full bg-amber-400 text-slate-950' => $day->isToday()])>{{ $day->day }}</p><div class="space-y-1.5">@foreach($dayEvents as $event)<a href="{{ route('calendar.show', $event) }}" @class(['block rounded-md border-l-4 px-2 py-1.5 text-[11px] leading-4', 'border-amber-500 bg-amber-50 text-amber-950 dark:bg-amber-950/50 dark:text-amber-200' => $event->event_type === \App\Enums\AuctionEventType::TaxDeedAuction, 'border-rose-500 bg-rose-50 text-rose-950 dark:bg-rose-950/50 dark:text-rose-200' => $event->event_type === \App\Enums\AuctionEventType::ForeclosureAuction, 'border-sky-500 bg-sky-50 text-sky-950 dark:bg-sky-950/50 dark:text-sky-200' => $event->event_type === \App\Enums\AuctionEventType::Meeting])><span class="block font-bold">{{ $event->starts_at->format('g:i A') }}</span><span class="block truncate">{{ $event->displayTitle() }}</span>@if($event->county)<span class="block truncate opacity-75">{{ $event->county->label() }}</span>@endif</a>@endforeach</div></div>@endforeach</div>
    </section>

    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 class="font-semibold">Upcoming events</h2><p class="mt-1 text-sm text-slate-500">Next twelve events matching the selected filters.</p></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($upcoming as $event)<a href="{{ route('calendar.show', $event) }}" class="grid gap-3 px-5 py-4 hover:bg-slate-50 sm:grid-cols-[160px_minmax(220px,1fr)_170px_170px] dark:hover:bg-slate-800/40"><div><p class="font-semibold">{{ $event->starts_at->format('M j, Y') }}</p><p class="text-xs text-slate-500">{{ $event->starts_at->format('g:i A T') }}</p></div><div><p class="font-medium">{{ $event->displayTitle() }}</p>@if($event->parcel_number)<p class="mt-1 text-xs text-slate-500">Parcel {{ $event->parcel_number }}</p>@elseif($event->property_address)<p class="mt-1 text-xs text-slate-500">{{ $event->property_address }}</p>@endif</div><p class="text-sm">{{ $event->event_type->label() }}</p><p class="text-sm">{{ $event->county ? $event->county->label().' County' : '—' }}</p></a>@empty<p class="px-5 py-12 text-center text-sm text-slate-500">No upcoming events match these filters.</p>@endforelse</div></section>
</x-layouts.app>
