@csrf
@isset($case) @method('PUT') @endisset
@php($value = fn(string $key, mixed $default = null) => old($key, isset($case) ? data_get($case, $key) : request($key, $default)))
<div class="space-y-8">
    <section><h2 class="font-semibold">Case assignment</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <div><label for="status" class="text-sm font-medium">Pipeline stage *</label><select id="status" name="status" required class="form-input">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(($value('status','research') instanceof \App\Enums\SurplusCaseStatus ? $value('status')->value : $value('status','research')) === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="status" /></div>
        <div><label for="claimant_contact_id" class="text-sm font-medium">Claimant contact</label><select id="claimant_contact_id" name="claimant_contact_id" class="form-input"><option value="">No claimant selected</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string)$value('claimant_contact_id')===(string)$contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' · '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="claimant_contact_id" /></div>
        <div><label for="assigned_user_id" class="text-sm font-medium">Assigned user</label><select id="assigned_user_id" name="assigned_user_id" class="form-input"><option value="">Unassigned</option>@foreach($assignees as $user)<option value="{{ $user->id }}" @selected((string)$value('assigned_user_id')===(string)$user->id)>{{ $user->name }}</option>@endforeach</select><x-form-error name="assigned_user_id" /></div>
        <div class="sm:col-span-2"><label for="property_id" class="text-sm font-medium">Related property</label><select id="property_id" name="property_id" class="form-input"><option value="">No property selected</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected((string)$value('property_id')===(string)$property->id)>{{ $property->address }} · {{ $property->city }}, {{ $property->state }}{{ $property->parcel_id ? ' · '.$property->parcel_id : '' }}</option>@endforeach</select><x-form-error name="property_id" /></div>
        <div><label for="source" class="text-sm font-medium">Lead source</label><input id="source" name="source" maxlength="120" value="{{ $value('source') }}" class="form-input"><x-form-error name="source" /></div>
    </div></section>
    <section><h2 class="font-semibold">Case identifiers</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach(['state'=>'State','county'=>'County','parcel_id'=>'Parcel ID','tax_deed_number'=>'Tax deed number','foreclosure_case_number'=>'Foreclosure case number','certificate_number'=>'Certificate number'] as $key=>$label)<div><label for="{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" maxlength="{{ $key==='state' ? 2 : 120 }}" value="{{ $value($key) }}" class="form-input"><x-form-error name="{{ $key }}" /></div>@endforeach</div></section>
    <section><h2 class="font-semibold">Milestones and deadlines</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach(['sale_date'=>'Sale date','claim_deadline'=>'Claim deadline','agreement_date'=>'Agreement date','submitted_at'=>'Submitted','approved_at'=>'Approved','paid_at'=>'Paid'] as $key=>$label)<div><label for="{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" type="date" value="{{ old($key, isset($case) ? $case->{$key}?->format('Y-m-d') : '') }}" class="form-input"><x-form-error name="{{ $key }}" /></div>@endforeach</div></section>
    @if(auth()->user()->canViewSurplusFinancials())
        <section x-data="{ surplus: Number(@js($value('surplus_amount', 0))) || 0, money(value) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value) || 0) } }">
            <h2 class="font-semibold">Claim economics</h2>
            <p class="mt-1 text-sm text-slate-500">Enter the surplus amount to see VVR's projected fee pay immediately. The server always calculates and saves the fee at 12%.</p>
            <div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">
                <div><label for="surplus_amount" class="text-sm font-medium">Surplus amount</label><input id="surplus_amount" name="surplus_amount" type="number" min="0" step="0.01" value="{{ $value('surplus_amount') }}" x-model.number="surplus" class="form-input"><x-form-error name="surplus_amount" /></div>
                <div><span class="text-sm font-medium">VVR fee percentage</span><div class="form-input bg-slate-50 font-semibold dark:bg-slate-800">12.00% <span class="ml-1 text-xs font-normal text-slate-500">Fixed</span></div><p class="mt-1 text-xs text-slate-500">The VVR surplus fee is always 12%.</p></div>
                <div><label class="text-sm font-medium">VVR projected fee pay</label><div class="form-input bg-amber-50 font-semibold text-amber-900 dark:bg-amber-950/40 dark:text-amber-200" x-text="money(surplus * 0.12)">{{ '$'.number_format((float)$value('surplus_amount',0) * 0.12, 2) }}</div><p class="mt-1 text-xs text-slate-500">Surplus amount × 12%</p></div>
                <div><label for="recovered_amount" class="text-sm font-medium">Recovered amount</label><input id="recovered_amount" name="recovered_amount" type="number" min="0" step="0.01" value="{{ $value('recovered_amount') }}" class="form-input"><x-form-error name="recovered_amount" /></div>
                <div><label for="actual_fee" class="text-sm font-medium">Actual fee received</label><input id="actual_fee" name="actual_fee" type="number" min="0" step="0.01" value="{{ $value('actual_fee') }}" class="form-input"><x-form-error name="actual_fee" /></div>
            </div>
        </section>
    @endif
    @if(auth()->user()->canViewPropertySourceDocuments())<section><h2 class="font-semibold">Private documents</h2><label for="document_drive_url" class="mt-4 block text-sm font-medium">Google Drive folder</label><input id="document_drive_url" name="document_drive_url" type="url" value="{{ $value('document_drive_url') }}" placeholder="https://drive.google.com/drive/folders/..." class="form-input"><x-form-error name="document_drive_url" /></section>@endif
    <section><h2 class="font-semibold">Case notes</h2><textarea name="notes" rows="8" maxlength="50000" class="form-input">{{ $value('notes') }}</textarea><x-form-error name="notes" /></section>
</div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ isset($case) ? route('surplus.show',$case) : route('surplus.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950">{{ isset($case) ? 'Save case' : 'Create case' }}</button></div>
