<x-layouts.app title="{{ $case->case_number }}" heading="{{ $case->case_number }}" subheading="Surplus recovery case">
    <div class="mx-auto max-w-6xl">
        <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div class="flex flex-wrap gap-2"><span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800 dark:bg-amber-950 dark:text-amber-300">{{ $case->status->label() }}</span>@if($case->claim_deadline?->isPast() && $case->status->isOpen())<span class="rounded-full bg-rose-100 px-3 py-1 text-xs font-semibold text-rose-700 dark:bg-rose-950 dark:text-rose-300">Deadline overdue</span>@endif</div><div class="flex gap-2">@can('create', \App\Models\OutboundEmail::class)<a href="{{ route('email.create',['related_type'=>'surplus','related_id'=>$case->id]) }}" class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950">Send email</a>@endcan @can('update',$case)<a href="{{ route('surplus.edit',$case) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Edit case</a>@endcan @can('delete',$case)<form method="POST" action="{{ route('surplus.destroy',$case) }}" onsubmit="return confirm('Archive this surplus case?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm font-medium text-rose-700 dark:border-rose-900 dark:text-rose-400">Archive</button></form>@endcan</div></div>
        <div class="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><div class="space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Case overview</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2">
                <div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Claimant</dt><dd class="mt-1 text-sm">@if($case->claimantContact)<a href="{{ route('contacts.show',$case->claimantContact) }}" class="font-semibold text-amber-700 hover:underline dark:text-amber-400">{{ $case->claimantContact->full_name }}</a><span class="block text-xs text-slate-500">{{ $case->claimantContact->company ?: $case->claimantContact->email }}</span>@else — @endif</dd></div>
                <div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Property</dt><dd class="mt-1 text-sm">@if($case->property)<a href="{{ route('properties.show',$case->property) }}" class="font-semibold text-amber-700 hover:underline dark:text-amber-400">{{ $case->property->address }}</a><span class="block text-xs text-slate-500">{{ $case->property->city }}, {{ $case->property->state }} {{ $case->property->postal_code }}</span>@else — @endif</dd></div>
                @foreach([['Assigned to',$case->assignedUser?->name],['Lead source',$case->source],['State / county',trim(($case->state ?: '').($case->county ? ' · '.$case->county.' County' : ''))],['Parcel ID',$case->parcel_id],['Tax deed number',$case->tax_deed_number],['Foreclosure case',$case->foreclosure_case_number],['Certificate number',$case->certificate_number]] as [$label,$value])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm">{{ $value ?: '—' }}</dd></div>@endforeach
            </dl></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div><h2 class="font-semibold">Associated people</h2><p class="mt-1 text-sm text-slate-500">Link the surplus owner, relatives, heirs, representatives, and other skip-trace contacts to this case.</p></div>
                <div class="mt-5 divide-y divide-slate-100 dark:divide-slate-800">
                    @forelse($case->contacts as $contact)
                        <div class="flex flex-col justify-between gap-3 py-4 sm:flex-row sm:items-start">
                            <div><a href="{{ route('contacts.show',$contact) }}" class="font-semibold text-amber-700 hover:underline dark:text-amber-400">{{ $contact->full_name }}</a><p class="mt-1 text-xs text-slate-500">{{ \App\Enums\SurplusContactRole::tryFrom($contact->pivot->role)?->label() ?? str($contact->pivot->role)->headline() }}@if($contact->company) · {{ $contact->company }}@endif @if($contact->email) · {{ $contact->email }}@endif</p>@if($contact->pivot->relationship_notes)<p class="mt-2 text-sm text-slate-600 dark:text-slate-300">{{ $contact->pivot->relationship_notes }}</p>@endif</div>
                            @can('update',$case)@if($contact->id !== $case->claimant_contact_id)<form method="POST" action="{{ route('surplus.contacts.destroy',[$case,$contact->pivot->id]) }}" onsubmit="return confirm('Remove this person from the Surplus case?')">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600 hover:underline">Remove</button></form>@else<span class="self-start rounded-full bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-800 dark:bg-amber-950 dark:text-amber-300">Primary claimant</span>@endif @endcan
                        </div>
                    @empty<p class="py-4 text-sm text-slate-500">No people are linked to this case.</p>@endforelse
                </div>
                @can('update',$case)
                    <form method="POST" action="{{ route('surplus.contacts.store',$case) }}" class="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-950 sm:grid-cols-2">@csrf
                        <div class="sm:col-span-2"><label for="contact_id" class="text-sm font-medium">Contact</label><select id="contact_id" name="contact_id" required class="form-input"><option value="">Select an existing contact</option>@foreach($availableContacts as $contact)<option value="{{ $contact->id }}">{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="contact_id" /></div>
                        <div><label for="role" class="text-sm font-medium">Relationship</label><select id="role" name="role" required class="form-input">@foreach($contactRoles as $role)<option value="{{ $role->value }}" @selected($role === \App\Enums\SurplusContactRole::Relative)>{{ $role->label() }}</option>@endforeach</select><x-form-error name="role" /></div>
                        <div><label for="relationship_notes" class="text-sm font-medium">Relationship notes</label><input id="relationship_notes" name="relationship_notes" maxlength="500" placeholder="Owner's daughter, best mailing address…" class="form-input"><x-form-error name="relationship_notes" /></div>
                        <div class="sm:col-span-2 flex flex-wrap items-center gap-3"><button class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">Link contact</button><a href="{{ route('contacts.create') }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Create a new contact first</a></div>
                    </form>
                @endcan
            </section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Milestones</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach([['Sale date',$case->sale_date],['Claim deadline',$case->claim_deadline],['Agreement date',$case->agreement_date],['Submitted',$case->submitted_at],['Approved',$case->approved_at],['Paid',$case->paid_at]] as [$label,$date])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-medium">{{ $date?->format('M j, Y') ?: '—' }}</dd></div>@endforeach</dl></section>
            @can('viewFinancials',$case)<section class="rounded-2xl border border-amber-200 bg-amber-50/60 p-6 shadow-sm dark:border-amber-900 dark:bg-amber-950/20"><h2 class="font-semibold">Claim economics</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach([['Surplus amount',$case->surplus_amount,true],['Agreed fee',\App\Services\SurplusCaseService::FIXED_FEE_PERCENTAGE,false],['Expected fee',$case->expected_fee,true],['Recovered amount',$case->recovered_amount,true],['Actual fee',$case->actual_fee,true]] as [$label,$amount,$currency])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-lg font-semibold">{{ $amount !== null ? ($currency ? '$'.number_format((float)$amount,2) : number_format((float)$amount,2).'%') : '-' }}</dd></div>@endforeach</dl></section>@endcan
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Case notes</h2><p class="mt-4 whitespace-pre-line text-sm leading-6 text-slate-600 dark:text-slate-300">{{ $case->notes ?: 'No notes have been added.' }}</p></section>
        </div><div class="space-y-6">
            @can('viewDocuments',$case)<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Private documents</h2>@if($case->document_drive_url)<a href="{{ $case->document_drive_url }}" target="_blank" rel="noopener noreferrer" class="mt-4 inline-flex text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Open Drive folder ↗</a>@endif @forelse($case->intakeFiles as $file)<div class="mt-4 border-t border-slate-100 pt-4 dark:border-slate-800"><p class="break-words text-sm font-medium">{{ $file->original_name }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($file->size_bytes/1024,1) }} KB · Approved {{ $file->attached_at?->format('M j, Y') }}</p><a href="{{ route('surplus.intake-files.download',[$case,$file]) }}" class="mt-2 inline-flex text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Download private source</a></div>@empty @if(!$case->document_drive_url)<p class="mt-3 text-sm text-slate-500">No private documents are linked.</p>@endif @endforelse</section>@endcan
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold">Tasks</h2><p class="mt-1 text-xs text-slate-500">Work assigned to this recovery case.</p></div>@can('create',\App\Models\Task::class)<a href="{{ route('tasks.create',['subject'=>'surplus:'.$case->id]) }}" class="text-xs font-semibold text-amber-700 hover:underline dark:text-amber-400">Add task</a>@endcan</div><div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($case->tasks as $task)<a href="{{ route('tasks.show',$task) }}" class="block py-3 hover:text-amber-700"><p class="text-sm font-medium">{{ $task->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $task->status->label() }} · {{ $task->assignedUser?->name ?? 'Unassigned' }} · {{ $task->due_at?->format('M j, Y') ?? 'No due date' }}</p></a>@empty<p class="py-4 text-sm text-slate-500">No tasks are associated with this case.</p>@endforelse</div></section>
        </div></div><x-email-history :record="$case" /><a href="{{ route('surplus.index') }}" class="mt-6 inline-flex text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">← Back to surplus</a>
    </div>
</x-layouts.app>
