@php
    $scenario = $scenario ?? null;
    $value = fn (string $field, mixed $default = null): mixed => old($field, $scenario?->{$field} ?? $default);
@endphp
<div class="grid gap-5 sm:grid-cols-2">
    <div class="sm:col-span-2"><label for="name" class="text-sm font-medium">Scenario name</label><input id="name" name="name" required maxlength="150" value="{{ $value('name') }}" class="form-input"><x-form-error name="name" /></div>
    <div><label for="status" class="text-sm font-medium">Status</label><select id="status" name="status" required class="form-input">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($value('status', 'draft') instanceof \App\Enums\ProjectionScenarioStatus ? $value('status')->value === $status->value : $value('status', 'draft') === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="status" /></div>
    <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm dark:border-amber-900 dark:bg-amber-950/30"><p class="font-semibold">Fixed payment split</p><p class="mt-1 text-slate-600 dark:text-slate-300">20% VVR / 40% Assigned Contact 1 / 40% Assigned Contact 2</p></div>
    <div><label for="start_year" class="text-sm font-medium">Start year</label><input id="start_year" name="start_year" type="number" min="2020" max="2100" required value="{{ $value('start_year', 2026) }}" @readonly($scenario) class="form-input {{ $scenario ? 'bg-slate-100 dark:bg-slate-800' : '' }}"><x-form-error name="start_year" /></div>
    <div><label for="end_year" class="text-sm font-medium">End year</label><input id="end_year" name="end_year" type="number" min="2020" max="2100" required value="{{ $value('end_year', 2030) }}" @readonly($scenario) class="form-input {{ $scenario ? 'bg-slate-100 dark:bg-slate-800' : '' }}"><p class="mt-1 text-xs text-slate-500">Maximum ten years. The horizon is locked after creation.</p><x-form-error name="end_year" /></div>
    <div><label for="contact_one_id" class="text-sm font-medium">Assigned Contact 1 · 40%</label><select id="contact_one_id" name="contact_one_id" class="form-input"><option value="">Unassigned</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string) $value('contact_one_id') === (string) $contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="contact_one_id" /></div>
    <div><label for="contact_two_id" class="text-sm font-medium">Assigned Contact 2 · 40%</label><select id="contact_two_id" name="contact_two_id" class="form-input"><option value="">Unassigned</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string) $value('contact_two_id') === (string) $contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="contact_two_id" /></div>
    <div class="sm:col-span-2"><label for="notes" class="text-sm font-medium">Planning notes</label><textarea id="notes" name="notes" rows="4" maxlength="10000" class="form-input">{{ $value('notes') }}</textarea><x-form-error name="notes" /></div>
</div>
