@php($money = fn (int $cents): string => ($cents < 0 ? '−$' : '$').number_format(abs($cents) / 100, 2))
<x-layouts.app title="Projections" heading="Projections" subheading="Monthly operating goals and five-year payment forecasts">
    <div class="space-y-6">
        <section class="flex flex-col justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-end dark:border-slate-800 dark:bg-slate-900"><div class="flex-1"><label for="scenario" class="text-sm font-medium">Projection scenario</label>@if($scenarios->isNotEmpty())<form method="GET" action="{{ route('projections.index') }}" class="mt-2 flex flex-col gap-3 sm:flex-row"><select id="scenario" name="scenario" class="form-input" onchange="this.form.submit()">@foreach($scenarios as $option)<option value="{{ $option->token }}" @selected($scenario?->is($option))>{{ $option->name }}{{ $option->is_default ? ' · Default' : '' }} · {{ $option->status->label() }}</option>@endforeach</select><noscript><button class="rounded-lg border px-4 py-2 text-sm font-semibold">View</button></noscript></form>@else<p class="mt-2 text-sm text-slate-500">No projection scenarios have been created.</p>@endif</div>@can('create', \App\Models\ProjectionScenario::class)<a href="{{ route('projections.create') }}" class="rounded-lg bg-amber-400 px-5 py-2.5 text-center text-sm font-semibold text-slate-950">+ New scenario</a>@endcan</section>

        @if($scenario && $summary)
            <section class="rounded-2xl border border-amber-200 bg-amber-50/60 p-5 dark:border-amber-900 dark:bg-amber-950/20"><div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div class="flex flex-wrap items-center gap-2"><h2 class="text-lg font-bold">{{ $scenario->name }}</h2>@if($scenario->is_default)<span class="rounded-full bg-amber-200 px-2.5 py-1 text-xs font-semibold text-amber-900 dark:bg-amber-900 dark:text-amber-100">Default</span>@endif<span class="rounded-full bg-white px-2.5 py-1 text-xs font-semibold dark:bg-slate-900">{{ $scenario->status->label() }}</span></div><p class="mt-2 text-sm text-slate-600 dark:text-slate-300">{{ $scenario->start_year }}–{{ $scenario->end_year }} · Fixed split: 20% VVR / 40% {{ $scenario->contactOne?->full_name ?: 'Contact 1' }} / 40% {{ $scenario->contactTwo?->full_name ?: 'Contact 2' }}</p>@if($scenario->notes)<p class="mt-3 max-w-3xl whitespace-pre-line text-sm text-slate-600 dark:text-slate-300">{{ $scenario->notes }}</p>@endif</div><div class="flex flex-wrap gap-2">@can('update',$scenario)<a href="{{ route('projections.edit',$scenario) }}" class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white dark:bg-amber-400 dark:text-slate-950">Edit assumptions</a>@if(! $scenario->is_default)<form method="POST" action="{{ route('projections.default',$scenario) }}">@csrf @method('PATCH')<button class="rounded-lg border border-amber-400 px-4 py-2 text-sm font-semibold">Make default</button></form>@endif@endcan</div></div></section>
            <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
                @foreach([['Projected units',$summary['grand']['units'],false],['Projected profit pool',$summary['grand']['total'],true],['20% VVR',$summary['grand']['vvr'],true],['40% '.($scenario->contactOne?->first_name ?: 'Contact 1'),$summary['grand']['contact_one'],true],['40% '.($scenario->contactTwo?->first_name ?: 'Contact 2'),$summary['grand']['contact_two'],true]] as [$label,$value,$currency])<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold">{{ $currency ? $money($value) : number_format($value) }}</p></article>@endforeach
            </section>
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 px-6 py-5 dark:border-slate-800"><h2 class="font-semibold">Annual projection summary</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[800px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/60"><tr><th class="px-5 py-3">Year</th><th class="px-5 py-3 text-right">Units</th><th class="px-5 py-3 text-right">Profit pool</th><th class="px-5 py-3 text-right">20% VVR</th><th class="px-5 py-3 text-right">40% Contact 1</th><th class="px-5 py-3 text-right">40% Contact 2</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@foreach($summary['years'] as $year)<tr><th class="px-5 py-4 font-semibold">{{ $year['year'] }}</th><td class="px-5 py-4 text-right">{{ number_format($year['units']) }}</td><td class="px-5 py-4 text-right font-semibold">{{ $money($year['total']) }}</td><td class="px-5 py-4 text-right">{{ $money($year['vvr']) }}</td><td class="px-5 py-4 text-right">{{ $money($year['contact_one']) }}</td><td class="px-5 py-4 text-right">{{ $money($year['contact_two']) }}</td></tr>@endforeach</tbody><tfoot class="bg-slate-50 font-bold dark:bg-slate-800/60"><tr><th class="px-5 py-4">Total</th><td class="px-5 py-4 text-right">{{ number_format($summary['grand']['units']) }}</td><td class="px-5 py-4 text-right">{{ $money($summary['grand']['total']) }}</td><td class="px-5 py-4 text-right">{{ $money($summary['grand']['vvr']) }}</td><td class="px-5 py-4 text-right">{{ $money($summary['grand']['contact_one']) }}</td><td class="px-5 py-4 text-right">{{ $money($summary['grand']['contact_two']) }}</td></tr></tfoot></table></div></section>
            <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">@foreach($categories as $category)@php($categoryTotal = $summary['categories'][$category->value])<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">{{ $category->label() }}</p><p class="mt-2 text-xl font-bold">{{ $money($categoryTotal['total']) }}</p><p class="mt-2 text-sm text-slate-500">{{ number_format($categoryTotal['units']) }} {{ strtolower($category->unitLabel()) }} · Average {{ $money($categoryTotal['average_net_profit']) }}</p></article>@endforeach</section>
            <section class="space-y-4"><h2 class="text-lg font-semibold">Monthly detail</h2>@foreach($summary['years'] as $year)<details class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900" @if($loop->first) open @endif><summary class="cursor-pointer px-6 py-4 font-semibold">{{ $year['year'] }} · {{ $money($year['total']) }} projected</summary><div class="overflow-x-auto border-t border-slate-200 dark:border-slate-800"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/60"><tr><th class="px-4 py-3">Month</th>@foreach($categories as $category)<th class="px-4 py-3 text-right">{{ $category->label() }}</th>@endforeach<th class="px-4 py-3 text-right">Monthly total</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@foreach($year['months'] as $month)<tr><th class="px-4 py-3 font-medium">{{ $monthNames[$month['month']] }}</th>@foreach($categories as $category)@php($cell = $month['categories'][$category->value] ?? null)<td class="px-4 py-3 text-right">{{ $cell ? number_format($cell['units']).' · '.$money($cell['total']) : '0 · $0.00' }}</td>@endforeach<td class="px-4 py-3 text-right font-semibold">{{ $money($month['total']) }}</td></tr>@endforeach</tbody><tfoot class="border-t-2 border-slate-300 bg-slate-50 font-bold dark:border-slate-700 dark:bg-slate-800/60"><tr><th class="px-4 py-4">{{ $year['year'] }} total</th>@foreach($categories as $category)@php($categoryYear = $year['categories'][$category->value])<td class="px-4 py-4 text-right">{{ number_format($categoryYear['units']) }} · {{ $money($categoryYear['total']) }}</td>@endforeach<td class="px-4 py-4 text-right text-base text-amber-700 dark:text-amber-300">{{ $money($year['total']) }}</td></tr></tfoot></table></div></details>@endforeach</section>
        @else
            <section class="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center dark:border-slate-700 dark:bg-slate-900"><h2 class="text-lg font-semibold">Build the first projection scenario</h2><p class="mx-auto mt-2 max-w-xl text-sm text-slate-500">Set a planning horizon, average net-profit assumptions, and monthly operating goals. VVR calculates the complete 20/40/40 payment forecast automatically.</p>@can('create', \App\Models\ProjectionScenario::class)<a href="{{ route('projections.create') }}" class="mt-5 inline-flex rounded-lg bg-amber-400 px-5 py-2.5 text-sm font-semibold text-slate-950">Create scenario</a>@endcan</section>
        @endif
    </div>
</x-layouts.app>
