<x-layouts.app title="VVR Sales Copilot" heading="VVR Sales Copilot" subheading="AI-powered coaching grounded in approved VVR playbooks">
    @include('sales-copilot._navigation')
    <div class="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,.6fr)]">
        <section x-data="{ statement: '' }" class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <div class="flex items-center justify-between gap-4"><div><h2 class="text-xl font-bold">Quick Coach</h2><p class="mt-1 text-sm text-slate-500">Enter the prospect’s exact words. Copilot gives one governed response, not a generic script dump.</p></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">Ready</span></div>
            <div class="mt-5 flex flex-wrap gap-2">@foreach(['This sounds like a scam','I can do it myself','Send me information','I need to talk to my wife','It sounds too good to be true','I am not interested','What makes you different?','I will get back to you','Call me later'] as $chip)<button type="button" @click="statement = @js($chip)" class="rounded-full border border-slate-300 px-3 py-1.5 text-xs hover:border-amber-400 dark:border-slate-700">{{ $chip }}</button>@endforeach</div>
            <form method="POST" action="{{ route('sales-copilot.sessions.store') }}" class="mt-5 space-y-4">@csrf
                <label class="block text-sm font-semibold">What did the prospect say?<textarea x-model="statement" name="prospect_statement" rows="5" required maxlength="4000" class="form-input mt-2" placeholder="Paste or type their exact response or objection...">{{ old('prospect_statement') }}</textarea></label>
                @error('prospect_statement')<p class="text-sm text-red-600">{{ $message }}</p>@enderror
                <div class="grid gap-4 sm:grid-cols-3"><label class="text-sm font-semibold">Prospect name<input name="prospect_name" value="{{ old('prospect_name') }}" class="form-input mt-2"></label><label class="text-sm font-semibold">Call type<select name="call_type" class="form-input mt-2"><option value="inbound">Inbound</option><option value="outbound">Outbound</option><option value="follow_up">Follow-up</option><option value="other">Other</option></select></label><label class="text-sm font-semibold">Current stage<select name="current_stage" class="form-input mt-2">@foreach(['connection','situation','problem_awareness','solution_awareness','consequence','qualifying','transition','presentation','commitment','objection_resolution'] as $stage)<option value="{{ $stage }}">{{ str($stage)->replace('_',' ')->title() }}</option>@endforeach</select></label></div>
                <details class="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><summary class="cursor-pointer text-sm font-semibold">Optional CRM context</summary><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="text-sm">County<input name="county" class="form-input mt-1"></label><label class="text-sm">Parcel ID<input name="parcel_id" class="form-input mt-1"></label><label class="text-sm">Estimated surplus<input name="estimated_surplus" type="number" min="0" step="0.01" class="form-input mt-1"></label><label class="text-sm">Relationship<input name="prospect_relationship" class="form-input mt-1" placeholder="Claimant, relative, owner..."></label><label class="text-sm sm:col-span-2">Previous conversation summary<textarea name="previous_conversation_summary" class="form-input mt-1" rows="2"></textarea></label></div></details>
                <button class="w-full rounded-xl bg-amber-400 px-5 py-3 font-bold text-slate-950 hover:bg-amber-300">Start Live Coaching</button>
            </form>
        </section>
        <div class="space-y-6"><section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-bold">Recent sessions</h2><div class="mt-4 space-y-3">@forelse($sessions as $session)<a href="{{ route('sales-copilot.sessions.show',$session) }}" class="block rounded-xl border border-slate-200 p-3 hover:border-amber-400 dark:border-slate-700"><div class="flex justify-between gap-3"><span class="font-semibold">{{ $session->prospect_name ?: 'Unnamed prospect' }}</span><span class="text-xs uppercase text-slate-500">{{ $session->status }}</span></div><p class="mt-1 text-xs text-slate-500">{{ str($session->current_stage)->replace('_',' ')->title() }} · {{ optional($session->last_coached_at)->diffForHumans() ?: 'Not coached' }}</p></a>@empty<p class="text-sm text-slate-500">No coaching sessions yet.</p>@endforelse</div></section><section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-bold">Governed knowledge</h2><p class="mt-2 text-sm text-slate-500">{{ $playbooks->count() }} priority VVR playbooks are available. Owner-authored, approved language ranks above generated wording.</p><a href="{{ route('sales-copilot.playbooks.index') }}" class="mt-4 inline-block text-sm font-semibold text-amber-600">Review playbooks →</a></section></div>
    </div>
</x-layouts.app>
