<x-layouts.app title="Armory" heading="Armory" subheading="VVR scripts, talk tracks, and playbooks">
    @include('armory._navigation', ['active' => 'scripts'])
    <div class="mb-6 rounded-2xl border border-amber-200 bg-gradient-to-br from-amber-50 to-white p-6 dark:border-amber-900/70 dark:from-amber-950/30 dark:to-slate-900"><div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><h2 class="text-lg font-bold">Interactive script operations</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">Build guided playbooks with branching responses, then run resumable sessions tied to a contact and property. VVR records the path, notes, and outcome.</p></div><span class="self-start rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">Interactive mode active</span></div></div>

    <div class="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-center">
        <form method="GET" class="grid flex-1 gap-3 sm:grid-cols-[minmax(220px,1fr)_190px_150px_auto]">@if(request('sort'))<input type="hidden" name="sort" value="{{ request('sort') }}"><input type="hidden" name="direction" value="{{ request('direction', 'asc') }}">@endif<input name="search" value="{{ request('search') }}" placeholder="Search title, description, or script text" class="form-input mt-0"><select name="category" class="form-input mt-0"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->value }}" @selected(request('category') === $category->value)>{{ $category->label() }}</option>@endforeach</select><select name="status" class="form-input mt-0"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select><button class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Filter</button></form>
        @can('create', \App\Models\ArmoryScript::class)<a href="{{ route('armory.create') }}" class="rounded-lg bg-amber-400 px-4 py-2 text-center text-sm font-semibold text-slate-950 hover:bg-amber-300">+ Add script</a>@endcan
    </div>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/60"><tr><x-sortable-header route="armory.index" column="script" label="Script" /><x-sortable-header route="armory.index" column="category" label="Category" /><x-sortable-header route="armory.index" column="version" label="Version" /><x-sortable-header route="armory.index" column="status" label="Status" /><x-sortable-header route="armory.index" column="source" label="Source" /><x-sortable-header route="armory.index" column="updated" label="Updated" /></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
        @forelse($scripts as $script)<tr class="hover:bg-slate-50 dark:hover:bg-slate-800/40"><td class="px-5 py-4"><a href="{{ route('armory.show',$script) }}" class="font-semibold hover:text-amber-600">{{ $script->title }}</a><p class="mt-1 max-w-md truncate text-xs text-slate-500">{{ $script->description ?: 'No description' }}</p></td><td class="px-5 py-4">{{ $script->category->label() }}</td><td class="px-5 py-4">{{ $script->version_label }}</td><td class="px-5 py-4"><span @class(['rounded-full px-2 py-1 text-xs font-semibold','bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' => $script->status === \App\Enums\ArmoryScriptStatus::Active,'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300' => $script->status === \App\Enums\ArmoryScriptStatus::Draft,'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300' => $script->status === \App\Enums\ArmoryScriptStatus::Retired])>{{ $script->status->label() }}</span></td><td class="px-5 py-4 text-xs text-slate-500">{{ $script->hasFile() ? $script->original_name : 'Text only' }}</td><td class="px-5 py-4 text-xs text-slate-500">{{ $script->updated_at->format('M j, Y') }}<span class="mt-1 block">{{ $script->uploader?->name ?? $script->creator?->name ?? 'VVR' }}</span></td></tr>
        @empty<tr><td colspan="6" class="px-6 py-14 text-center text-slate-500">No scripts match the current filters.</td></tr>@endforelse
    </tbody></table></div><div class="border-t border-slate-200 px-5 py-4 dark:border-slate-800">{{ $scripts->links() }}</div></section>
</x-layouts.app>
