<x-layouts.app title="{{ $script->title }}" heading="{{ $script->title }}" subheading="{{ $script->category->label() }} · Version {{ $script->version_label }}">
    <div class="mx-auto max-w-5xl space-y-6">
        <div class="flex flex-wrap justify-end gap-3">@if($script->steps_count > 0)<a href="{{ route('armory.sessions.create',$script) }}" class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">Start guided session</a>@endif @if($script->hasFile())<a href="{{ route('armory.download',$script) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Download source</a>@endif @can('update',$script)<a href="{{ route('armory.playbook.show',$script) }}" class="rounded-lg border border-amber-400 px-4 py-2 text-sm font-semibold text-amber-700 dark:text-amber-400">Build playbook</a><a href="{{ route('armory.edit',$script) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Edit</a>@endcan @can('delete',$script)<form method="POST" action="{{ route('armory.destroy',$script) }}" onsubmit="return confirm('Archive this script? The private source file will be retained.')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm font-medium text-rose-600 dark:border-rose-900">Archive</button></form>@endcan</div>

        <section class="grid gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2 lg:grid-cols-4 dark:border-slate-800 dark:bg-slate-900">@foreach([['Category',$script->category->label()],['Status',$script->status->label()],['Version',$script->version_label],['Added by',$script->uploader?->name ?? $script->creator?->name ?? 'VVR']] as [$label,$value])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-medium">{{ $value }}</dd></div>@endforeach @if($script->description)<div class="sm:col-span-2 lg:col-span-4"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Description</dt><dd class="mt-2 whitespace-pre-line text-sm leading-6">{{ $script->description }}</dd></div>@endif</section>

        @if($script->content_text)<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Script</h2><pre class="mt-5 whitespace-pre-wrap font-sans text-sm leading-7 text-slate-700 dark:text-slate-200">{{ $script->content_text }}</pre></section>@endif

        @if($script->hasFile())<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Private source file</h2><div class="mt-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p class="text-sm font-medium">{{ $script->original_name }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($script->size_bytes / 1024, 1) }} KB · SHA-256 protected duplicate check</p></div><a href="{{ route('armory.download',$script) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Download</a></div></section>@endif

        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 class="font-semibold">Interactive playbook</h2><p class="mt-1 text-sm text-slate-500">{{ $script->steps_count }} guided {{ str('step')->plural($script->steps_count) }} · {{ $script->sessions_count }} recorded {{ str('session')->plural($script->sessions_count) }}</p></div><div class="flex gap-2">@can('update',$script)<a href="{{ route('armory.playbook.show',$script) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold dark:border-slate-700">Configure</a>@endcan @if($script->steps_count > 0)<a href="{{ route('armory.sessions.create',$script) }}" class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950">Run session</a>@endif</div></div></section>
    </div>
</x-layouts.app>
