@csrf
@isset($sop) @method('PUT') @endisset
@php($value = fn(string $key, mixed $default = null) => old($key, isset($sop) ? data_get($sop,$key) : request($key,$default)))
<div class="space-y-8">
    <section><h2 class="font-semibold">Procedure identity</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><div class="sm:col-span-2"><label for="title" class="text-sm font-medium">SOP title *</label><input id="title" name="title" required maxlength="180" value="{{ $value('title') }}" class="form-input"><x-form-error name="title" /></div><div><label for="version_label" class="text-sm font-medium">Version *</label><input id="version_label" name="version_label" required maxlength="40" value="{{ $value('version_label','1.0') }}" class="form-input"><x-form-error name="version_label" /></div><div><label for="department" class="text-sm font-medium">Department *</label><select id="department" name="department" required class="form-input">@foreach($departments as $department)<option value="{{ $department->value }}" @selected(($value('department','general_operations') instanceof \App\Enums\SopDepartment ? $value('department')->value : $value('department','general_operations'))===$department->value)>{{ $department->label() }}</option>@endforeach</select><x-form-error name="department" /></div><div><label for="status" class="text-sm font-medium">Status *</label><select id="status" name="status" required class="form-input">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(($value('status','draft') instanceof \App\Enums\SopStatus ? $value('status')->value : $value('status','draft'))===$status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="status" /></div><div><label for="owner_user_id" class="text-sm font-medium">Procedure owner</label><select id="owner_user_id" name="owner_user_id" class="form-input"><option value="">Unassigned</option>@foreach($owners as $owner)<option value="{{ $owner->id }}" @selected((string)$value('owner_user_id')===(string)$owner->id)>{{ $owner->name }}</option>@endforeach</select><x-form-error name="owner_user_id" /></div></div></section>
    <section><h2 class="font-semibold">Review schedule</h2><div class="mt-4 grid gap-5 sm:grid-cols-2"><div><label for="effective_date" class="text-sm font-medium">Effective date</label><input id="effective_date" name="effective_date" type="date" value="{{ old('effective_date',isset($sop)?$sop->effective_date?->format('Y-m-d'):'') }}" class="form-input"><x-form-error name="effective_date" /></div><div><label for="review_date" class="text-sm font-medium">Next review date</label><input id="review_date" name="review_date" type="date" value="{{ old('review_date',isset($sop)?$sop->review_date?->format('Y-m-d'):'') }}" class="form-input"><x-form-error name="review_date" /></div></div></section>
    <section><h2 class="font-semibold">Summary</h2><textarea name="summary" rows="4" maxlength="5000" class="form-input" placeholder="Purpose, scope, and intended users of this procedure.">{{ $value('summary') }}</textarea><x-form-error name="summary" /></section>
    <section><h2 class="font-semibold">Written procedure</h2><p class="mt-1 text-sm text-slate-500">Paste the authoritative steps here so the procedure is searchable and readable inside Command Center.</p><textarea name="content_text" rows="16" maxlength="500000" class="form-input font-mono text-sm" placeholder="Purpose&#10;Scope&#10;Responsibilities&#10;Procedure&#10;1. ...">{{ $value('content_text') }}</textarea><x-form-error name="content_text" /></section>
    <section><h2 class="font-semibold">Workflow continuation</h2><p class="mt-1 text-sm text-slate-500">Choose the SOP users should open after completing this procedure. Leave blank when this is the final SOP in the sequence.</p><div class="mt-4"><label for="next_sop_id" class="text-sm font-medium">Next SOP</label><select id="next_sop_id" name="next_sop_id" class="form-input"><option value="">No next SOP — end here</option>@foreach($nextSops as $nextSop)<option value="{{ $nextSop->id }}" @selected((string)$value('next_sop_id')===(string)$nextSop->id)>{{ $nextSop->department->label() }} · {{ $nextSop->title }} · {{ $nextSop->status->label() }}</option>@endforeach</select><x-form-error name="next_sop_id" /></div></section>
    <section><h2 class="font-semibold">Files and external source</h2><div class="mt-4 grid gap-5 sm:grid-cols-2"><div><label for="sop_file" class="text-sm font-medium">Private attachment</label><input id="sop_file" name="sop_file" type="file" accept=".pdf,.doc,.docx,.txt,.md,.rtf" class="form-input"><p class="mt-1 text-xs text-slate-500">PDF, DOC, DOCX, TXT, MD, or RTF · Maximum 15 MB · Stored privately</p>@if(isset($sop) && $sop->hasFile())<label class="mt-3 flex items-center gap-2 text-xs"><input type="checkbox" name="remove_file" value="1" class="rounded border-slate-300"> Remove {{ $sop->original_name }} without replacing it</label>@endif<x-form-error name="sop_file" /><x-form-error name="remove_file" /></div><div><label for="drive_url" class="text-sm font-medium">Google Drive link</label><input id="drive_url" name="drive_url" type="url" value="{{ $value('drive_url') }}" placeholder="https://drive.google.com/..." class="form-input"><x-form-error name="drive_url" /></div></div></section>
</div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ isset($sop)?route('sops.show',$sop):route('sops.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950">{{ isset($sop)?'Save SOP':'Create SOP' }}</button></div>
