<x-layouts.app title="{{ $sop->title }}" heading="{{ $sop->title }}" subheading="{{ $sop->department->label() }} · Version {{ $sop->version_label }}">
    <div class="mx-auto max-w-6xl">
        <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div class="flex flex-wrap gap-2"><span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800 dark:bg-amber-950 dark:text-amber-300">{{ $sop->status->label() }}</span>@if($sop->review_date?->isPast() && $sop->status !== \App\Enums\SopStatus::Retired)<span class="rounded-full bg-rose-100 px-3 py-1 text-xs font-semibold text-rose-700 dark:bg-rose-950 dark:text-rose-300">Review overdue</span>@endif</div><div class="flex flex-wrap gap-2">@can('update',$sop)<a href="{{ route('sops.edit',$sop) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Edit SOP</a>@endcan @can('delete',$sop)<form method="POST" action="{{ route('sops.destroy',$sop) }}" onsubmit="return confirm('Archive this SOP?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm font-medium text-rose-700 dark:border-rose-900 dark:text-rose-400">Archive</button></form>@endcan</div></div>
        <div class="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><div class="space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Purpose and scope</h2><p class="mt-4 whitespace-pre-line text-sm leading-6 text-slate-600 dark:text-slate-300">{{ $sop->summary ?: 'No summary has been added.' }}</p></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Procedure</h2>@if($sop->content_text)<div class="mt-5 whitespace-pre-wrap font-mono text-sm leading-7 text-slate-700 dark:text-slate-200">{{ $sop->content_text }}</div>@else<p class="mt-4 text-sm text-slate-500">This SOP is maintained in its linked file or Drive document.</p>@endif</section>
        </div><aside class="space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Document control</h2><dl class="mt-5 space-y-4">@foreach([['Department',$sop->department->label()],['Version',$sop->version_label],['Owner',$sop->owner?->name],['Effective date',$sop->effective_date?->format('M j, Y')],['Next review',$sop->review_date?->format('M j, Y')],['Last updated',$sop->updated_at->format('M j, Y g:i A')]] as [$label,$value])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-medium">{{ $value ?: '—' }}</dd></div>@endforeach</dl></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Sources</h2><div class="mt-4 space-y-3">@if($sop->hasFile())<a href="{{ route('sops.download',$sop) }}" class="block rounded-lg border border-slate-200 p-3 text-sm font-semibold hover:border-amber-400 dark:border-slate-700"><span class="block truncate">Download {{ $sop->original_name }}</span><span class="mt-1 block text-xs font-normal text-slate-500">{{ number_format($sop->size_bytes/1024,1) }} KB · Private file</span></a>@endif @if($sop->drive_url)<a href="{{ $sop->drive_url }}" target="_blank" rel="noopener noreferrer" class="block rounded-lg border border-slate-200 p-3 text-sm font-semibold hover:border-amber-400 dark:border-slate-700">Open Google Drive source ↗</a>@endif @if(!$sop->hasFile() && !$sop->drive_url)<p class="text-sm text-slate-500">The written procedure above is the only source.</p>@endif</div></section>
        </aside></div>
        @if($sop->nextSop)
            <section class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-6 shadow-sm dark:border-amber-900 dark:bg-amber-950/25"><div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p class="text-xs font-semibold uppercase tracking-widest text-amber-700 dark:text-amber-400">Continue workflow</p><h2 class="mt-2 text-lg font-bold">Next SOP: {{ $sop->nextSop->title }}</h2><p class="mt-1 text-sm text-slate-600 dark:text-slate-300">{{ $sop->nextSop->department->label() }} · {{ $sop->nextSop->status->label() }}@if($sop->nextSop->summary) · {{ \Illuminate\Support\Str::limit($sop->nextSop->summary, 140) }}@endif</p></div><a href="{{ route('sops.show',$sop->nextSop) }}" class="inline-flex shrink-0 items-center justify-center rounded-lg bg-amber-400 px-5 py-3 text-sm font-semibold text-slate-950">Open next SOP →</a></div></section>
        @elseif(auth()->user()->can('update',$sop))
            <section class="mt-6 rounded-2xl border border-dashed border-slate-300 p-5 dark:border-slate-700"><p class="text-sm text-slate-500">No next SOP is assigned.</p><a href="{{ route('sops.edit',$sop) }}#next_sop_id" class="mt-2 inline-flex text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Assign the next SOP →</a></section>
        @endif
        <a href="{{ route('sops.index') }}" class="mt-6 inline-flex text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">← Back to SOPs</a>
    </div>
</x-layouts.app>
