@csrf
@if(isset($property)) @method('PUT') @endif
@php($draft = $aiValues ?? [])
@if(!isset($property) && isset($intakeReview) && $intakeReview)
    <input type="hidden" name="intake_token" value="{{ $intakeReview['token'] }}">
@endif
<div class="space-y-8">
    <section><h2 class="text-base font-semibold">Property information</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <div><label for="parcel_id" class="text-sm font-medium">Parcel ID</label><input id="parcel_id" name="parcel_id" value="{{ old('parcel_id', data_get($draft, 'parcel_id', $property->parcel_id ?? '')) }}" class="form-input"><x-form-error name="parcel_id" /></div>
        <div><label for="property_type" class="text-sm font-medium">Property type *</label><select id="property_type" name="property_type" required class="form-input"><option value="">Choose a type</option>@foreach($propertyTypes as $type)<option value="{{ $type->value }}" @selected(old('property_type', data_get($draft, 'property_type', isset($property) ? $property->property_type->value : '')) === $type->value)>{{ $type->label() }}</option>@endforeach</select><x-form-error name="property_type" /></div>
        <div><label for="status" class="text-sm font-medium">Status *</label><select id="status" name="status" required class="form-input">@foreach($propertyStatuses as $status)<option value="{{ $status->value }}" @selected(old('status', data_get($draft, 'status', isset($property) ? $property->status->value : 'research')) === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="status" /></div>
        <div class="sm:col-span-2"><label for="address" class="text-sm font-medium">Street address *</label><input id="address" name="address" value="{{ old('address', data_get($draft, 'address', $property->address ?? '')) }}" required class="form-input"><x-form-error name="address" /></div>
        <div><label for="city" class="text-sm font-medium">City *</label><input id="city" name="city" value="{{ old('city', data_get($draft, 'city', $property->city ?? '')) }}" required class="form-input"><x-form-error name="city" /></div>
        <div><label for="county" class="text-sm font-medium">County *</label><input id="county" name="county" value="{{ old('county', data_get($draft, 'county', $property->county ?? '')) }}" required class="form-input"><x-form-error name="county" /></div>
        <div><label for="state" class="text-sm font-medium">State *</label><input id="state" name="state" maxlength="2" value="{{ old('state', data_get($draft, 'state', $property->state ?? '')) }}" required class="form-input uppercase"><x-form-error name="state" /></div>
        <div><label for="postal_code" class="text-sm font-medium">ZIP code</label><input id="postal_code" name="postal_code" value="{{ old('postal_code', data_get($draft, 'postal_code', $property->postal_code ?? '')) }}" class="form-input"><x-form-error name="postal_code" /></div>
        <div><label for="acreage" class="text-sm font-medium">Acreage</label><input id="acreage" name="acreage" type="number" min="0" step="0.0001" value="{{ old('acreage', data_get($draft, 'acreage', $property->acreage ?? '')) }}" class="form-input"><x-form-error name="acreage" /></div>
        <div><label for="owner_contact_id" class="text-sm font-medium">Owner contact</label><select id="owner_contact_id" name="owner_contact_id" class="form-input"><option value="">No linked owner</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string) old('owner_contact_id', $property->owner_contact_id ?? '') === (string) $contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="owner_contact_id" /></div>
    </div></section>

    <section><h2 class="text-base font-semibold">Research</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <div><label for="zoning" class="text-sm font-medium">Zoning</label><input id="zoning" name="zoning" value="{{ old('zoning', data_get($draft, 'zoning', $property->zoning ?? '')) }}" class="form-input"><x-form-error name="zoning" /></div>
        <div><label for="flood_zone" class="text-sm font-medium">Flood zone</label><input id="flood_zone" name="flood_zone" value="{{ old('flood_zone', data_get($draft, 'flood_zone', $property->flood_zone ?? '')) }}" class="form-input"><x-form-error name="flood_zone" /></div>
        <div><label for="wetlands_status" class="text-sm font-medium">Wetlands *</label><select id="wetlands_status" name="wetlands_status" required class="form-input">@foreach($wetlandsStatuses as $status)<option value="{{ $status->value }}" @selected(old('wetlands_status', data_get($draft, 'wetlands_status', isset($property) ? $property->wetlands_status->value : 'unknown')) === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="wetlands_status" /></div>
        <div><label for="road_access" class="text-sm font-medium">Road access</label><input id="road_access" name="road_access" value="{{ old('road_access', data_get($draft, 'road_access', $property->road_access ?? '')) }}" class="form-input"><x-form-error name="road_access" /></div>
        @foreach(['electricity' => 'Electricity', 'water' => 'Water', 'sewer' => 'Sewer', 'gas' => 'Gas'] as $key => $label)<div><label for="utilities_{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="utilities_{{ $key }}" name="utilities[{{ $key }}]" value="{{ old('utilities.'.$key, data_get($draft, 'utilities.'.$key, data_get($property->utilities ?? [], $key))) }}" class="form-input"><x-form-error name="utilities.{{ $key }}" /></div>@endforeach
        <div class="sm:col-span-2 lg:col-span-3"><label for="gis_links_text" class="text-sm font-medium">GIS links</label><textarea id="gis_links_text" name="gis_links_text" rows="3" placeholder="One HTTP or HTTPS URL per line" class="form-input">{{ old('gis_links_text', isset($property) ? implode("\n", $property->gis_links ?? []) : '') }}</textarea><x-form-error name="gis_links_text" /></div>
        @if(auth()->user()->canViewPropertySourceDocuments())
            <div class="sm:col-span-2 lg:col-span-3">
                <label for="document_drive_url" class="text-sm font-medium">Document Drive folder</label>
                <input id="document_drive_url" name="document_drive_url" type="url" inputmode="url" placeholder="https://drive.google.com/drive/folders/..." value="{{ old('document_drive_url', $property->document_drive_url ?? '') }}" class="form-input">
                <p class="mt-1 text-xs text-slate-500">Paste the private HTTPS link to the Drive folder containing documents for this property.</p>
                <x-form-error name="document_drive_url" />
            </div>
            <div class="sm:col-span-2 lg:col-span-3">
                <label for="closing_documents_url" class="text-sm font-medium">Closing documents</label>
                <input id="closing_documents_url" name="closing_documents_url" type="url" inputmode="url" placeholder="https://drive.google.com/drive/folders/..." value="{{ old('closing_documents_url', $property->closing_documents_url ?? '') }}" class="form-input">
                <p class="mt-1 text-xs text-slate-500">Paste the private HTTPS link to the closing document folder or completed closing package.</p>
                <x-form-error name="closing_documents_url" />
            </div>
        @endif
        <div class="sm:col-span-2 lg:col-span-3"><label for="legal_description" class="text-sm font-medium">Legal description</label><textarea id="legal_description" name="legal_description" rows="4" class="form-input">{{ old('legal_description', data_get($draft, 'legal_description', $property->legal_description ?? '')) }}</textarea><x-form-error name="legal_description" /></div>
        <div class="sm:col-span-2 lg:col-span-3"><label for="research_notes" class="text-sm font-medium">Research notes</label><textarea id="research_notes" name="research_notes" rows="5" class="form-input">{{ old('research_notes', data_get($draft, 'research_notes', $property->research_notes ?? '')) }}</textarea><x-form-error name="research_notes" /></div>
    </div></section>

    @if(auth()->user()->canViewPropertyFinancials())
        @php($purchaseValue = old('purchase_price', data_get($draft, 'purchase_price', $property->purchase_price ?? 0)))
        @php($taxesValue = old('taxes', data_get($draft, 'taxes', $property->taxes ?? 0)))
        @php($attorneyValue = old('attorney_fees', data_get($draft, 'attorney_fees', $property->attorney_fees ?? 0)))
        @php($realtorValue = old('realtor_fees', data_get($draft, 'realtor_fees', $property->realtor_fees ?? 0)))
        @php($otherCostsValue = old('other_costs', data_get($draft, 'other_costs', $property->other_costs ?? 0)))
        <section x-data="{ purchase: {{ (float) $purchaseValue }}, taxes: {{ (float) $taxesValue }}, attorney: {{ (float) $attorneyValue }}, realtor: {{ (float) $realtorValue }}, other: {{ (float) $otherCostsValue }}, total() { return [this.purchase, this.taxes, this.attorney, this.realtor, this.other].reduce((sum, value) => sum + (Number(value) || 0), 0); } }"><h2 class="text-base font-semibold">Financials</h2><p class="mt-1 text-sm text-slate-500">All-in updates automatically from purchase price plus every listed cost.</p><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            <div><label for="purchase_price" class="text-sm font-medium">Purchase price</label><input id="purchase_price" name="purchase_price" type="number" min="0" step="0.01" x-model.number="purchase" class="form-input"><x-form-error name="purchase_price" /></div>
            <div><label for="taxes" class="text-sm font-medium">Taxes</label><input id="taxes" name="taxes" type="number" min="0" step="0.01" x-model.number="taxes" class="form-input"><x-form-error name="taxes" /></div>
            <div><label for="attorney_fees" class="text-sm font-medium">Attorney fees</label><input id="attorney_fees" name="attorney_fees" type="number" min="0" step="0.01" x-model.number="attorney" class="form-input"><x-form-error name="attorney_fees" /></div>
            <div><label for="realtor_fees" class="text-sm font-medium">Realtor fees</label><input id="realtor_fees" name="realtor_fees" type="number" min="0" step="0.01" x-model.number="realtor" class="form-input"><x-form-error name="realtor_fees" /></div>
            <div><label for="other_costs" class="text-sm font-medium">Other costs</label><input id="other_costs" name="other_costs" type="number" min="0" step="0.01" x-model.number="other" class="form-input"><x-form-error name="other_costs" /></div>
            <div><label for="all_in_amount" class="text-sm font-medium">All-in amount</label><input id="all_in_amount" name="all_in_amount" type="number" step="0.01" :value="total().toFixed(2)" readonly class="form-input bg-slate-100 font-semibold dark:bg-slate-800"><p class="mt-1 text-xs text-slate-500">Calculated automatically</p><x-form-error name="all_in_amount" /></div>
            @foreach(['arv' => 'ARV', 'wholesale_price' => 'Wholesale price', 'investor_price' => 'Investor price', 'expected_sales_price' => 'Expected sales price', 'actual_sales_price' => 'Actual sales price'] as $key => $label)<div><label for="{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" type="number" min="0" step="0.01" value="{{ old($key, data_get($draft, $key, $property->{$key} ?? '')) }}" class="form-input"><x-form-error name="{{ $key }}" /></div>@endforeach
            <div class="rounded-xl bg-slate-50 p-4 sm:col-span-2 lg:col-span-4 dark:bg-slate-950/50"><p class="text-sm font-semibold">All-in and profit are calculated automatically</p><p class="mt-1 text-sm text-slate-500">All-in equals purchase price + taxes + attorney fees + realtor fees + other costs. Expected and actual profit equal the applicable sales price minus all-in.</p>@if(isset($property))<a href="{{ route('financials.properties.edit',$property) }}" class="mt-3 inline-flex text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Configure payment split</a>@endif</div>
            <div class="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 sm:col-span-2 lg:col-span-4 dark:border-slate-700 dark:bg-slate-950/50">
                <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p class="text-sm font-semibold">Linked deal financials</p><p class="mt-1 text-sm text-slate-500">Create or open a deal from the saved property record to manage offers, contracts, parties, deadlines, and deal-level revenue.</p></div><span class="self-start rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">Available after save</span></div>
            </div>
        </div></section>
    @endif
</div>

@if(!isset($property) && isset($intakeReview) && $intakeReview)<label class="mt-8 flex items-start gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm dark:border-amber-900 dark:bg-amber-950/40"><input type="checkbox" name="approve_extracted_data" value="1" required class="mt-1 rounded border-slate-300"><span><strong>Approve property creation</strong><span class="mt-1 block text-slate-600 dark:text-slate-300">I reviewed and corrected the extracted values and authorize VVR Command Center to create this property and attach the source document.</span></span></label><x-form-error name="approve_extracted_data" />@endif
<div class="mt-8 flex justify-end gap-3"><a href="{{ isset($property) ? route('properties.show', $property) : (isset($conversation) ? route('vvr-ai.conversations.show', $conversation) : route('properties.index')) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">{{ isset($property) ? 'Save changes' : (isset($intakeReview) && $intakeReview ? 'Approve and create property' : 'Create property') }}</button></div>
