<x-layouts.app title="{{ $property->address }}" heading="{{ $property->address }}" subheading="{{ $property->city }}, {{ $property->state }} {{ $property->postal_code }}">
    <div class="mx-auto max-w-6xl">
        <div class="mb-5 flex flex-wrap justify-end gap-3">@can('create', \App\Models\OutboundEmail::class)<a href="{{ route('email.create',['related_type'=>'property','related_id'=>$property->id]) }}" class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950">Send email</a>@endcan @can('create', \App\Models\CalendarEvent::class)<a href="{{ route('calendar.create', ['property' => $property]) }}" class="rounded-lg border border-amber-300 px-4 py-2 text-sm font-semibold text-amber-800 dark:border-amber-800 dark:text-amber-300">Schedule auction</a>@endcan @can('update', $property)<a href="{{ route('properties.edit', $property) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Edit</a>@endcan @can('delete', $property)<form method="POST" action="{{ route('properties.destroy', $property) }}" onsubmit="return confirm('Archive this property?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm font-medium text-rose-600 dark:border-rose-900">Archive</button></form>@endcan</div>

        <div class="grid gap-6 lg:grid-cols-3">
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Property information</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2">
                @foreach([['Parcel ID', $property->parcel_id], ['County', $property->county], ['Property type', $property->property_type->label()], ['Status', $property->status->label()], ['Acreage', $property->acreage !== null ? number_format((float) $property->acreage, 4) : null], ['Zoning', $property->zoning], ['Flood zone', $property->flood_zone], ['Wetlands', $property->wetlands_status->label()], ['Road access', $property->road_access]] as [$label, $value])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm">{{ $value ?: '—' }}</dd></div>@endforeach
                @if($property->legal_description)<div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Legal description</dt><dd class="mt-2 whitespace-pre-line text-sm leading-6">{{ $property->legal_description }}</dd></div>@endif
                @if($property->research_notes)<div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Research notes</dt><dd class="mt-2 whitespace-pre-line text-sm leading-6">{{ $property->research_notes }}</dd></div>@endif
            </dl></section>

            <div class="space-y-6">
                <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Owner</h2>@if($property->ownerContact)<a href="{{ route('contacts.show', $property->ownerContact) }}" class="mt-4 block font-medium hover:text-amber-600">{{ $property->ownerContact->full_name }}</a><p class="mt-1 text-sm text-slate-500">{{ $property->ownerContact->company ?: 'No company' }}</p><p class="mt-3 text-sm">{{ $property->ownerContact->email ?: 'No email' }}</p><p class="mt-1 text-sm">{{ $property->ownerContact->phone ?: 'No phone' }}</p>@else<p class="mt-4 text-sm text-slate-500">No owner contact linked.</p>@endif</section>

                @can('viewFinancials', $property)<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between gap-3"><h2 class="font-semibold">Financials</h2><a href="{{ route('financials.properties.edit',$property) }}" class="text-xs font-semibold text-amber-700 hover:underline dark:text-amber-400">Configure</a></div><dl class="mt-4 space-y-3">@foreach([['Purchase price', $property->purchase_price], ['Taxes', $property->taxes], ['Attorney fees', $property->attorney_fees], ['Realtor fees', $property->realtor_fees], ['Other costs', $property->other_costs], ['All-in amount', $property->all_in_amount], ['ARV', $property->arv], ['Wholesale price', $property->wholesale_price], ['Investor price', $property->investor_price], ['Expected sales price', $property->expected_sales_price], ['Actual sales price', $property->actual_sales_price], ['Expected profit', $property->expected_profit], ['Actual profit', $property->actual_profit]] as [$label, $value])<div class="flex justify-between gap-4 text-sm"><dt class="text-slate-500">{{ $label }}</dt><dd class="font-medium">{{ $value !== null ? (($value < 0 ? '−$' : '$').number_format(abs((float) $value), 2)) : '—' }}</dd></div>@endforeach</dl><p class="mt-3 border-t border-slate-200 pt-3 text-xs text-slate-500 dark:border-slate-800">All-in = purchase price + taxes + attorney fees + realtor fees + other costs.</p><div class="mt-5 rounded-xl bg-slate-50 p-4 dark:bg-slate-950/50"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">20 / 40 / 40 payment split</p><p class="mt-2 text-sm"><strong>20% VVR</strong></p><p class="mt-1 text-sm"><strong>40%</strong> {{ $property->financialSplit?->contactOne?->full_name ?? 'Unassigned contact' }}</p><p class="mt-1 text-sm"><strong>40%</strong> {{ $property->financialSplit?->contactTwo?->full_name ?? 'Unassigned contact' }}</p></div></section>@endcan
            </div>
        </div>

        <div class="mt-6 grid gap-6 lg:grid-cols-2">
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Utilities</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2">@foreach(['electricity' => 'Electricity', 'water' => 'Water', 'sewer' => 'Sewer', 'gas' => 'Gas'] as $key => $label)<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm">{{ data_get($property->utilities, $key) ?: '—' }}</dd></div>@endforeach</dl></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">GIS links</h2><div class="mt-4 space-y-2">@forelse($property->gis_links ?? [] as $link)<a href="{{ $link }}" target="_blank" rel="noopener noreferrer" class="block truncate text-sm font-medium text-amber-700 hover:underline dark:text-amber-400">{{ $link }} ↗</a>@empty<p class="text-sm text-slate-500">No GIS links saved.</p>@endforelse</div></section>
        </div>

        @can('viewFinancials', $property)
        @if($property->taxRecords->isNotEmpty())
            <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Property tax history</h2><p class="mt-1 text-sm text-slate-500">Annual assessment history. These amounts are not acquisition costs and do not affect all-in calculations.</p><div class="mt-4 overflow-x-auto"><table class="w-full min-w-[820px] text-left text-sm"><thead class="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500 dark:border-slate-800"><tr><th class="py-3 pr-4">Year</th><th class="py-3 pr-4">Market</th><th class="py-3 pr-4">Assessed</th><th class="py-3 pr-4">Taxable</th><th class="py-3 pr-4">Prior final tax</th><th class="py-3 pr-4">Proposed tax</th><th class="py-3">Classification</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@foreach($property->taxRecords as $record)<tr><td class="py-3 pr-4 font-semibold">{{ $record->tax_year }}</td>@foreach([$record->market_value,$record->assessed_value,$record->taxable_value,$record->prior_year_final_tax,$record->proposed_tax] as $amount)<td class="py-3 pr-4">{{ $amount !== null ? '$'.number_format((float)$amount,2) : '—' }}</td>@endforeach<td class="py-3">{{ $record->assessment_classification ?: '—' }}</td></tr>@endforeach</tbody></table></div></section>
        @endif
        @endcan

        <section id="checklist" class="mt-6 scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
                <div><h2 class="font-semibold">Property checklist</h2><p class="mt-1 text-sm text-slate-500">Track required acquisition records and link the completed document or supporting item.</p></div>
                <span class="self-start rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold dark:bg-slate-800">{{ $checklistItems->where('is_completed', true)->count() }} of {{ $checklistItems->count() }} complete</span>
            </div>

            @can('update', $property)<form method="POST" action="{{ route('properties.checklist.update', $property) }}" class="mt-5">@csrf @method('PUT')@else<div class="mt-5">@endcan
                <div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500 dark:border-slate-800"><tr><th class="px-3 py-3">Complete</th><th class="px-3 py-3">Checklist item</th><th class="px-3 py-3">Completed details</th>@can('viewSourceDocuments', $property)<th class="px-3 py-3">Completed item link</th>@endcan</tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
                    @foreach($checklistItems as $item)
                        @php($key = $item->item_key->value)
                        <tr class="align-top">
                            <td class="px-3 py-4">@can('update', $property)<input type="hidden" name="items[{{ $key }}][completed]" value="0"><input type="checkbox" name="items[{{ $key }}][completed]" value="1" @checked((bool) old("items.{$key}.completed", $item->is_completed)) class="h-5 w-5 rounded border-slate-300 text-amber-500 focus:ring-amber-400">@else<span class="text-lg">{{ $item->is_completed ? '✓' : '○' }}</span>@endcan</td>
                            <td class="px-3 py-4"><p class="font-medium">{{ $item->item_key->label() }}</p><p class="mt-1 text-xs {{ $item->is_completed ? 'text-emerald-600 dark:text-emerald-400' : 'text-slate-400' }}">{{ $item->is_completed ? 'Completed' : 'Pending' }}</p></td>
                            <td class="px-3 py-4 text-xs text-slate-500">@if($item->completed_at)<p>{{ $item->completed_at->format('M j, Y g:i A') }}</p><p class="mt-1">{{ $item->completedBy?->name ?? 'User unavailable' }}</p>@else—@endif</td>
                            @can('viewSourceDocuments', $property)<td class="px-3 py-4">@can('update', $property)<input type="url" name="items[{{ $key }}][evidence_url]" inputmode="url" placeholder="https://drive.google.com/..." value="{{ old("items.{$key}.evidence_url", $item->evidence_url) }}" class="form-input mt-0 min-w-72"><x-form-error name="items.{{ $key }}.evidence_url" />@elseif($item->evidence_url)<a href="{{ $item->evidence_url }}" target="_blank" rel="noopener noreferrer" class="font-semibold text-amber-700 hover:underline dark:text-amber-400">Open completed item ↗</a>@else<span class="text-slate-400">No link</span>@endcan @if($item->evidence_url && auth()->user()->can('update', $property))<a href="{{ $item->evidence_url }}" target="_blank" rel="noopener noreferrer" class="mt-2 block text-xs font-semibold text-amber-700 hover:underline dark:text-amber-400">Open current link ↗</a>@endif</td>@endcan
                        </tr>
                    @endforeach
                </tbody></table></div>
                @can('update', $property)<div class="mt-5 flex justify-end"><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">Save checklist</button></div></form>@else</div>@endcan
        </section>

        <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Associated contacts</h2><p class="mt-1 text-sm text-slate-500">Contacts assigned to this property outside the dedicated owner relationship.</p><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse($property->contacts as $contact)<a href="{{ route('contacts.show',$contact) }}" class="rounded-xl border border-slate-200 p-4 hover:border-amber-300 dark:border-slate-800 dark:hover:border-amber-700"><p class="font-medium">{{ $contact->full_name }}</p><p class="mt-1 text-xs text-slate-500">{{ $contact->type->label() }}{{ $contact->company ? ' · '.$contact->company : '' }}</p></a>@empty<p class="text-sm text-slate-500 sm:col-span-2 lg:col-span-3">No contacts are assigned to this property.</p>@endforelse</div></section>

        @can('viewSourceDocuments', $property)
            @if($property->document_drive_url || $property->closing_documents_url || $property->intakeFiles->isNotEmpty() || $property->surplusIntakeFiles->isNotEmpty())
                <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                    <h2 class="font-semibold">Property documents</h2>
                    <p class="mt-1 text-sm text-slate-500">Private document locations and historical source files for this property.</p>

                    @if($property->document_drive_url)
                        <div class="mt-4 flex flex-col justify-between gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center dark:border-slate-800">
                            <div class="min-w-0">
                                <p class="text-sm font-medium">Google Drive folder</p>
                                <p class="mt-1 truncate text-xs text-slate-500">{{ $property->document_drive_url }}</p>
                            </div>
                            <a href="{{ $property->document_drive_url }}" target="_blank" rel="noopener noreferrer" class="shrink-0 text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Open Drive Folder ↗</a>
                        </div>
                    @endif

                    @if($property->closing_documents_url)
                        <div class="mt-4 flex flex-col justify-between gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center dark:border-slate-800">
                            <div class="min-w-0">
                                <p class="text-sm font-medium">Closing documents</p>
                                <p class="mt-1 truncate text-xs text-slate-500">{{ $property->closing_documents_url }}</p>
                            </div>
                            <a href="{{ $property->closing_documents_url }}" target="_blank" rel="noopener noreferrer" class="shrink-0 text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Open Closing Documents ↗</a>
                        </div>
                    @endif

                    @if($property->intakeFiles->isNotEmpty())
                        <div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@foreach($property->intakeFiles as $file)<div class="flex flex-col justify-between gap-3 py-3 sm:flex-row sm:items-center"><div><p class="text-sm font-medium">{{ $file->original_name }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($file->size_bytes / 1024, 1) }} KB · Attached {{ $file->attached_at?->format('M j, Y g:i A') }}</p></div><a href="{{ route('properties.intake-files.download', [$property, $file]) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Download</a></div>@endforeach</div>
                    @endif
                    @if($property->surplusIntakeFiles->isNotEmpty())
                        <div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@foreach($property->surplusIntakeFiles as $file)<div class="py-3"><p class="text-sm font-medium">{{ $file->original_name }}</p><p class="mt-1 text-xs text-slate-500">Surplus ownership/tax source · {{ number_format($file->size_bytes / 1024, 1) }} KB · Access from its linked Surplus case.</p></div>@endforeach</div>
                    @endif
                </section>
            @endif
        @endcan
    </div>
        <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="font-semibold">Deals</h2><p class="mt-1 text-sm text-slate-500">Transactions linked to this property.</p></div>@can('create',\App\Models\Deal::class)<a href="{{ route('deals.create',['property_id'=>$property->id]) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Add deal</a>@endcan</div><div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($property->deals as $deal)<a href="{{ route('deals.show',$deal) }}" class="flex flex-col justify-between gap-2 py-3 hover:text-amber-700 sm:flex-row sm:items-center"><span><span class="font-medium">{{ $deal->title }}</span><span class="mt-1 block text-xs text-slate-500">{{ $deal->deal_number }} · {{ $deal->type->label() }}</span></span><span class="text-xs font-semibold">{{ $deal->status->label() }}</span></a>@empty<p class="py-6 text-sm text-slate-500">No deals are linked to this property.</p>@endforelse</div></section>
        @if(auth()->user()->canViewSurplusCases())<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between"><div><h2 class="font-semibold">Surplus cases</h2><p class="mt-1 text-sm text-slate-500">Recovery cases linked to this property.</p></div>@can('create',\App\Models\SurplusCase::class)<a href="{{ route('surplus.create',['property_id'=>$property->id]) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Add case</a>@endcan</div><div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($property->surplusCases as $case)<a href="{{ route('surplus.show',$case) }}" class="flex justify-between gap-3 py-3 hover:text-amber-700"><span class="font-medium">{{ $case->case_number }}</span><span class="text-xs font-semibold">{{ $case->status->label() }}{{ $case->claim_deadline ? ' · '.$case->claim_deadline->format('M j, Y') : '' }}</span></a>@empty<p class="py-6 text-sm text-slate-500">No surplus cases are linked to this property.</p>@endforelse</div></section>@endif
        @if(auth()->user()->canViewPreAuctionAcquisitions())<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between"><div><h2 class="font-semibold">PreTax Auction acquisitions</h2><p class="mt-1 text-sm text-slate-500">Owner-interest acquisitions linked to this property before tax deed auction.</p></div>@can('create',\App\Models\PreAuctionAcquisition::class)<a href="{{ route('pre-auction.create',['property_id'=>$property->id]) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Add acquisition</a>@endcan</div><div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($property->preAuctionAcquisitions as $case)<a href="{{ route('pre-auction.show',$case) }}" class="flex justify-between gap-3 py-3 hover:text-amber-700"><span class="font-medium">{{ $case->case_number }}</span><span class="text-xs font-semibold">{{ $case->status->label() }}{{ $case->auction_at ? ' · '.$case->auction_at->format('M j, Y') : '' }}</span></a>@empty<p class="py-6 text-sm text-slate-500">No PreTax Auction acquisitions are linked to this property.</p>@endforelse</div></section>@endif
        <x-email-history :record="$property" />
</x-layouts.app>
