@csrf
@isset($case) @method('PUT') @endisset
@php($value = fn(string $key, mixed $default = null) => old($key, isset($case) ? data_get($case, $key) : request($key, $default)))
<div class="space-y-8">
    <section><h2 class="font-semibold">Assignment and workflow</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <div><label for="status" class="text-sm font-medium">Pipeline stage *</label><select id="status" name="status" required class="form-input">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(($value('status','research') instanceof \App\Enums\PreAuctionAcquisitionStatus ? $value('status')->value : $value('status','research')) === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="status" /></div>
        <div><label for="owner_contact_id" class="text-sm font-medium">Current owner</label><select id="owner_contact_id" name="owner_contact_id" class="form-input"><option value="">No owner selected</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string)$value('owner_contact_id')===(string)$contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' · '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="owner_contact_id" /></div>
        <div><label for="assigned_user_id" class="text-sm font-medium">Assigned user</label><select id="assigned_user_id" name="assigned_user_id" class="form-input"><option value="">Unassigned</option>@foreach($assignees as $user)<option value="{{ $user->id }}" @selected((string)$value('assigned_user_id')===(string)$user->id)>{{ $user->name }}</option>@endforeach</select><x-form-error name="assigned_user_id" /></div>
        <div class="sm:col-span-2"><label for="property_id" class="text-sm font-medium">Related property</label><select id="property_id" name="property_id" class="form-input"><option value="">No property selected</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected((string)$value('property_id')===(string)$property->id)>{{ $property->address }} · {{ $property->city }}, {{ $property->state }}{{ $property->parcel_id ? ' · '.$property->parcel_id : '' }}</option>@endforeach</select><x-form-error name="property_id" /></div>
        <div><label for="source" class="text-sm font-medium">Lead source</label><input id="source" name="source" maxlength="120" value="{{ $value('source') }}" class="form-input"><x-form-error name="source" /></div>
    </div></section>

    <section><h2 class="font-semibold">Florida tax deed identifiers</h2><p class="mt-1 text-sm text-slate-500">This department is limited to Florida properties already scheduled for tax deed auction.</p><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <div><label for="state" class="text-sm font-medium">State *</label><input id="state" name="state" value="FL" readonly class="form-input bg-slate-100 dark:bg-slate-800"></div>
        <div><label for="county" class="text-sm font-medium">County *</label><input id="county" name="county" required maxlength="120" value="{{ $value('county') }}" class="form-input"><x-form-error name="county" /></div>
        <div><label for="parcel_id" class="text-sm font-medium">Parcel ID *</label><input id="parcel_id" name="parcel_id" required maxlength="120" value="{{ $value('parcel_id') }}" class="form-input"><x-form-error name="parcel_id" /></div>
        <div><label for="tax_deed_number" class="text-sm font-medium">Tax deed number</label><input id="tax_deed_number" name="tax_deed_number" maxlength="120" value="{{ $value('tax_deed_number') }}" class="form-input"><x-form-error name="tax_deed_number" /></div>
        <div><label for="certificate_number" class="text-sm font-medium">Certificate number</label><input id="certificate_number" name="certificate_number" maxlength="120" value="{{ $value('certificate_number') }}" class="form-input"><x-form-error name="certificate_number" /></div>
        <div><label for="assessor_market_value" class="text-sm font-medium">Assessor market value</label><input id="assessor_market_value" name="assessor_market_value" type="number" min="0" step="0.01" value="{{ $value('assessor_market_value') }}" class="form-input"><x-form-error name="assessor_market_value" /></div>
        <div><label for="auction_at" class="text-sm font-medium">Scheduled auction *</label><input id="auction_at" name="auction_at" type="datetime-local" required value="{{ old('auction_at',isset($case) ? $case->auction_at?->format('Y-m-d\TH:i') : '') }}" class="form-input"><x-form-error name="auction_at" /></div>
        <div class="sm:col-span-2"><label for="auction_url" class="text-sm font-medium">Auction link</label><input id="auction_url" name="auction_url" type="url" value="{{ $value('auction_url') }}" class="form-input"><x-form-error name="auction_url" /></div>
        <div class="sm:col-span-2"><label for="appraiser_url" class="text-sm font-medium">Property appraiser link</label><input id="appraiser_url" name="appraiser_url" type="url" value="{{ $value('appraiser_url') }}" class="form-input"><x-form-error name="appraiser_url" /></div>
        <div class="sm:col-span-2"><label for="property_details_url" class="text-sm font-medium">Property details source</label><input id="property_details_url" name="property_details_url" type="url" value="{{ $value('property_details_url') }}" class="form-input"><x-form-error name="property_details_url" /></div>
        <div><label for="purchase_deadline" class="text-sm font-medium">Internal purchase deadline</label><input id="purchase_deadline" name="purchase_deadline" type="date" value="{{ old('purchase_deadline',isset($case) ? $case->purchase_deadline?->format('Y-m-d') : '') }}" class="form-input"><x-form-error name="purchase_deadline" /></div>
    </div></section>

    <section><h2 class="font-semibold">Acquisition and recording milestones</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        @foreach(['contract_date'=>'Contract date','closing_date'=>'Closing date','deed_recorded_date'=>'Deed recorded date','non_redemption_reviewed_at'=>'Non-redemption strategy reviewed'] as $key=>$label)<div><label for="{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" type="date" value="{{ old($key,isset($case) ? $case->{$key}?->format('Y-m-d') : '') }}" class="form-input"><x-form-error name="{{ $key }}" /></div>@endforeach
        <div class="sm:col-span-2"><label for="recording_instrument_number" class="text-sm font-medium">Recording instrument number</label><input id="recording_instrument_number" name="recording_instrument_number" maxlength="160" value="{{ $value('recording_instrument_number') }}" class="form-input"><x-form-error name="recording_instrument_number" /></div>
        <div class="sm:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><strong>Required control:</strong> recording a review date documents an internal strategy review only. The Command Center never redeems certificates, records a deed, submits a claim, or determines legal entitlement automatically.</div>
    </div></section>

    @if(auth()->user()->canViewPreAuctionFinancials())
        <section x-data="{ purchase: Number(@js($value('purchase_price',0))) || 0, closing: Number(@js($value('closing_costs',0))) || 0, other: Number(@js($value('other_costs',0))) || 0, projected: Number(@js($value('projected_surplus',0))) || 0, recovered: Number(@js($value('amount_recovered',0))) || 0, total(){ return this.purchase+this.closing+this.other }, money(v){ return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0) } }">
            <h2 class="font-semibold">Acquisition economics</h2><p class="mt-1 text-sm text-slate-500">Net values update from the same authoritative case fields everywhere.</p><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
                <div><label for="purchase_price" class="text-sm font-medium">Owner purchase price</label><input id="purchase_price" name="purchase_price" type="number" min="0" step="0.01" value="{{ $value('purchase_price') }}" x-model.number="purchase" class="form-input"><x-form-error name="purchase_price" /></div>
                <div><label for="closing_costs" class="text-sm font-medium">Closing costs</label><input id="closing_costs" name="closing_costs" type="number" min="0" step="0.01" value="{{ $value('closing_costs') }}" x-model.number="closing" class="form-input"><x-form-error name="closing_costs" /></div>
                <div><label for="other_costs" class="text-sm font-medium">Other costs</label><input id="other_costs" name="other_costs" type="number" min="0" step="0.01" value="{{ $value('other_costs') }}" x-model.number="other" class="form-input"><x-form-error name="other_costs" /></div>
                <div><label class="text-sm font-medium">Total acquisition cost</label><div class="form-input bg-slate-100 font-semibold dark:bg-slate-800" x-text="money(total())"></div></div>
                <div><label for="projected_surplus" class="text-sm font-medium">Projected surplus</label><input id="projected_surplus" name="projected_surplus" type="number" min="0" step="0.01" value="{{ $value('projected_surplus') }}" x-model.number="projected" class="form-input"><x-form-error name="projected_surplus" /></div>
                <div><label class="text-sm font-medium">Projected net</label><div class="form-input bg-amber-50 font-semibold dark:bg-amber-950/30" x-text="money(projected-total())"></div></div>
                <div><label for="auction_winning_bid" class="text-sm font-medium">Auction winning bid</label><input id="auction_winning_bid" name="auction_winning_bid" type="number" min="0" step="0.01" value="{{ $value('auction_winning_bid') }}" class="form-input"><x-form-error name="auction_winning_bid" /></div>
                <div><label for="surplus_generated" class="text-sm font-medium">Surplus generated</label><input id="surplus_generated" name="surplus_generated" type="number" min="0" step="0.01" value="{{ $value('surplus_generated') }}" class="form-input"><x-form-error name="surplus_generated" /></div>
                <div><label for="amount_recovered" class="text-sm font-medium">Amount recovered</label><input id="amount_recovered" name="amount_recovered" type="number" min="0" step="0.01" value="{{ $value('amount_recovered') }}" x-model.number="recovered" class="form-input"><x-form-error name="amount_recovered" /></div>
                <div><label class="text-sm font-medium">Actual net</label><div class="form-input bg-emerald-50 font-semibold dark:bg-emerald-950/30" x-text="money(recovered-total())"></div></div>
            </div>
        </section>
    @endif

    <section><h2 class="font-semibold">Post-auction entitlement review</h2><p class="mt-1 text-sm text-slate-500">Eligibility must be supported by a documented human review; no status is inferred from deed ownership alone.</p><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        <div><label for="entitlement_status" class="text-sm font-medium">Review status *</label><select id="entitlement_status" name="entitlement_status" required class="form-input">@foreach($entitlementStatuses as $status)<option value="{{ $status->value }}" @selected(($value('entitlement_status','not_reviewed') instanceof \App\Enums\PreAuctionEntitlementStatus ? $value('entitlement_status')->value : $value('entitlement_status','not_reviewed')) === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="entitlement_status" /></div>
        <div><label for="entitlement_reviewed_at" class="text-sm font-medium">Reviewed date</label><input id="entitlement_reviewed_at" name="entitlement_reviewed_at" type="date" value="{{ old('entitlement_reviewed_at',isset($case) ? $case->entitlement_reviewed_at?->format('Y-m-d') : '') }}" class="form-input"><x-form-error name="entitlement_reviewed_at" /></div>
        <div><label for="claim_submitted_at" class="text-sm font-medium">Claim submitted</label><input id="claim_submitted_at" name="claim_submitted_at" type="date" value="{{ old('claim_submitted_at',isset($case) ? $case->claim_submitted_at?->format('Y-m-d') : '') }}" class="form-input"><x-form-error name="claim_submitted_at" /></div>
        <div><label for="paid_at" class="text-sm font-medium">Paid</label><input id="paid_at" name="paid_at" type="date" value="{{ old('paid_at',isset($case) ? $case->paid_at?->format('Y-m-d') : '') }}" class="form-input"><x-form-error name="paid_at" /></div>
        <div class="sm:col-span-2 lg:col-span-4"><label for="entitlement_notes" class="text-sm font-medium">Entitlement review basis</label><textarea id="entitlement_notes" name="entitlement_notes" rows="4" maxlength="10000" class="form-input">{{ $value('entitlement_notes') }}</textarea><x-form-error name="entitlement_notes" /></div>
    </div></section>

    @if(auth()->user()->canViewPropertySourceDocuments())<section><h2 class="font-semibold">Private documents</h2><label for="document_drive_url" class="mt-4 block text-sm font-medium">Google Drive folder</label><input id="document_drive_url" name="document_drive_url" type="url" value="{{ $value('document_drive_url') }}" placeholder="https://drive.google.com/drive/folders/..." class="form-input"><x-form-error name="document_drive_url" /></section>@endif
    <section><h2 class="font-semibold">Case notes</h2><textarea name="notes" rows="7" maxlength="50000" class="form-input">{{ $value('notes') }}</textarea><x-form-error name="notes" /></section>
</div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ isset($case) ? route('pre-auction.show',$case) : route('pre-auction.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950">{{ isset($case) ? 'Save acquisition' : 'Create acquisition' }}</button></div>
