<x-layouts.app title="Guided Sessions" heading="Armory Guided Sessions" subheading="Resumable script runs and recorded outcomes">
    @include('armory._navigation', ['active' => 'sessions'])
    <section class="mb-6 rounded-2xl border border-amber-200 bg-gradient-to-br from-amber-50 to-white p-6 shadow-sm dark:border-amber-900/70 dark:from-amber-950/30 dark:to-slate-900">
        <div class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(360px,520px)] lg:items-end">
            <div><p class="text-xs font-semibold uppercase tracking-widest text-amber-700 dark:text-amber-400">Interactive Armory</p><h2 class="mt-2 text-xl font-bold">Start a new guided session</h2><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Choose a script, then connect the session to a contact or property on the next screen.</p></div>
            @if($availableScripts->isNotEmpty())<form method="GET" action="{{ route('armory.sessions.start') }}" class="flex flex-col gap-3 sm:flex-row"><label class="sr-only" for="script_id">Guided script</label><select id="script_id" name="script_id" required class="form-input mt-0 flex-1"><option value="">Choose a guided script</option>@foreach($availableScripts as $script)<option value="{{ $script->id }}">{{ $script->title }} · {{ $script->category->label() }}{{ $script->status !== \App\Enums\ArmoryScriptStatus::Active ? ' · '.$script->status->label() : '' }}</option>@endforeach</select><button class="rounded-lg bg-amber-400 px-5 py-2.5 text-sm font-semibold text-slate-950 hover:bg-amber-300">Start session</button></form>@else<p class="rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-500 dark:border-slate-700 dark:bg-slate-900">No runnable scripts are available. Add interactive steps to an active Armory script first.</p>@endif
        </div>
    </section>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="w-full min-w-[980px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/60"><tr><th class="px-5 py-3">Session</th><th class="px-5 py-3">Contact / property</th><th class="px-5 py-3">User</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Outcome</th><th class="px-5 py-3">Started</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
        @forelse($sessions as $session)<tr><td class="px-5 py-4"><a href="{{ route('armory.sessions.show',$session) }}" class="font-semibold hover:text-amber-600">{{ $session->script->title }}</a></td><td class="px-5 py-4"><p>{{ $session->contact?->full_name ?: 'No contact' }}</p><p class="mt-1 text-xs text-slate-500">{{ $session->property?->address ?: 'No property' }}</p></td><td class="px-5 py-4">{{ $session->user->name }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold dark:bg-slate-800">{{ $session->status->label() }}</span></td><td class="px-5 py-4">{{ $session->outcome ?: '—' }}</td><td class="px-5 py-4 text-xs text-slate-500">{{ $session->started_at->format('M j, Y g:i A') }}</td><td class="px-5 py-4 text-right">@can('delete',$session)<form method="POST" action="{{ route('armory.sessions.destroy', $session, false) }}" onsubmit="return confirm('Delete this guided session? It will be recoverable for 30 days.')">@csrf @method('DELETE')<button type="submit" class="text-sm font-semibold text-rose-600 hover:text-rose-500">Delete</button></form>@endcan</td></tr>
        @empty<tr><td colspan="7" class="px-6 py-14 text-center text-slate-500">No guided sessions have been started.</td></tr>@endforelse
    </tbody></table></div><div class="border-t border-slate-200 px-5 py-4 dark:border-slate-800">{{ $sessions->links() }}</div></section>
</x-layouts.app>
