<x-layouts.app title="{{ $session->script->title }} Session" heading="Guided Session" subheading="{{ $session->script->title }}">
    <div class="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
        <main class="space-y-6">
            @if($session->status === \App\Enums\ArmorySessionStatus::InProgress && $session->currentStep)
                @php($step = $session->currentStep)
                @php($nextSequentialStep = $session->script->steps->first(fn($item) => $item->sequence > $step->sequence))
                <div class="h-2 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800"><div class="h-full bg-amber-400" style="width: {{ max(5, (($session->script->steps->search(fn($item) => $item->id === $step->id) + 1) / max(1,$session->script->steps->count())) * 100) }}%"></div></div>
                <section class="rounded-2xl border border-amber-200 bg-white p-6 shadow-sm dark:border-amber-900 dark:bg-slate-900"><div class="flex flex-wrap items-center justify-between gap-2"><span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800 dark:bg-amber-950 dark:text-amber-300">Script: {{ $session->script->title }}</span><span class="text-xs font-semibold uppercase tracking-widest text-amber-700 dark:text-amber-400">Step {{ $step->sequence }} · {{ $step->title }}</span></div><h2 class="mt-5 text-2xl font-semibold leading-relaxed">{{ $renderer->render($step->prompt_text, $session) }}</h2>@if($step->guidance_text)<div class="mt-6 rounded-xl bg-sky-50 p-4 text-sm leading-6 text-sky-900 dark:bg-sky-950/40 dark:text-sky-200"><strong>Private guidance:</strong> {{ $renderer->render($step->guidance_text, $session) }}</div>@endif</section>
                <form method="POST" action="{{ route('armory.sessions.advance', $session, false) }}" class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">@csrf
                    @if($step->options->isNotEmpty())<fieldset><legend class="font-semibold">What did they say?</legend><div class="mt-4 grid gap-3">@foreach($step->options as $option)<label class="cursor-pointer rounded-xl border border-slate-200 p-4 hover:border-amber-400 has-[:checked]:border-amber-400 has-[:checked]:bg-amber-50 dark:border-slate-700 dark:has-[:checked]:bg-amber-950/30"><input type="radio" name="option_id" value="{{ $option->id }}" required class="mr-2"> <span class="font-semibold">{{ $option->label }}</span>@if($option->response_text)<span class="mt-2 block pl-6 text-sm text-slate-500">Suggested response: {{ $renderer->render($option->response_text, $session) }}</span>@endif @if($option->nextStep)<span class="mt-2 block pl-6 text-xs text-slate-500">Next step: {{ $option->nextStep->title }}</span>@else<span class="mt-2 block pl-6 text-xs text-slate-500">Completes the session</span>@endif</label>@endforeach</div><x-form-error name="option_id" /></fieldset>@endif
                    <div class="mt-5"><label class="text-sm font-medium">Step notes</label><textarea name="step_notes" rows="3" maxlength="5000" class="form-input" placeholder="Capture facts, objections, or commitments from this step."></textarea><x-form-error name="step_notes" /></div><div class="mt-5 text-right"><button type="submit" class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950">@if($step->options->isNotEmpty())Use response @elseif($nextSequentialStep)Continue @else Complete session @endif →</button></div>
                </form>
            @else
                <section class="rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center dark:border-emerald-900 dark:bg-emerald-950/30"><p class="text-sm font-semibold uppercase tracking-widest text-emerald-700 dark:text-emerald-400">{{ $session->status->label() }}</p><h2 class="mt-3 text-2xl font-bold">Session closed</h2><p class="mt-2 text-slate-600 dark:text-slate-300">Outcome: {{ $session->outcome ?: 'Not recorded' }}</p></section>
            @endif

            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Session path</h2><div class="mt-4 space-y-3">@forelse($session->events->sortBy('id') as $event)<div class="border-l-2 border-slate-200 pl-4 dark:border-slate-700"><p class="text-sm font-medium">{{ str($event->event_type)->headline() }}{{ $event->step ? ' · '.$event->step->title : '' }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->option?->label }} {{ data_get($event->payload,'notes') }}</p></div>@empty<p class="text-sm text-slate-500">No events recorded.</p>@endforelse</div></section>
        </main>
        <aside class="space-y-5"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Context</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-xs text-slate-500">Contact</dt><dd class="font-medium">{{ $session->contact?->full_name ?: $session->caller_name ?: 'Not selected' }}</dd></div><div><dt class="text-xs text-slate-500">Property</dt><dd class="font-medium">{{ $session->property?->address ?: 'Not selected' }}</dd></div><div><dt class="text-xs text-slate-500">Script</dt><dd class="font-medium">{{ $session->script->title }}</dd></div><div><dt class="text-xs text-slate-500">Started by</dt><dd class="font-medium">{{ $session->user->name }}</dd></div><div><dt class="text-xs text-slate-500">Started</dt><dd class="font-medium">{{ $session->started_at->format('M j, Y g:i A') }}</dd></div></dl></section>
            @if($session->notes)<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Notes</h2><p class="mt-3 whitespace-pre-line text-sm leading-6">{{ $session->notes }}</p></section>@endif
            @can('update',$session)<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Close session manually</h2><form method="POST" action="{{ route('armory.sessions.finish', $session, false) }}" class="mt-4 space-y-3">@csrf<input name="outcome" required maxlength="120" placeholder="Outcome, e.g. follow_up" class="form-input mt-0"><textarea name="notes" rows="3" maxlength="10000" placeholder="Final notes" class="form-input mt-0"></textarea><button type="submit" class="w-full rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white dark:bg-amber-400 dark:text-slate-950">Complete session</button></form><form method="POST" action="{{ route('armory.sessions.abandon', $session, false) }}" class="mt-3">@csrf<button type="submit" class="w-full rounded-lg border border-rose-300 px-4 py-2 text-sm font-semibold text-rose-600 dark:border-rose-900">Abandon session</button></form></section>@endcan
            @can('delete',$session)<section class="rounded-2xl border border-rose-200 bg-white p-5 shadow-sm dark:border-rose-900 dark:bg-slate-900"><h2 class="font-semibold">Delete session</h2><p class="mt-2 text-sm text-slate-500">Removes this session from Armory. It remains recoverable for 30 days.</p><form method="POST" action="{{ route('armory.sessions.destroy', $session, false) }}" class="mt-4" onsubmit="return confirm('Delete this guided session? It will be recoverable for 30 days.')">@csrf @method('DELETE')<button type="submit" class="w-full rounded-lg border border-rose-300 px-4 py-2 text-sm font-semibold text-rose-600 dark:border-rose-900">Delete guided session</button></form></section>@endcan
        </aside>
    </div>
</x-layouts.app>
