@csrf
@if(isset($task)) @method('PUT') @endif
@php
    $value = fn (string $key, mixed $fallback = null) => old($key, isset($task) ? data_get($task, $key) : data_get($defaults ?? [], $key, $fallback));
    $subjectPrefix = isset($task) && $task->taskable ? match (true) {
        $task->taskable instanceof \App\Models\Contact => 'contact:',
        $task->taskable instanceof \App\Models\Property => 'property:',
        $task->taskable instanceof \App\Models\Deal => 'deal:',
        $task->taskable instanceof \App\Models\SurplusCase => 'surplus:',
        $task->taskable instanceof \App\Models\PreAuctionAcquisition => 'pre_auction:',
        default => '',
    } : '';
    $subject = old('subject', isset($task) && $task->taskable ? $subjectPrefix.$task->taskable_id : request('subject'));
    $selectedRecurrence = $value('recurrence_frequency');
    $selectedRecurrence = $selectedRecurrence instanceof \App\Enums\TaskRecurrence ? $selectedRecurrence->value : $selectedRecurrence;
@endphp
<div class="space-y-8" x-data="{ recurring: @js((bool) $selectedRecurrence) }">
    @if(!isset($task) && $templates->isNotEmpty())
        <section><div class="flex items-center justify-between"><div><h2 class="font-semibold">Start from a template</h2><p class="mt-1 text-sm text-slate-500">Optional: load a standard VVR task and adjust it before saving.</p></div><a href="{{ route('task-templates.index') }}" class="text-sm font-semibold text-amber-700 dark:text-amber-400">Manage templates</a></div><div class="mt-4 flex flex-wrap gap-2">@foreach($templates as $template)<a href="{{ route('tasks.create', ['template' => $template->id]) }}" @class(['rounded-full border px-3 py-1.5 text-xs font-medium', 'border-amber-400 bg-amber-50 text-amber-800 dark:bg-amber-950 dark:text-amber-300' => (string) request('template') === (string) $template->id, 'border-slate-300 dark:border-slate-700' => (string) request('template') !== (string) $template->id])>{{ $template->name }}</a>@endforeach</div></section>
    @endif

    <section><h2 class="font-semibold">Task details</h2><div class="mt-4 grid gap-5 sm:grid-cols-2">
        <div class="sm:col-span-2"><label for="title" class="text-sm font-medium">Title *</label><input id="title" name="title" required maxlength="180" value="{{ $value('title') }}" class="form-input"><x-form-error name="title" /></div>
        <div class="sm:col-span-2"><label for="description" class="text-sm font-medium">Description</label><textarea id="description" name="description" rows="5" class="form-input">{{ $value('description') }}</textarea><x-form-error name="description" /></div>
        <div><label for="status" class="text-sm font-medium">Status *</label><select id="status" name="status" required class="form-input">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($value('status', 'pending') instanceof \App\Enums\TaskStatus ? $value('status')->value === $status->value : $value('status', 'pending') === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="status" /></div>
        <div><label for="priority" class="text-sm font-medium">Priority *</label><select id="priority" name="priority" required class="form-input">@foreach($priorities as $priority)<option value="{{ $priority->value }}" @selected($value('priority', 'normal') instanceof \App\Enums\TaskPriority ? $value('priority')->value === $priority->value : $value('priority', 'normal') === $priority->value)>{{ $priority->label() }}</option>@endforeach</select><x-form-error name="priority" /></div>
        <div><label for="assigned_user_id" class="text-sm font-medium">Assigned user</label><select id="assigned_user_id" name="assigned_user_id" class="form-input"><option value="">Unassigned</option>@foreach($assignees as $assignee)<option value="{{ $assignee->id }}" @selected((string) $value('assigned_user_id') === (string) $assignee->id)>{{ $assignee->name }}</option>@endforeach</select><x-form-error name="assigned_user_id" /></div>
        <div><label for="subject" class="text-sm font-medium">Associated CRM record</label><select id="subject" name="subject" class="form-input"><option value="">Standalone task</option><optgroup label="Contacts">@foreach($contacts as $contact)<option value="contact:{{ $contact->id }}" @selected($subject === 'contact:'.$contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company : '' }}</option>@endforeach</optgroup><optgroup label="Properties">@foreach($properties as $property)<option value="property:{{ $property->id }}" @selected($subject === 'property:'.$property->id)>{{ $property->address }}, {{ $property->city }}, {{ $property->state }}</option>@endforeach</optgroup><optgroup label="Deals">@foreach($deals as $deal)<option value="deal:{{ $deal->id }}" @selected($subject === 'deal:'.$deal->id)>{{ $deal->deal_number }} — {{ $deal->title }}</option>@endforeach</optgroup>@if($surplusCases->isNotEmpty())<optgroup label="Surplus cases">@foreach($surplusCases as $case)<option value="surplus:{{ $case->id }}" @selected($subject === 'surplus:'.$case->id)>{{ $case->case_number }} — {{ $case->status->label() }}</option>@endforeach</optgroup>@endif @if($preAuctionCases->isNotEmpty())<optgroup label="PreTax Auction acquisitions">@foreach($preAuctionCases as $case)<option value="pre_auction:{{ $case->id }}" @selected($subject === 'pre_auction:'.$case->id)>{{ $case->case_number }} — {{ $case->status->label() }}</option>@endforeach</optgroup>@endif</select><x-form-error name="subject" /></div>
    </div></section>

    <section><h2 class="font-semibold">Schedule and reminder</h2><div class="mt-4 grid gap-5 sm:grid-cols-2">
        <div><label for="due_at" class="text-sm font-medium">Due date and time</label><input id="due_at" name="due_at" type="datetime-local" value="{{ old('due_at', isset($task) ? $task->due_at?->format('Y-m-d\TH:i') : data_get($defaults ?? [], 'due_at')) }}" class="form-input"><x-form-error name="due_at" /></div>
        <div><label for="reminder_at" class="text-sm font-medium">Reminder date and time</label><input id="reminder_at" name="reminder_at" type="datetime-local" value="{{ old('reminder_at', isset($task) ? $task->reminder_at?->format('Y-m-d\TH:i') : data_get($defaults ?? [], 'reminder_at')) }}" class="form-input"><p class="mt-1 text-xs text-slate-500">Creates a private in-app reminder for the assigned user.</p><x-form-error name="reminder_at" /></div>
        <div class="sm:col-span-2"><label class="inline-flex items-center gap-2 text-sm font-medium"><input type="checkbox" x-model="recurring" class="rounded border-slate-300"> Repeat this task</label></div>
        <template x-if="recurring"><div class="contents"><div><label for="recurrence_frequency" class="text-sm font-medium">Frequency *</label><select id="recurrence_frequency" name="recurrence_frequency" class="form-input"><option value="">Choose frequency</option>@foreach($recurrences as $recurrence)<option value="{{ $recurrence->value }}" @selected($selectedRecurrence === $recurrence->value)>{{ $recurrence->label() }}</option>@endforeach</select><x-form-error name="recurrence_frequency" /></div><div><label for="recurrence_interval" class="text-sm font-medium">Repeat every</label><input id="recurrence_interval" name="recurrence_interval" type="number" min="1" max="52" value="{{ $value('recurrence_interval', 1) }}" class="form-input"><p class="mt-1 text-xs text-slate-500">For example, 2 means every two weeks when frequency is Weekly.</p><x-form-error name="recurrence_interval" /></div><div><label for="recurrence_ends_at" class="text-sm font-medium">Recurrence ends</label><input id="recurrence_ends_at" name="recurrence_ends_at" type="datetime-local" value="{{ old('recurrence_ends_at', isset($task) ? $task->recurrence_ends_at?->format('Y-m-d\TH:i') : '') }}" class="form-input"><x-form-error name="recurrence_ends_at" /></div></div></template>
    </div></section>
</div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ isset($task) ? route('tasks.show', $task) : route('tasks.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">{{ isset($task) ? 'Save task' : 'Create task' }}</button></div>
