<x-layouts.app title="{{ $task->title }}" heading="Task" subheading="Assignment and execution details">
    <div class="mx-auto max-w-5xl">
        <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div class="flex flex-wrap items-center gap-2"><h2 class="text-2xl font-bold tracking-tight">{{ $task->title }}</h2><span class="rounded-full bg-slate-200 px-2.5 py-1 text-xs font-semibold dark:bg-slate-800">{{ $task->status->label() }}</span><span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-semibold text-amber-800 dark:bg-amber-950 dark:text-amber-300">{{ $task->priority->label() }}</span></div><p class="mt-2 text-sm text-slate-500">Created {{ $task->created_at->format('M j, Y g:i A') }}</p></div><div class="flex flex-wrap gap-2">@if($task->status !== \App\Enums\TaskStatus::Completed) @can('update', $task)<form method="POST" action="{{ route('tasks.complete', $task) }}">@csrf @method('PATCH')<button class="rounded-lg border border-emerald-300 px-4 py-2 text-sm font-semibold text-emerald-700 dark:border-emerald-900 dark:text-emerald-400">Complete</button></form>@endcan @endif @can('update', $task)<a href="{{ route('tasks.edit', $task) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Edit</a>@endcan @can('delete', $task)<form method="POST" action="{{ route('tasks.destroy', $task) }}" onsubmit="return confirm('Archive this task?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm font-medium text-rose-700 dark:border-rose-900 dark:text-rose-400">Archive</button></form>@endcan</div></div>

        <div class="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]">
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 class="font-semibold">Description</h3><p class="mt-4 whitespace-pre-line text-sm leading-6 text-slate-600 dark:text-slate-300">{{ $task->description ?: 'No description was added.' }}</p></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 class="font-semibold">Assignment</h3><dl class="mt-4 space-y-4 text-sm"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Assigned to</dt><dd class="mt-1">{{ $task->assignedUser?->name ?? 'Unassigned' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Associated record</dt><dd class="mt-1">@if($task->taskable instanceof \App\Models\Contact)<a href="{{ route('contacts.show', $task->taskable) }}" class="font-medium text-amber-700 hover:underline dark:text-amber-400">{{ $task->taskable->full_name }}</a>@elseif($task->taskable instanceof \App\Models\Property)<a href="{{ route('properties.show', $task->taskable) }}" class="font-medium text-amber-700 hover:underline dark:text-amber-400">{{ $task->taskable->full_address }}</a>@elseif($task->taskable instanceof \App\Models\Deal)<a href="{{ route('deals.show', $task->taskable) }}" class="font-medium text-amber-700 hover:underline dark:text-amber-400">{{ $task->taskable->title }}</a>@elseif($task->taskable instanceof \App\Models\SurplusCase)<a href="{{ route('surplus.show', $task->taskable) }}" class="font-medium text-amber-700 hover:underline dark:text-amber-400">{{ $task->taskable->case_number }}</a>@elseif($task->taskable instanceof \App\Models\PreAuctionAcquisition)<a href="{{ route('pre-auction.show', $task->taskable) }}" class="font-medium text-amber-700 hover:underline dark:text-amber-400">{{ $task->taskable->case_number }}</a>@else Standalone task @endif</dd></div></dl></section>
        </div>

        <div class="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            @foreach([['Due', $task->due_at?->format('M j, Y g:i A')], ['Reminder', $task->reminder_at?->format('M j, Y g:i A')], ['Completed', $task->completed_at?->format('M j, Y g:i A')]] as [$label, $value])<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-2 text-sm font-medium">{{ $value ?: '—' }}</p></section>@endforeach
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Recurrence</p><p class="mt-2 text-sm font-medium">@if($task->recurrence_frequency)Every {{ $task->recurrence_interval > 1 ? $task->recurrence_interval.' ' : '' }}{{ str($task->recurrence_frequency->value)->plural($task->recurrence_interval) }}@else Not recurring @endif</p>@if($task->recurrence_ends_at)<p class="mt-1 text-xs text-slate-500">Ends {{ $task->recurrence_ends_at->format('M j, Y') }}</p>@endif</section>
        </div>
        <a href="{{ route('tasks.index') }}" class="mt-6 inline-flex text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">← Back to tasks</a>
    </div>
</x-layouts.app>
