@csrf
@isset($deal) @method('PUT') @endisset
@php($value = fn(string $key, mixed $default = null) => old($key, isset($deal) ? data_get($deal, $key) : request($key, $default)))
<div class="space-y-8">
    <section><h2 class="font-semibold">Deal information</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <div class="sm:col-span-2"><label for="title" class="text-sm font-medium">Deal title *</label><input id="title" name="title" required maxlength="180" value="{{ $value('title') }}" class="form-input"><x-form-error name="title" /></div>
        <div><label for="type" class="text-sm font-medium">Classification *</label><select id="type" name="type" required class="form-input">@foreach($dealTypes as $type)<option value="{{ $type->value }}" @selected(($value('type','acquisition') instanceof \App\Enums\DealType ? $value('type')->value : $value('type','acquisition')) === $type->value)>{{ $type->label() }}</option>@endforeach</select><x-form-error name="type" /></div>
        <div><label for="status" class="text-sm font-medium">Deal status *</label><select id="status" name="status" required class="form-input">@foreach($dealStatuses as $status)<option value="{{ $status->value }}" @selected(($value('status','draft') instanceof \App\Enums\DealStatus ? $value('status')->value : $value('status','draft')) === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-form-error name="status" /></div>
        <div><label for="property_id" class="text-sm font-medium">Property</label><select id="property_id" name="property_id" class="form-input"><option value="">No property selected</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected((string)$value('property_id') === (string)$property->id)>{{ $property->address }} · {{ $property->city }}, {{ $property->state }}</option>@endforeach</select><x-form-error name="property_id" /></div>
        <div><label for="primary_contact_id" class="text-sm font-medium">Primary contact</label><select id="primary_contact_id" name="primary_contact_id" class="form-input"><option value="">No primary contact</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string)$value('primary_contact_id') === (string)$contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' · '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="primary_contact_id" /></div>
        <div><label for="assigned_user_id" class="text-sm font-medium">Assigned user</label><select id="assigned_user_id" name="assigned_user_id" class="form-input"><option value="">Unassigned</option>@foreach($assignees as $user)<option value="{{ $user->id }}" @selected((string)$value('assigned_user_id') === (string)$user->id)>{{ $user->name }}</option>@endforeach</select><x-form-error name="assigned_user_id" /></div>
        <div><label for="source" class="text-sm font-medium">Source</label><input id="source" name="source" maxlength="120" value="{{ $value('source') }}" class="form-input" placeholder="Referral, auction, direct mail..."><x-form-error name="source" /></div>
    </div></section>

    <section><h2 class="font-semibold">Dates</h2><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach(['contract_date'=>'Contract date','due_diligence_deadline'=>'Due-diligence deadline','projected_close_date'=>'Projected close','actual_close_date'=>'Actual close'] as $key=>$label)<div><label for="{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" type="date" value="{{ old($key, isset($deal) ? $deal->{$key}?->format('Y-m-d') : '') }}" class="form-input"><x-form-error name="{{ $key }}" /></div>@endforeach</div></section>

    @if(auth()->user()->canViewPropertyFinancials())<section><h2 class="font-semibold">Deal economics</h2><p class="mt-1 text-sm text-slate-500">Deal-specific amounts do not overwrite authoritative Property Financials.</p><div class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">@foreach(['offer_amount'=>'Offer amount','contract_amount'=>'Contract amount','earnest_money'=>'Earnest money','projected_revenue'=>'Projected revenue','actual_revenue'=>'Actual revenue'] as $key=>$label)<div><label for="{{ $key }}" class="text-sm font-medium">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" type="number" min="0" step="0.01" value="{{ $value($key) }}" class="form-input"><x-form-error name="{{ $key }}" /></div>@endforeach</div></section>@endif

    @if(auth()->user()->canViewPropertySourceDocuments())<section><h2 class="font-semibold">Deal documents</h2><div class="mt-4"><label for="document_drive_url" class="text-sm font-medium">Private Drive folder</label><input id="document_drive_url" name="document_drive_url" type="url" value="{{ $value('document_drive_url') }}" placeholder="https://drive.google.com/drive/folders/..." class="form-input"><x-form-error name="document_drive_url" /></div></section>@endif
    <section><h2 class="font-semibold">Notes</h2><textarea name="notes" rows="7" maxlength="50000" class="form-input">{{ $value('notes') }}</textarea><x-form-error name="notes" /></section>
</div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ isset($deal) ? route('deals.show',$deal) : route('deals.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950">{{ isset($deal) ? 'Save deal' : 'Create deal' }}</button></div>
