<x-layouts.app title="{{ $deal->title }}" heading="{{ $deal->title }}" subheading="{{ $deal->deal_number }} · {{ $deal->type->label() }}">
    <div class="mx-auto max-w-6xl">
        <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-start">
            <div class="flex flex-wrap gap-2"><span class="rounded-full bg-slate-200 px-3 py-1 text-xs font-semibold dark:bg-slate-800">{{ $deal->status->label() }}</span><span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800 dark:bg-amber-950 dark:text-amber-300">{{ $deal->type->label() }}</span></div>
            <div class="flex flex-wrap gap-2">@can('create', \App\Models\OutboundEmail::class)<a href="{{ route('email.create',['related_type'=>'deal','related_id'=>$deal->id]) }}" class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950">Send email</a>@endcan @can('update',$deal)<a href="{{ route('deals.edit',$deal) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Edit deal</a>@endcan @can('delete',$deal)<form method="POST" action="{{ route('deals.destroy',$deal) }}" onsubmit="return confirm('Archive this deal?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm font-medium text-rose-700 dark:border-rose-900 dark:text-rose-400">Archive</button></form>@endcan</div>
        </div>

        <div class="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]">
            <div class="space-y-6">
                <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Deal overview</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2">
                    <div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Property</dt><dd class="mt-1 text-sm">@if($deal->property)<a href="{{ route('properties.show',$deal->property) }}" class="font-semibold text-amber-700 hover:underline dark:text-amber-400">{{ $deal->property->address }}</a><span class="block text-xs text-slate-500">{{ $deal->property->city }}, {{ $deal->property->state }} {{ $deal->property->postal_code }}</span>@else — @endif</dd></div>
                    <div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">Primary contact</dt><dd class="mt-1 text-sm">@if($deal->primaryContact)<a href="{{ route('contacts.show',$deal->primaryContact) }}" class="font-semibold text-amber-700 hover:underline dark:text-amber-400">{{ $deal->primaryContact->full_name }}</a><span class="block text-xs text-slate-500">{{ $deal->primaryContact->company ?: $deal->primaryContact->email }}</span>@else — @endif</dd></div>
                    @foreach([['Assigned to',$deal->assignedUser?->name],['Source',$deal->source]] as [$label,$value])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm">{{ $value ?: '—' }}</dd></div>@endforeach
                </dl></section>

                <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Timeline</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach([['Contract date',$deal->contract_date],['Due diligence',$deal->due_diligence_deadline],['Projected close',$deal->projected_close_date],['Actual close',$deal->actual_close_date]] as [$label,$date])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-medium">{{ $date?->format('M j, Y') ?: '—' }}</dd></div>@endforeach</dl></section>

                @can('viewFinancials',$deal)<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Deal economics</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach([['Offer amount',$deal->offer_amount],['Contract amount',$deal->contract_amount],['Earnest money',$deal->earnest_money],['Projected revenue',$deal->projected_revenue],['Actual revenue',$deal->actual_revenue]] as [$label,$amount])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-lg font-semibold">{{ $amount !== null ? '$'.number_format((float)$amount,2) : '—' }}</dd></div>@endforeach</dl></section>@endcan

                @can('viewFinancials',$deal)
                    @if($deal->property)
                        <section class="rounded-2xl border border-amber-200 bg-amber-50/60 p-6 shadow-sm dark:border-amber-900 dark:bg-amber-950/20">
                            <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 class="font-semibold">Live property financials</h2><p class="mt-1 text-xs text-slate-500">Authoritative values synced from the linked property. Deal economics above remain transaction-specific.</p></div><a href="{{ route('financials.properties.edit',$deal->property) }}" class="text-xs font-semibold text-amber-700 hover:underline dark:text-amber-400">Update property financials</a></div>
                            <dl class="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach([['All-in amount',$deal->property->all_in_amount],['Expected sale',$deal->property->expected_sales_price],['Expected profit',$deal->property->expected_profit],['Actual profit',$deal->property->actual_profit]] as [$label,$amount])<div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 text-lg font-semibold">{{ $amount !== null ? (((float)$amount < 0 ? '−$' : '$').number_format(abs((float)$amount),2)) : '—' }}</dd></div>@endforeach</dl>
                        </section>
                    @endif
                @endcan

                <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Notes</h2><p class="mt-4 whitespace-pre-line text-sm leading-6 text-slate-600 dark:text-slate-300">{{ $deal->notes ?: 'No notes have been added.' }}</p></section>
            </div>

            <div class="space-y-6">
                @can('viewDocuments',$deal)<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold">Documents</h2>@if($deal->document_drive_url)<a href="{{ $deal->document_drive_url }}" target="_blank" rel="noopener noreferrer" class="mt-4 inline-flex text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Open private Drive folder ↗</a>@else<p class="mt-3 text-sm text-slate-500">No document folder is linked.</p>@endif</section>@endcan

                <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold">Deal parties</h2><p class="mt-1 text-xs text-slate-500">Contacts and their role in this transaction.</p></div></div>
                    @can('update',$deal)<form method="POST" action="{{ route('deals.contacts.store',$deal) }}" class="mt-4 grid gap-3">@csrf<select name="contact_id" required class="form-input mt-0"><option value="">Select contact</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}">{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company : '' }}</option>@endforeach</select><select name="role" required class="form-input mt-0">@foreach($contactRoles as $role)<option value="{{ $role->value }}">{{ $role->label() }}</option>@endforeach</select><button class="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">Add party</button></form>@endcan
                    <div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($deal->contacts as $contact)<div class="flex items-center justify-between gap-3 py-3"><div><a href="{{ route('contacts.show',$contact) }}" class="text-sm font-semibold hover:text-amber-600">{{ $contact->full_name }}</a><p class="mt-1 text-xs text-slate-500">{{ \App\Enums\DealContactRole::tryFrom($contact->pivot->role)?->label() ?? str($contact->pivot->role)->headline() }}</p></div>@can('update',$deal)<form method="POST" action="{{ route('deals.contacts.destroy',[$deal,$contact->pivot->id]) }}" onsubmit="return confirm('Remove this party from the deal?')">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600">Remove</button></form>@endcan</div>@empty<p class="py-4 text-sm text-slate-500">No additional deal parties.</p>@endforelse</div>
                </section>

                <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold">Tasks</h2><p class="mt-1 text-xs text-slate-500">Work assigned directly to this deal.</p></div>@can('create',\App\Models\Task::class)<a href="{{ route('tasks.create',['subject'=>'deal:'.$deal->id]) }}" class="text-xs font-semibold text-amber-700 hover:underline dark:text-amber-400">Add task</a>@endcan</div><div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($deal->tasks as $task)<a href="{{ route('tasks.show',$task) }}" class="block py-3 hover:text-amber-700"><p class="text-sm font-medium">{{ $task->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $task->status->label() }} · {{ $task->assignedUser?->name ?? 'Unassigned' }} · {{ $task->due_at?->format('M j, Y') ?? 'No due date' }}</p></a>@empty<p class="py-4 text-sm text-slate-500">No tasks are associated with this deal.</p>@endforelse</div></section>
            </div>
        </div>
        <x-email-history :record="$deal" />
        <a href="{{ route('deals.index') }}" class="mt-6 inline-flex text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">← Back to deals</a>
    </div>
</x-layouts.app>
