@csrf
@php
    $templateMap = $templates->mapWithKeys(fn($item) => [(string) $item->id => ['subject' => $item->subject, 'body' => $item->body_text, 'attachments' => $item->attachments->pluck('original_name')->values()]]);
    $contactMap = $contacts->mapWithKeys(fn($item) => [(string) $item->id => $item->email]);
    $selectedContactId = old('primary_contact_id', $email->primary_contact_id ?? $selectedContact?->id);
    $defaultTo = old('to', isset($email) ? implode(', ', $email->to_json) : ($selectedContact?->email ?? ''));
    $selectedRelatedRecord = old('related_record', $related ? $relatedType.':'.$related->id : '');
@endphp
<div x-data="{ templates: @js($templateMap), contacts: @js($contactMap), selectedTemplateId: @js((string) old('armory_email_template_id', $email->armory_email_template_id ?? '')), linkLabel: '', linkUrl: '', linkError: '', applyTemplate(id) { this.selectedTemplateId=id; if (!id || !this.templates[id]) return; document.getElementById('subject').value=this.templates[id].subject; document.getElementById('body_text').value=this.templates[id].body; }, applyContact(id) { if (id && this.contacts[id]) document.getElementById('to').value=this.contacts[id]; }, insertLink() { const raw=this.linkUrl.trim(); let parsed; try { parsed=new URL(raw); } catch (error) { this.linkError='Enter a complete URL beginning with https://'; return; } if (!['http:', 'https:'].includes(parsed.protocol)) { this.linkError='Only http:// and https:// links are allowed.'; return; } const field=document.getElementById('body_text'); const label=(this.linkLabel.trim() || raw).replace(/[\[\]]/g, ''); const markup='['+label+']('+parsed.toString()+')'; const start=field.selectionStart; field.value=field.value.slice(0,start)+markup+field.value.slice(field.selectionEnd); field.focus(); field.selectionStart=field.selectionEnd=start+markup.length; this.linkLabel=''; this.linkUrl=''; this.linkError=''; } }" class="grid gap-5 sm:grid-cols-2">
    <div class="sm:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-200"><strong>From:</strong> {{ config('mail.from.name') }} &lt;{{ config('mail.from.address') }}&gt;. Saving this form does not send anything.</div>
    <div class="sm:col-span-2"><label for="related_record" class="text-sm font-medium">Related CRM record</label><select id="related_record" name="related_record" class="form-input"><option value="">No related record</option>@if($related && !$relatedOptions->contains('value', $selectedRelatedRecord))<option value="{{ $selectedRelatedRecord }}" selected>{{ class_basename($related) }} #{{ $related->id }} — current linked record</option>@endif @foreach($relatedOptions as $option)<option value="{{ $option['value'] }}" @selected($selectedRelatedRecord === $option['value'])>{{ $option['label'] }}</option>@endforeach</select><x-form-error name="related_record" /><x-form-error name="related_id" /><p class="mt-1 text-xs text-slate-500">Choose the exact Property, Deal, Surplus case, or PreTax Auction file that supplies authorized merge-field values.</p></div>
    <div><label for="primary_contact_id" class="text-sm font-medium">CRM contact</label><select id="primary_contact_id" name="primary_contact_id" class="form-input" @change="applyContact($event.target.value)"><option value="">No linked contact</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string)$selectedContactId === (string)$contact->id)>{{ trim($contact->first_name.' '.$contact->last_name) }} — {{ $contact->email }}</option>@endforeach</select><x-form-error name="primary_contact_id" /></div>
    <div><label for="armory_email_template_id" class="text-sm font-medium">Armory template</label><select id="armory_email_template_id" name="armory_email_template_id" class="form-input" @change="applyTemplate($event.target.value)"><option value="">Write manually</option>@foreach($templates as $template)<option value="{{ $template->id }}" @selected((string)old('armory_email_template_id', $email->armory_email_template_id ?? '') === (string)$template->id)>{{ $template->name }}</option>@endforeach</select><template x-if="selectedTemplateId && templates[selectedTemplateId]?.attachments?.length"><p class="mt-2 text-xs font-semibold text-amber-700 dark:text-amber-400">Template attachments: <span x-text="templates[selectedTemplateId].attachments.join(', ')"></span>. They are added when this draft is saved.</p></template></div>
    <div class="sm:col-span-2"><label for="to" class="text-sm font-medium">To</label><textarea id="to" name="to" required rows="2" class="form-input" placeholder="name@example.com">{{ $defaultTo }}</textarea><x-form-error name="to" /><p class="mt-1 text-xs text-slate-500">Separate multiple addresses with commas or new lines.</p></div>
    <div><label for="cc" class="text-sm font-medium">CC</label><textarea id="cc" name="cc" rows="2" class="form-input">{{ old('cc', isset($email) ? implode(', ', $email->cc_json ?? []) : '') }}</textarea><x-form-error name="cc" /></div>
    <div><label for="bcc" class="text-sm font-medium">BCC</label><textarea id="bcc" name="bcc" rows="2" class="form-input">{{ old('bcc', isset($email) ? implode(', ', $email->bcc_json ?? []) : '') }}</textarea><x-form-error name="bcc" /></div>
    <div class="sm:col-span-2"><label for="subject" class="text-sm font-medium">Subject</label><input id="subject" name="subject" required maxlength="255" value="{{ old('subject', $email->subject ?? '') }}" class="form-input"><x-form-error name="subject" /></div>
    <div class="sm:col-span-2"><label for="body_text" class="text-sm font-medium">Message</label><textarea id="body_text" name="body_text" required rows="16" maxlength="500000" class="form-input">{{ old('body_text', $email->body_text ?? '') }}</textarea><x-form-error name="body_text" /><p class="mt-1 text-xs text-slate-500">Supported template fields are replaced from the authorized linked CRM record. Unresolved fields block sending.</p></div>
    <section class="sm:col-span-2 rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800/50">
        <h3 class="text-sm font-semibold">Insert a hyperlink</h3>
        <p class="mt-1 text-xs text-slate-500">Add clickable text at the current cursor position in your message. Only HTTP and HTTPS destinations are allowed.</p>
        <div class="mt-3 grid gap-3 sm:grid-cols-[1fr_1.5fr_auto]"><div><label for="link_label" class="text-xs font-medium">Link text</label><input id="link_label" type="text" x-model="linkLabel" class="form-input" placeholder="View the property"></div><div><label for="link_url" class="text-xs font-medium">Destination URL</label><input id="link_url" type="url" x-model="linkUrl" class="form-input" placeholder="https://valorventure.us/"></div><button type="button" @click="insertLink()" class="self-end rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700 dark:bg-amber-400 dark:text-slate-950 dark:hover:bg-amber-300">Insert link</button></div>
        <p x-show="linkError" x-text="linkError" class="mt-2 text-xs font-semibold text-red-600"></p>
        <p class="mt-2 text-xs text-slate-500">You can also type links as <code>[link text](https://example.com)</code>.</p>
    </section>
    <div><label for="email_signature_id" class="text-sm font-medium">Signature</label><select id="email_signature_id" name="email_signature_id" class="form-input">@foreach($signatures as $signature)<option value="{{ $signature->id }}" @selected((string)old('email_signature_id', $email->email_signature_id ?? $signatures->firstWhere('is_default', true)?->id) === (string)$signature->id)>{{ $signature->name }}{{ $signature->is_default ? ' (default)' : '' }}</option>@endforeach</select><x-form-error name="email_signature_id" /></div>
    <div><label for="attachments" class="text-sm font-medium">Attachments</label><input id="attachments" name="attachments[]" type="file" multiple class="form-input" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.jpg,.jpeg,.png"><x-form-error name="attachments" /><x-form-error name="attachments.*" /><p class="mt-1 text-xs text-slate-500">Select up to {{ config('email.max_attachments') }} files, {{ config('email.attachment_max_kb') / 1024 }} MB each. PDF, Word, Excel, CSV, text, JPG, and PNG are supported. Files are stored privately until delivery.</p>@isset($email) @if($email->attachments->isNotEmpty())<p class="mt-2 text-xs font-semibold text-slate-600 dark:text-slate-300">Already attached: {{ $email->attachments->pluck('original_name')->join(', ') }}</p>@endif @endisset</div>
    <section class="sm:col-span-2 rounded-xl border border-slate-200 bg-slate-50 p-5 dark:border-slate-700 dark:bg-slate-800/50">
        <h3 class="text-sm font-semibold">Available merge fields</h3>
        <p class="mt-1 text-xs text-slate-500">Insert these exactly as shown. Values come only from the selected contact or linked CRM record and are displayed on the review screen before sending.</p>
        <div class="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($mergeTags as $tag => $label)<button type="button" x-on:click="const field=document.getElementById('body_text'); const start=field.selectionStart; field.value=field.value.slice(0,start)+'{{ $tag }}'+field.value.slice(field.selectionEnd); field.focus(); field.selectionStart=field.selectionEnd=start+'{{ $tag }}'.length" class="rounded-lg bg-white px-3 py-2 text-left hover:ring-2 hover:ring-amber-300 dark:bg-slate-900"><code class="text-xs font-semibold text-amber-700 dark:text-amber-400">{{ $tag }}</code><span class="mt-1 block text-xs text-slate-500">{{ $label }}</span></button>@endforeach</div>
        <p class="mt-3 text-xs text-slate-500">Select a field to insert it at the cursor in the message. Missing values remain visible and block delivery rather than being invented.</p>
    </section>
</div>
<div class="mt-6 flex justify-end gap-3"><a href="{{ isset($email) ? route('email.show', $email) : route('email.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button type="submit" form="email-compose-form" class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">Save draft</button></div>
