<x-layouts.app title="Email: {{ $email->subject }}" heading="Email Review" subheading="Review delivery details and status">
    @include('email._navigation', ['active' => 'messages'])
    <div class="mx-auto grid max-w-6xl gap-6 lg:grid-cols-[1fr_320px]">
        <main class="space-y-5">
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-widest text-slate-500">{{ $email->status->label() }}</p><h2 class="mt-2 text-xl font-bold">{{ $previewSubject }}</h2></div>@can('update', $email)<a href="{{ route('email.edit', $email) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold dark:border-slate-700">Edit draft</a>@endcan</div>
                <dl class="mt-6 grid gap-3 text-sm sm:grid-cols-[100px_1fr]"><dt class="font-semibold text-slate-500">From</dt><dd>{{ $email->from_name }} &lt;{{ $email->from_address }}&gt;</dd><dt class="font-semibold text-slate-500">To</dt><dd>{{ implode(', ', $email->to_json) }}</dd>@if($email->cc_json)<dt class="font-semibold text-slate-500">CC</dt><dd>{{ implode(', ', $email->cc_json) }}</dd>@endif @if($email->bcc_json)<dt class="font-semibold text-slate-500">BCC</dt><dd>{{ implode(', ', $email->bcc_json) }}</dd>@endif</dl>
                @if($unresolved)<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/40 dark:text-red-200"><strong>Cannot send yet:</strong> these fields have no authorized CRM value: {{ implode(', ', $unresolved) }}. Edit the draft or link a record containing the missing information.</div>@endif
                <div class="prose prose-slate mt-6 max-w-none rounded-xl border border-slate-200 bg-slate-50 p-5 text-sm leading-7 dark:prose-invert dark:border-slate-700 dark:bg-slate-800/60">{!! $previewHtml !!}</div>
            </section>
            @if($email->attachments->isNotEmpty())<section class="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-semibold">Attachments</h3><div class="mt-3 space-y-2">@foreach($email->attachments as $attachment)<a href="{{ route('email.attachments.download', [$email, $attachment]) }}" class="flex justify-between rounded-lg bg-slate-50 px-4 py-3 text-sm hover:text-amber-600 dark:bg-slate-800"><span>{{ $attachment->original_name }}</span><span class="text-slate-500">{{ number_format($attachment->size_bytes / 1024, 1) }} KB</span></a>@endforeach</div></section>@endif
            @if($email->failure_message)<section class="rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/40 dark:text-red-200"><strong>Delivery failed.</strong><p class="mt-2">{{ $email->failure_message }}</p><p class="mt-2">Nothing is marked sent. Review the account configuration before using the manual retry.</p></section>@endif
        </main>
        <aside class="space-y-5">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-semibold">Delivery</h3><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-slate-500">Prepared by</dt><dd class="font-medium">{{ $email->user->name }}</dd></div><div><dt class="text-slate-500">Created</dt><dd>{{ $email->created_at->format('M j, Y g:i A') }}</dd></div>@if($email->queued_at)<div><dt class="text-slate-500">Queued</dt><dd>{{ $email->queued_at->format('M j, Y g:i A') }}</dd></div>@endif @if($email->sent_at)<div><dt class="text-slate-500">Sent</dt><dd class="text-emerald-600">{{ $email->sent_at->format('M j, Y g:i A') }}</dd></div>@endif<div><dt class="text-slate-500">Attempts</dt><dd>{{ $email->attempt_count }}</dd></div></dl></section>
            @can('send', $email)<form method="POST" action="{{ route('email.send', $email) }}" class="rounded-2xl border border-amber-300 bg-amber-50 p-5 dark:border-amber-900 dark:bg-amber-950/40">@csrf<input type="hidden" name="review_fingerprint" value="{{ $reviewFingerprint }}"><h3 class="font-semibold text-amber-950 dark:text-amber-100">Approve and send</h3><p class="mt-2 text-sm text-amber-900 dark:text-amber-200">This queues the exact message shown for delivery from info@valorventure.us. It cannot be recalled after SMTP accepts it.</p><label class="mt-4 flex gap-2 text-sm"><input type="checkbox" name="confirm_send" value="1" required><span>I reviewed the recipients, subject, body, and attachments.</span></label><x-form-error name="send" /><x-form-error name="confirm_send" /><button class="mt-4 w-full rounded-lg bg-amber-400 px-4 py-2 text-sm font-bold text-slate-950 hover:bg-amber-300">Queue email for delivery</button></form>@endcan
            @can('cancel', $email)<form method="POST" action="{{ route('email.cancel', $email) }}">@csrf<button class="w-full rounded-lg border border-red-300 px-4 py-2 text-sm font-semibold text-red-700">Cancel queued email</button></form>@endcan
            @can('retry', $email)<form method="POST" action="{{ route('email.retry', $email) }}">@csrf<button class="w-full rounded-lg border border-amber-400 px-4 py-2 text-sm font-semibold">Retry once</button></form>@endcan
            @can('delete', $email)<form method="POST" action="{{ route('email.destroy', $email) }}" onsubmit="return confirm('Delete this unsent draft? It will remain recoverable during the retention period.')">@csrf @method('DELETE')<x-form-error name="delete" /><button class="w-full rounded-lg border border-red-300 px-4 py-2 text-sm font-semibold text-red-700 dark:border-red-900 dark:text-red-400">Delete draft</button></form>@endcan
            @if($email->status === \App\Enums\OutboundEmailStatus::Queued)<p class="rounded-xl bg-slate-100 p-4 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">Stellar's scheduler processes queued email on the next five-minute cron run.</p>@endif
        </aside>
    </div>
</x-layouts.app>
