@csrf
@if(isset($template)) @method('PUT') @endif
<div class="grid gap-5 sm:grid-cols-2">
    <div><label for="name" class="text-sm font-medium">Template name *</label><input id="name" name="name" required maxlength="120" value="{{ old('name', $template->name ?? '') }}" class="form-input"><x-form-error name="name" /></div>
    <div><label for="title" class="text-sm font-medium">Default task title *</label><input id="title" name="title" required maxlength="180" value="{{ old('title', $template->title ?? '') }}" class="form-input"><x-form-error name="title" /></div>
    <div class="sm:col-span-2"><label for="description" class="text-sm font-medium">Default description</label><textarea id="description" name="description" rows="5" class="form-input">{{ old('description', $template->description ?? '') }}</textarea><x-form-error name="description" /></div>
    <div><label for="priority" class="text-sm font-medium">Default priority *</label><select id="priority" name="priority" class="form-input">@foreach($priorities as $priority)<option value="{{ $priority->value }}" @selected(old('priority', isset($template) ? $template->priority->value : 'normal') === $priority->value)>{{ $priority->label() }}</option>@endforeach</select><x-form-error name="priority" /></div>
    <div><label for="due_in_days" class="text-sm font-medium">Due in days</label><input id="due_in_days" name="due_in_days" type="number" min="0" max="3650" value="{{ old('due_in_days', $template->due_in_days ?? '') }}" class="form-input"><x-form-error name="due_in_days" /></div>
    <div><label for="reminder_lead_minutes" class="text-sm font-medium">Reminder lead time (minutes)</label><input id="reminder_lead_minutes" name="reminder_lead_minutes" type="number" min="0" max="525600" value="{{ old('reminder_lead_minutes', $template->reminder_lead_minutes ?? '') }}" class="form-input"><p class="mt-1 text-xs text-slate-500">1440 minutes is one day before the deadline.</p><x-form-error name="reminder_lead_minutes" /></div>
    <div><label for="recurrence_frequency" class="text-sm font-medium">Default recurrence</label><select id="recurrence_frequency" name="recurrence_frequency" class="form-input"><option value="">Does not repeat</option>@foreach($recurrences as $recurrence)<option value="{{ $recurrence->value }}" @selected(old('recurrence_frequency', isset($template) ? $template->recurrence_frequency?->value : '') === $recurrence->value)>{{ $recurrence->label() }}</option>@endforeach</select><x-form-error name="recurrence_frequency" /></div>
    <div><label for="recurrence_interval" class="text-sm font-medium">Recurrence interval</label><input id="recurrence_interval" name="recurrence_interval" type="number" min="1" max="52" value="{{ old('recurrence_interval', $template->recurrence_interval ?? 1) }}" class="form-input"><x-form-error name="recurrence_interval" /></div>
    <div class="sm:col-span-2"><input type="hidden" name="is_active" value="0"><label class="inline-flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $template->is_active ?? true)) class="rounded border-slate-300"> Active template</label></div>
</div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ route('task-templates.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950">{{ isset($template) ? 'Save template' : 'Create template' }}</button></div>
