<x-layouts.app title="Financials · {{ $property->address }}" heading="Property financials" subheading="{{ $property->full_address }}">
    @php($purchaseValue = old('purchase_price',$property->purchase_price ?? 0))
    @php($taxesValue = old('taxes',$property->taxes ?? 0))
    @php($attorneyValue = old('attorney_fees',$property->attorney_fees ?? 0))
    @php($realtorValue = old('realtor_fees',$property->realtor_fees ?? 0))
    @php($otherCostsValue = old('other_costs',$property->other_costs ?? 0))
    @php($expectedSaleValue = old('expected_sales_price',$property->expected_sales_price))
    @php($actualSaleValue = old('actual_sales_price',$property->actual_sales_price))
    <form method="POST" action="{{ route('financials.properties.update',$property) }}" class="mx-auto max-w-5xl space-y-6" x-data="{ purchase: {{ (float) $purchaseValue }}, taxes: {{ (float) $taxesValue }}, attorney: {{ (float) $attorneyValue }}, realtor: {{ (float) $realtorValue }}, other: {{ (float) $otherCostsValue }}, expectedSale: {{ filled($expectedSaleValue) ? (float) $expectedSaleValue : 'null' }}, actualSale: {{ filled($actualSaleValue) ? (float) $actualSaleValue : 'null' }}, allInTotal() { return [this.purchase, this.taxes, this.attorney, this.realtor, this.other].reduce((sum, value) => sum + (Number(value) || 0), 0); }, amount(value) { if (value === null || Number.isNaN(Number(value))) return '—'; return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value)); }, profitCents(sale) { if (sale === null || sale === '') return null; return Math.round(Number(sale) * 100) - Math.round(this.allInTotal() * 100); }, profit(sale) { const cents = this.profitCents(sale); return cents === null ? null : cents / 100; }, distribution(sale, recipient) { const profit = this.profitCents(sale); if (profit === null) return null; const cents = Math.max(profit, 0); const vvr = Math.round(cents * .20); const contactOne = Math.round(cents * .40); if (recipient === 'vvr') return vvr / 100; if (recipient === 'contactOne') return contactOne / 100; return (cents - vvr - contactOne) / 100; } }">
        @csrf @method('PUT')
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="font-semibold">Property economics</h2><p class="mt-1 text-sm text-slate-500">All-in and profit update automatically whenever a cost or sales price changes.</p></div><a href="{{ route('properties.show',$property) }}" class="text-sm font-semibold text-amber-700 hover:underline dark:text-amber-400">Open property</a></div><div class="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            <div><label for="purchase_price" class="text-sm font-medium">Purchase price</label><input id="purchase_price" name="purchase_price" type="number" min="0" step="0.01" x-model.number="purchase" class="form-input"><x-form-error name="purchase_price" /></div>
            <div><label for="taxes" class="text-sm font-medium">Taxes</label><input id="taxes" name="taxes" type="number" min="0" step="0.01" x-model.number="taxes" class="form-input"><x-form-error name="taxes" /></div>
            <div><label for="attorney_fees" class="text-sm font-medium">Attorney fees</label><input id="attorney_fees" name="attorney_fees" type="number" min="0" step="0.01" x-model.number="attorney" class="form-input"><x-form-error name="attorney_fees" /></div>
            <div><label for="realtor_fees" class="text-sm font-medium">Realtor fees</label><input id="realtor_fees" name="realtor_fees" type="number" min="0" step="0.01" x-model.number="realtor" class="form-input"><x-form-error name="realtor_fees" /></div>
            <div><label for="other_costs" class="text-sm font-medium">Other costs</label><input id="other_costs" name="other_costs" type="number" min="0" step="0.01" x-model.number="other" class="form-input"><x-form-error name="other_costs" /></div>
            <div><label for="all_in_amount" class="text-sm font-medium">All-in amount</label><input id="all_in_amount" name="all_in_amount" type="number" step="0.01" :value="allInTotal().toFixed(2)" readonly class="form-input bg-slate-100 font-semibold dark:bg-slate-800"><p class="mt-1 text-xs text-slate-500">Purchase + taxes + attorney + realtor + other</p><x-form-error name="all_in_amount" /></div>
            <div><label for="expected_sales_price" class="text-sm font-medium">Expected sales price</label><input id="expected_sales_price" name="expected_sales_price" type="number" min="0" step="0.01" x-model.number="expectedSale" value="{{ old('expected_sales_price',$property->expected_sales_price) }}" class="form-input"><x-form-error name="expected_sales_price" /></div>
            <div><label for="actual_sales_price" class="text-sm font-medium">Actual sales price</label><input id="actual_sales_price" name="actual_sales_price" type="number" min="0" step="0.01" x-model.number="actualSale" value="{{ old('actual_sales_price',$property->actual_sales_price) }}" class="form-input"><x-form-error name="actual_sales_price" /></div>
            <div class="rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Expected net profit</p><p class="mt-2 text-xl font-bold" x-text="amount(profit(expectedSale))"></p><p class="mt-1 text-xs text-slate-500">Expected sale − all-in</p></div>
        </div></section>

        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div><h2 class="font-semibold">Payment split</h2><p class="mt-1 text-sm text-slate-500">Percentages are fixed at 20% VVR / 40% Contact 1 / 40% Contact 2. Payments are calculated from positive net profit.</p></div><div class="mt-5 grid gap-4 lg:grid-cols-3">
            <article class="rounded-xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900 dark:bg-amber-950/20"><p class="text-xs font-bold uppercase tracking-wide text-amber-700 dark:text-amber-400">20% · VVR</p><p class="mt-3 text-2xl font-bold" x-text="amount(distribution(expectedSale, 'vvr'))"></p><p class="mt-1 text-xs text-slate-500">Expected · Actual: <span x-text="amount(distribution(actualSale, 'vvr'))"></span></p><p class="mt-3 text-xs font-medium">Valor Venture Realty</p></article>
            <article class="rounded-xl border border-slate-200 p-5 dark:border-slate-800"><label for="contact_one_id" class="text-xs font-bold uppercase tracking-wide text-slate-500">40% · Contact 1</label><p class="mt-3 text-2xl font-bold" x-text="amount(distribution(expectedSale, 'contactOne'))"></p><p class="mt-1 text-xs text-slate-500">Expected · Actual: <span x-text="amount(distribution(actualSale, 'contactOne'))"></span></p><select id="contact_one_id" name="contact_one_id" class="form-input mt-4"><option value="">Unassigned</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string) old('contact_one_id',$property->financialSplit?->contact_one_id) === (string) $contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="contact_one_id" /></article>
            <article class="rounded-xl border border-slate-200 p-5 dark:border-slate-800"><label for="contact_two_id" class="text-xs font-bold uppercase tracking-wide text-slate-500">40% · Contact 2</label><p class="mt-3 text-2xl font-bold" x-text="amount(distribution(expectedSale, 'contactTwo'))"></p><p class="mt-1 text-xs text-slate-500">Expected · Actual: <span x-text="amount(distribution(actualSale, 'contactTwo'))"></span></p><select id="contact_two_id" name="contact_two_id" class="form-input mt-4"><option value="">Unassigned</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string) old('contact_two_id',$property->financialSplit?->contact_two_id) === (string) $contact->id)>{{ $contact->full_name }}{{ $contact->company ? ' — '.$contact->company : '' }}</option>@endforeach</select><x-form-error name="contact_two_id" /></article>
        </div><div class="mt-5 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-950"><div class="flex justify-between"><span class="text-slate-500">Actual net profit</span><strong x-text="amount(profit(actualSale))"></strong></div><div class="mt-2 flex justify-between"><span class="text-slate-500">Actual distributable amount</span><strong x-text="profit(actualSale) === null ? '—' : amount(Math.max(profit(actualSale), 0))"></strong></div></div></section>

        <div class="flex justify-end gap-3"><a href="{{ route('financials.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Cancel</a><button class="rounded-lg bg-amber-400 px-5 py-2 text-sm font-semibold text-slate-950 hover:bg-amber-300">Save financials</button></div>
    </form>
</x-layouts.app>
